### ISSUE TITLE
SpriteBatch devours memory

### ISSUE THREAD

**Issue by kg** [MonoGame/MonoGame#1261]
The default buffer size for SpriteBatch (10000 vertices/draw calls respectively) is too high and makes it difficult to use on PlayStation Mobile - being generous, that's at least a megabyte of memory (104 bytes per SpriteBatchItem, not even counting runtime overhead since it's a class...) which easily can run you up against the memory limit on that platform (it's 96MB total, for everything, including textures and buffers).

I don't know what the right buffer size is, though.

**Comment by tomspilman** [comment]
@nkast - Any thoughts on this one?

**Comment by nkast** [comment]
The garbage problem was originally with PSM, right? 
As for the size of SpriteBatchItems it's a fraction of assets memory (textures/sounds,), it will only be a problem if you create multiple SpriteBatch instances. We can lower the initial size but them someone will say it's still a waste or memory because every game is different. We now grow the array by a percentage to avoid constantly generating garbage so the size will always be a bit larger that what we need.
One way to make this work is by having an overload actor to set the initial size of SpriteBatchItems by the user (and Vertices maybe?). We need some way to report the max number of spritebatchItems each spritebatch instance is using so the user can go back and copy that number in the constructor.

**Comment by tomspilman** [comment]
> overload actor to set the initial size of SpriteBatchItems by the user 

So like a static 'SpriteBatch.DefaultBatchSize' that you can change on startup.


> if you create multiple SpriteBatch instances

The simple fix is just not to do that.  There is little benefit to making multiple instances like that.  Your goal should be to have as few as possible.

**Comment by nkast** [comment]
Having a static field will not work because then you set it to the max and waste memory on every other instance. I agree that ideally you must have a single instance but we can't enforce this, often you have reusable components use their own SpriteBatch instance.

**Comment by tomspilman** [comment]
So what about we move `SpriteBatcher.InitialBatchSize`...

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/SpriteBatcher.cs#L63

To `SpriteBatch` and make it a static that can be changed.  This helps the cases where a lower default is better for some platforms.

Second we add a new constructor:  `SpriteBatch(GraphicsDevice graphicsDevice, int initialBatchSize = InitialBatchSize)`.  This lets the user pass a custom batch size to each sprite batch instance they create if wanted.

**Comment by theZMan** [comment]
+1 - You have no idea how often I have wanted that ;-)

Couple of other things.

Maybe make CurrentBatchSize a readonly parameter - its very useful for performance tuning to know how big the buffer has got.

I believe XNA has an upper limit of how big a batch can get... I seem to remember observations from PIX showing me that at some point no matter the sort options a batch will get broken into multiple chunks. There was probably a reason for this... it might be platform specific too. Not sure if MonoGame has a limit or if it will keep growing forever.

**Comment by tomspilman** [comment]
> Maybe make CurrentBatchSize a readonly parameter 

That would be easy to do I think.


> I believe XNA has an upper limit of how big a batch can get

My guess is that is that is because of the diminishing returns from bigger and bigger batch sizes based on some tests on devices.

**Comment by cra0zy** [comment]
Right now, at least from what I remember, the default bugger size is something small, than we double it if the buffer ever exceeds our expectation.
