### ISSUE TITLE
(Android) TouchPanel ReadGesture - game freezes

### ISSUE THREAD

**Issue by DenisGrachev** [MonoGame/MonoGame#1359]
During a porting my games to Android find a bug. Sometimes game freezes at this loop:

while (TouchPanel.IsGestureAvailable)
                    {
                        GestureSample gesture = TouchPanel.ReadGesture();
                    }
At WP,Windows,Linux game works well!

Temporary replaced this code with my own, based on TouchPanel.GetState() with manual tracking.

**Comment by dmanning23** [comment]
I've been doing a lot of Android TouchPanel work, and never seen this bug. This was written against a really old version of MonoGame, it has probably been fixed since then.
Here is a library using the Android TouchPanel that uses the exact code recipe above:
https://github.com/dmanning23/TouchScreenBuddy/blob/3426e1bc2d582e0fef8f149bc39e1f870a27e09e/TouchScreenBuddy/TouchScreenBuddy.SharedProject/TouchManager.cs#L113

And here is a sample project showing several different gestures used on an Android TouchPanel:
https://github.com/dmanning23/TouchBuddyExample

I believe this bug can be closed.

**Comment by Jjagg** [comment]
Thanks @dmanning23 :) Closing!
