### ISSUE TITLE
JSIL Based Implementation

### ISSUE THREAD

**Issue by SamuelEnglard** [MonoGame/MonoGame#1422]
I saw the NaCl implementation to run in a browser but the flaw in that is that it only works in Chrome. JSIL is a program that converts CIL into JavaScript that will run in the browser. It includes XNA support (using Canvas to draw). I was thinking that using this for browser support may make more sense than using NaCl since this would be cross browser.

https://github.com/kevingadd/JSIL

**Comment by CartBlanche** [comment]
@kg What sort of funding is required.

**Comment by kg** [comment]
The funding was being used to pay a contractor (hourly) to do a lot of the heavy lifting because I have other stuff eating my time. We got as far as a simple proof-of-concept using emscripten SDL2 and FNA (because FNA talks directly to SDL2):

http://hildr.luminance.org/SampleFNA/

But there's a lot of additional work that would have to happen for the broad set of released MonoGame titles to work. Even something as simple as that sample game hit some html5 rough edges (like music playback...)

**Comment by RiuSalvi** [comment]
Is there any updates on this monogame to web situation? I want to now more and to help if i can.
