### ISSUE TITLE
XAudio2 might be started on a worker thread

### ISSUE THREAD

**Issue by KonajuGames** [MonoGame/MonoGame#1494]
XAudio2.StartEngine() must be called on the main thread.  The static constructor for SoundEffect is called on the first use of the SoundEffect class.  If this first use is on a worker thread, the static constructor is run in the context of the worker thread and XAudio2.StartEngine() will be called on the worker thread.

I have a pending solution for this (invoking the StartEngine call back to the main thread), but it's not properly working yet.  Raising this issue so it's not forgotten.

**Comment by tomspilman** [comment]
Let's fix this once and for all.

Let's add a platform function for initializing the sound system like `internal static void SoundEffect.PlatformInitializeSystem()`.  Then we should ensure this is called as early as possible during `GamePlatform` initialization.

Secondarily i *think* XNA allows using the sound APIs without initializing a `Game` class.  Let's leave hooks for forcing initialization on first use in those cases.

Let's fix this for 3.6.

**Comment by polsys** [comment]
Regarding the place for the said hook: should it go into the `FrameworkDispatcher`? Some XNA APIs require `FrameworkDispatcher.Update()` be called before using them, so on the first call the appropriate platform initialization functions could be run. That would be easy to extend to other subsystems and would not clutter public `SoundEffect` or other APIs.

**Comment by tomspilman** [comment]
We've never implemented that:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/FrameworkDispatcher.cs

... but we could.  Not sure if this is a good fit for this case, but likely we should be doing some work in `FrameworkDispatcher.Update()` that we currently do in the `PlatformWindow`, `PlatformGame`, or `Game` update methods.

**Comment by Jjagg** [comment]
> Secondarily i think XNA allows using the sound APIs without initializing a Game class. Let's leave hooks for forcing initialization on first use in those cases.

This is correct. I suspect there are static initializers that initialize FrameworkDispatcher or XNA just uses static initializers directly like we do now. When #4675 is merged the first call to FrameworkDispatcher.Update will initialize audio. I suggest we throw an exception when the initialization is not done on the main thread. XNA does not do this, but I think it's a fair way to ensure audio is initialized on the main thread. I'm pretty sure XNA doesn't guarantee this because I can create a DynamicSoundEffectInstance and play it on another thread without first calling FrameworkDispatcher.Initialize.

@KonajuGames Do you remember what issues might occur when XAudio2 is not started on the main thread? I can't find any information about this. The only thing [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.ixaudio2.ixaudio2.startengine(v=vs.85).aspx) says about it is 

> It is invalid to call StartEngine from within a callback (that is, IXAudio2EngineCallback or IXAudio2VoiceCallback).

**Comment by KonajuGames** [comment]
> Do you remember what issues might occur when XAudio2 is not started on the main thread? I can't find any information about this.

I'm certain those MSDN pages have changed since this issue was first opened.  In any case, the FrameworkDispatcher is the correct place to initialize and update the sound system.  XNA had the Game class update the FrameworkDispatcher, which is why FrameworkDispatcher needed to be manually updated when there was no Game class.

**Comment by Jjagg** [comment]
So it's fine like this? We don't throw an exception when the first FrameworkDispatcher.Update call is not done on the main thread?

**Comment by KonajuGames** [comment]
I guess it's a "try it and see" moment.
