### ISSUE TITLE
Song does not loop on Windows 8 with MediaPlayer

### ISSUE THREAD

**Issue by totallyeviljake** [MonoGame/MonoGame#1821]
@borrillis reports that Song is not looping when he uses MediaPlayer.Play(song). The song just plays to end even with MediaPlayer.IsRepeating = true.

**Comment by KonajuGames** [comment]
I'm using the latest DirectX version on Windows 8 desktop and the music is repeating.

**Comment by GAMESTER90** [comment]
Has this yet to be fixed? I'll try to contact the developers...

**Comment by KonajuGames** [comment]
I have used repeating songs in a Windows DirectX project for a while now.
The song duration is zero if the song is loaded through CreateFromUri
because getting the song duration requires loading the song into the
MediaPlayer to get that information.  Once the start has started playing,
the song duration should be available.​

**Comment by MichaelDePiazzi** [comment]
I'm not sure, but this may have possibly been resolved by PR #4090 as it addressed a few song playback issues. Can someone who was having this problem confirm?

**Comment by cra0zy** [comment]
Support for Windows 8.x platforms has been removed, closing...
