### ISSUE TITLE
Add Garbage Free BoundingBox.CreateFromPoints()

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#1880]
The current `BoundingBox.CreateFromPoints()` looks like this...

```
public static BoundingBox CreateFromPoints(IEnumerable<Vector3> points)
{
```

While this is convenient because it can work with anything it.... it generates garbage because of the generic iterator loop.

We should add a List<Vector3> specialization of this function because list iteration is garbage free:

```
public static BoundingBox CreateFromPoints(List<Vector3> points)
```

**Comment by YTN0** [comment]
@tomspilman  I recently ran into this same issue when profiling my code. For now, I just created a local clone of the BoundingBox.CreateFromPoints() API which takes a Vector3[] as input.

Is there a reason we don't just add a couple overloads to BoundingBox.CreateFromPoints() that takes in an array and List (as well as keep the original)?

i.e.

```
BoundingBox.CreateFromPoints(Vector3[] points);
and
BoundingBox.CreateFromPoints(List<Vector3> points);

```

**Comment by willmotil** [comment]
Well if anyone tried to use this in a dynamic way they would be in for pure pain.

I used evil jukes test code and came out with 20 x the total memory footprint to 
![ejsgarbage test](https://user-images.githubusercontent.com/7495196/58312540-7ec92f00-7dd9-11e9-98a3-f31c81718eab.png)
monogame itself in collections over 1 minute.

**Comment by nkast** [comment]
>> Back to the original topic, would IList<> as an overload be sufficient to
call the non-allocating enumerator rather than the specific List<>? Using
IList would potentially allow more containers to use it.​

>> Unfortunately no... only List or Vector3[] would work. This is one of this crappy cases where the best thing is messy.

With an IList<> you are not limited to use `foreach` which creates an enumerator.
There's the option to use a `for` loop and acess the list through an index.

We can plan ahead and add the full signature we are usually end up with when we work with lists. 
The one that has an index and a count. 

`public static BoundingBox CreateFromPoints(IList<Vector3> points, int index = 0, int count = -1)`

FYI, @YTN0
