### ISSUE TITLE
Is there a reason why SpriteBatcher doesn't use a vertex/index buffer pair?

### ISSUE THREAD

**Issue by kg** [MonoGame/MonoGame#2128]
When looking into performance issues in the JSIL MonoGame port, I noticed that SpriteBatcher is doing a lot of extra work for no obvious reason, and it's using DrawUserIndexedPrimitives to flush each batch instead of filling a single index/vertex buffer pair. Filling a single pair would mean that all the queued up drawing operations could be uploaded in one go instead of being uploaded in tiny chunks. For the browser this is really important because the cost of each OpenGL call is _dramatically_ increased due to WebGL's architecture, and a single DrawUserIndexedPrimitives call involves lots of OpenGL calls.

It seems to me like SpriteBatch could fill the actual index/vertex buffers (as arrays) in one go sequentially after it sorts the SpriteBatchItems, upload the full buffers, then render chunks of those buffers when it needs to flush batches. That would cut down on OpenGL calls considerably and I think it'd probably be faster in desktop OpenGL/Direct3D setups as well. Thoughts?

(mumble grumble spritebatch's design is SO bad for performance)

EDIT: For reference, the Platformer2D example seems to be drawing _six vertices at a time_, each draw operation involving the following high cost operations:

Applying all the rendering states (even worse, each DrawUserIndexedPrimitives flags the ib/vb as dirty, so each call to ApplyState is _forced_ to do work here)
Pinning the index/vertex buffers as GCHandles
Applying the current vertex declaration
Filling a temporary index buffer with provided indices
Filling a temporary vertex buffer with provided vertices
Calling vertexAttribPointer repeatedly to set up all the attribute streams

EDIT 2: This is no doubt responsible for some miserable performance on PSM as well. If memory serves, PSM does not like it when you do dozens to hundreds of uploads per frame, and state changes were more expensive there too.

**Comment by vgrudenic** [comment]
@kg Did you ever get a chance to make this change in the end, and possibly benchmark it?

I was about to try the same thing and stumbled upon this thread, if not I'll probably try it myself.

**Comment by nkast** [comment]
That's my take on SpriteBatch. Unfortunately, it doesn't qualify for a PR since it's DX-only & use SharpDX. 


Lumia 620
---------------
Current SpriteBatcher
min:1,43, max:2,86, avg:1,80 (100%)
VertexBuffer (from SickheadGames repo)
min:1,29, max:2,46, avg:1,58 ( 88%)
Mapped VertexBuffer / one time batch/update
min:1,23, max:2,51, avg:1,44 (80%)
Mapped VertexBuffer / one time batch / no Queue<>
min:1,18, max:2,86, avg:1,39 (77%)

Desktop AMD Phenom II x4 3.4GHz
---------------------------
Current SpriteBatcher
min:0.1412, max:1.9286, avg:0.3674 (100%)
Mapped VertexBuffer / one time batch / no Queue<>
min:0.1060, max:1.7683, avg:0.2973 (81%)

https://github.com/nkast/MonoGame/commit/ff959c65698fae6725f486bb634e8f4115254b9c


Some more details...

1) Initialize the pool with new 'SpriteBatchItem' instances in the constructor. Avoid allocation/GC during gameplay.
https://github.com/nkast/MonoGame/blob/ff959c65698fae6725f486bb634e8f4115254b9c/MonoGame.Framework/Graphics/SpriteBatcher.DirectX-OPT.cs#L105-L106

2) Remove '_freeBatchItemQueue.Enqueue(item)' from the inner loop.
https://github.com/mono/MonoGame/blob/1756c713b4aede3db5568f69012daf68be2d8c6a/MonoGame.Framework/Graphics/SpriteBatcher.cs#L272
Instead of a Queue we pool items in a List<> and keep an index to the next free item. After the loop we set the index to 0 to return all the items to the pool.
https://github.com/nkast/MonoGame/blob/ff959c65698fae6725f486bb634e8f4115254b9c/MonoGame.Framework/Graphics/SpriteBatcher.DirectX-OPT.cs#L314-L315

 3) Break the loop into 2 parts, first we set all the Vertices to update the DynamicVertexBuffer once  and then we go through the loop once more to draw. The IndexBuffer remain constant, no need to update it.

4) Instead of going through VertexBuffer.SetData() we map the buffer in-place and write the vertices directly on the mapped memory.
https://github.com/nkast/MonoGame/blob/ff959c65698fae6725f486bb634e8f4115254b9c/MonoGame.Framework/Graphics/SpriteBatcher.DirectX-OPT.cs#L254-L282

**Comment by tomspilman** [comment]
So what I suggest we do is maintain two paths for `SpriteBatch`... not ideal but best for this situation.

To do this we split `SpriteBatcher.cs` up like we do other platform specific parts using partial class features.

We move the code specific to that into a `SpriteBatcher.DUP.cs` specifically for the existing `DrawUserPrim` code that we default to on all non-DirectX platforms.  This maintains the existing performance for GL for the time being.

We then add a `SpriteBatcher.DirectX.cs` which implements the buffer management and submission that is optimal for those platforms.

The trick is going to be how to break up the `SpriteBatcher` functionality so we don't have a bunch of duplicate code in the platform specific bits.

**Comment by nkast** [comment]
Good, I could start moving things around and post a PR when I have something solid.
The change on Queue<> was a list time thing, I can get a separate PR for it.

**Comment by cra0zy** [comment]
Right now its uploading the full buffers, tho I still had to use some hacky things to get some extra performance with the bridge port :thinking: 

Anyway closing this.
