### ISSUE TITLE
Network gamer id is always 255?

### ISSUE THREAD

**Issue by panthernet** [MonoGame/MonoGame#2211]
Tried to play with network in monogame 3.0.1 but it seems that player Id is always 255 making it difficult to distinct network players :( 

Property: NetworkGamer::Id

**Comment by gustavolsson** [comment]
Hi,

I'm trying to port my multiplayer kart racing game to PC and just encountered this issue in the DekstopGL path of MonoGame 3.5.

Has anyone looked into the net code since this issue was opened?

With the exception of NetworkGamer.Id always being 255 for everyone except the host and the lack of SignedInGamer.IsGuest/support for multiple SignedInGamers, the implementation seems to work as it should. I've tested transitions from Lobby to Game state, players joining/leaving and sending messages. I haven't tested host migration yet.
