### ISSUE TITLE
Visual Studio 2012 Project Templates not installing

### ISSUE THREAD

**Issue by Tyyppi77** [MonoGame/MonoGame#2354]
I installed MonoGame yesterday from the link on the website, and on the installation wizard I chose that the VS2012 Project Templates will be installed. No projects were installed, and none are shown in the project templates folder. Can this be caused by the fact that I have an Express verion of the Visual Studio? I'd really appreciate some help here.

EDIT:
For the record, I did actually uncheck the checkboxes for installing Project Templates for VS2010 and VS2013.

**Comment by Apostolique** [comment]
Is it possible that your "Documents" folder has been moved?

For example, normally Templates are installed in:

```C:\Users\Name\Documents\Visual Studio 2017\Templates\ProjectTemplates```

In my case, I move my "Documents" to the F:\ drive:

```F:\Name\Documents\Visual Studio 2017\Templates\ProjectTemplates```

This made the installer get messed up and Visual Studio was unable to find the templates since they weren't getting installed at the right location.

**Comment by Jjagg** [comment]
Closing in favor of #3808.
