### ISSUE TITLE
Missing classes in Microsoft.Framework.Design

### ISSUE THREAD

**Issue by jamesford42** [MonoGame/MonoGame#2707]
For reference:
http://msdn.microsoft.com/en-us/library/Microsoft.Xna.Framework.Design(v=xnagamestudio.40).aspx

We currently have Vector2/3/4TypeConverter (though whether or not they behave exactly like XNA has not been thoroughly verified).

There is also a weird StringToColorConverter currently in the Microsoft.Xna.Framework.Content.Pipeline.Builder.Converters namespace which should 'probably' be the Framework.Design.ColorConverter.

**Comment by flibitijibibo** [comment]
Spent the day writing in the rest of the TypeConverters. The result:

https://github.com/flibitijibibo/FNA/tree/master/src/Design

Some general notes can be found here:

https://github.com/flibitijibibo/FNA/issues/195#issuecomment-159064606

One MonoGame-specific note to add is that, apparently, the TypeConverters do not actually work for anything but strings. I dunno why all this is here just for strings, but in XNA4 that's all they do... hence the base MathTypeHelper class which does just about everything generically except for the actual conversion operations.

If you pull in these classes you'll probably want to reintroduce stuff like the VectorConversions so that it's actually useful for the content pipeline and other similar projects.
