### ISSUE TITLE
The MonoGame Documentation doesn't render properly in Firefox

### ISSUE THREAD

**Issue by ghost** [MonoGame/MonoGame#2912]
I just had a friend notice that the MonoGame documentation web pages don't render properly in Firefox.

I have confirmed this on my own machine running Firefox 23.0.1

http://www.monogame.net/documentation/?page=main

![image](https://cloud.githubusercontent.com/assets/3201643/3884496/1e1656cc-21b0-11e4-986f-2d2d00d8cc8a.png)

**Comment by tgjones** [comment]
I have just had a look at this.

* On the bright side, IE, Chrome, and Firefox are rendering the page consistently.
* On the less-bright side, in all 3 of those browsers, if you make the browser window tall enough, there is a gap between the footer and the bottom of the browser window, as in the most recent screenshot above.

That is because of [this line](https://github.com/mono/MonoGame/blob/develop/Documentation/Styles/MonoGame/html/Root.cshtml#L43), which limits the height to 720px.

It's non-trivial to fix that properly, at least with the current HTML structure.

**Comment by tomspilman** [comment]
I guess we want to fix that line to something like this:
```
var pageHeight = Math.max(contentSize, tocSize, theWindowHeight);
```

**Comment by tgjones** [comment]
I tried that - but it's actually theWindowHeight - heightOfHeaderAndFooter, and that doesn't work because the margins on the header and footer elements mess up the height calculation.

**Comment by tomspilman** [comment]
Yeah.... calculating a good `heightOfHeaderAndFooter` is pretty tricky, but it should be possible.  Luckily at least it doesn't keep the docs from being readable.

**Comment by tgjones** [comment]
This isn't pretty, but it works - change this:

``` js
var pageHeight = Math.max(contentSize, tocSize, 720);
```

to this:

``` js
var maxHeight = $(window).height() - ($('.page-description').outerHeight() + $('.social-footer').outerHeight() + $('.site-footer').outerHeight()) - 12;
var pageHeight = Math.max(contentSize, tocSize, maxHeight);
```

It's still not great though - if you resize the window, the footer doesn't update to match. It's much better to do this sort of thing with plain CSS, not JS, but that would require restructuring the HTML.
