### ISSUE TITLE
Ambiguous terminology. Pipeline.exe, .mgcb, mgcb.exe

### ISSUE THREAD

**Issue by jamesford42** [MonoGame/MonoGame#3243]
Our terminology is very awkward and ambiguous...
1. pipeline - am i referring to the monogame pipeline as a conceptual whole? am i referring to the pipeline executable? Or maybe the monogame.framework.content.pipeline assembly?
2. mgcb - am i referring to the executable or the file extension?

Proposal:
I think that mgcb.exe needs to be renamed, the mgcb file extension should be changed, and pipeline.exe should be renamed. 

The specific names are not important but if it were up to me maybe the following:

rename mgcb.exe to mgbuild.exe - a'la msbuild.exe
rename pipeline.exe to mgbuild-gui.exe
change the .mgcb file extension to mgcontent - a'la XNA's .contentproj

**Comment by DDReaper** [comment]
You never know what you find until someone points it out to you :dancer: 

Copying from my other post:

Can a better name be agreed, for example:

* Content Builder Tool
* Content Pipeline Editor
* Content Package Editor

Ideas?

**Comment by tomspilman** [comment]
> Content Builder Tool

Ideally we would stay way from "Content Builder" to not cause confusion with MGCB.

> Content Pipeline Editor

 "Editor" is maybe a better direction.  That technically is what the Pipeline GUI tool is for...  it is a content project editor.
 
 "Content Pipeline Editor" seems to imply you are editing the "pipeline" when really you are editing the "content".

> Content Package Editor

 "Package" is really not accurate... there is no package involved.

 Still maybe "Content Editor" or "MonoGame Content Editor" is better.  Feels sort of boring to me, but maybe more accurate to what role it serves.

**Comment by DDReaper** [comment]
I'd vote for:
**MonoGame Content Editor

It's specific for MonoGame and describes what it actually does

**Comment by DDReaper** [comment]
On that thread then, would we refer to MGCB as:

**MonoGame Content Builder**

??

**Comment by theZMan** [comment]
Content editor seems to imply editing the actual content e.g. the images and models..

Content Pipeline editor doesn't make sense at all.

Content Project editor seems better to me - I know we don't have content projects any more but this is what replaces them and it does tie everything together just iike content projects did.

**Comment by tomspilman** [comment]
> I'd vote for: MonoGame Content Editor

 I begrudgingly vote for it and hope for a better idea to come along.


> MonoGame Content Builder

 Well IMO we already do...  MGCB is just shorthand for "MonoGame Content Builder".  I used MGCB because typing "MonoGameContentBuilder.exe" into a command line seemed unnecessarily explicit.  Like you don't have "MicrosoftBuild.exe" you have "Msbuild.exe".

 That said...  I don't think we want to get into calling the editor "MBCE".  That is just going to lead to confusion IMO.

**Comment by tomspilman** [comment]
> Content editor seems to imply editing the actual content e.g. the images and models..

 Well...  you do sort of edit the content.  Not images or models directly, but you do edit how the are processed.  Like I can change the model scale, the quality of a sound effect, etc.  So it sort of does editing of content.

> Content Project editor seems better to me 

"MonoGame Content Project Editor" is starting to feel too long, but yeah I get your point.

**Comment by DDReaper** [comment]
**The Super Awesome Mono Game Content Building Solution for Games**

I'd personally try to avoid the words "Content Project" simply because of the XNA roots of MonoGame (just a preference), would get caught up in issues and confuse users at this stage (the new content project or the old content project stuff)

Maybe time to change track and call it the Asset Pipeline?

So:
* MonoGame Asset Project Editor
* MonoGame Asset Builder

(Although I've always hated the word ASS in anything)

**Comment by theZMan** [comment]
Since nobody agrees @tomspilman should make an executive decision otherwise this one will go round and round for years..

**Comment by DDReaper** [comment]
I agree completely @theZMan (isn't that always the case? :D)

**Comment by tomspilman** [comment]
I would like to get some more opinions in here first...  but yeah we don't want to keep this open forever.

**Comment by mgarstenauer** [comment]
I would call the EXEs: MGCB.exe and MGCB-GUI.exe.
"MonoGame Content Builder"  and "MonoGame Content Builder Frontend/GUI"?
This would better communicate their relationship.

(Just brainstorming... Many GNU/Linux tools are often similarly separated in command-line tool and frontend. Do they have a naming scheme?)

**Comment by tomspilman** [comment]
> I would call the EXEs: MGCB.exe and MGCB-GUI.exe.

Not really worried about the EXE names at all really...  they can be whatever.


> "MonoGame Content Builder Frontend/GUI"?

Not really a fan of naming something "Frontend" or "GUI".

**Comment by danzel** [comment]
Call the GUI the "Content Manager"

**Comment by DDReaper** [comment]
"Content Manager" seems fair name for the GUI tool

**Comment by tomspilman** [comment]
>  "Content Manager"

I don't see how "Content Manager" is good and "Pipeline" is bad.

It seems like if "Pipeline" is bad because it is confused with the conceptual idea of the content pipeline, then "Content Manager" is bad because it is confused with the ContentManager class.

Makes me wonder... why is "Pipeline" is actually a bad name?

**Comment by KonajuGames** [comment]
I'd be happy with "MonoGame Content Manager" for the GUI tool.  It's not too long and doesn't imply editing the content itself.  It manages the content.  It would require the "MonoGame" remain in in the title to help differentiate from the `ContentManager` class.

> (Although I've always hated the word ASS in anything)

Assimp ranks among one of the more ridiculous names for an open source project. :)

**Comment by theZMan** [comment]
For me pipeline is the process that content goes through when you run the build tool. Plus pipeline is one of those specialized doman words - most game developers don't know the relevance of the word. A bit like how some developers insist on calling sprite sheets texture atlases... yeah dud you are technically correct but most folk have no clue what you mean.

Manager is better because the tool is managing the content for your project. Managing happens at project time and at runtime so it fits in both places. Its not confusing to me but I might not be the right audience.

**Comment by mgarstenauer** [comment]
> Makes me wonder... why is "Pipeline" is actually a bad name?

When I hear "pipeline" in the context of games, I think of the "rendering pipeline". Before XNA came along, I never associated "pipeline" with content processing. I believe new developers without an XNA background, might be confused at first.

I agree, "Content Manager" is good choice.
