### ISSUE TITLE
[WP8] Software buttons are not handled by MonoGame

### ISSUE THREAD

**Issue by Nezz** [MonoGame/MonoGame#3457]
Ouch.

![wp_ss_20150120_0002](https://cloud.githubusercontent.com/assets/431167/5866821/53581512-a295-11e4-9b5b-98bb137da914.jpg)

**Comment by Nezz** [comment]
Does anyone know how we could detect this?

**Comment by totallyeviljake** [comment]
I don't see this on any of our games that run on WP8, but we are using the XAML template. Are you seeing this with the swap chain template?

**Comment by Nezz** [comment]
XAML with DrawingSurfaceBackgroundGrid.

**Comment by totallyeviljake** [comment]
That's particularly weird then since we have the same templates - xaml with drawing surface:

https://github.com/Cocos2DXNA/cocos2d-xna/blob/master/TestWin8Phone/GamePage.xaml

That's the template we use in all of our WP8 games, including our landscape games (Santa Shooter). maybe this is from a recent change to MonoGame for the WP8.1 template support?

**Comment by Nezz** [comment]
This is a pretty old bug - we just did not have the hardware to test it.

You have DrawingSurface in your template, not DrawingSurfaceBackgroundGrid :)

**Comment by KakCAT** [comment]
Hi,

sorry for pushing but I'm getting an increasing amount of complaints about this issue. Is there any fix available or any example which handles all the cases?

The bug is also present in Windows 10, and as soon as microsoft starts rolling new devices (which supposedly encourage virtual buttons to get more hardware developers jump into the windows 10 bandwagon) there will be lots more.

**Comment by Nezz** [comment]
If you are using DrawingSurfaceBackgroundGrid, you have to handle it in your own engine.
If you are using DrawingSurface, you get a surface with the right size.

**Comment by KakCAT** [comment]
Hi Nezz,

last time I checked this was valid as long as the controls were always present on the screen. 

However the user can choose to make them invisible and bring them while playing. For some reason, once done it seems you can't hide them back, but they keep obscuring a part of the game.

Do you know if this has been fixed or it's just that DrawingSurface must also be handled internally?

Thanks!

**Comment by Nezz** [comment]
We are using DrawingSurfaceBackgroundGrid, so I don't know how DrawingSurface can handle that situation.

**Comment by KakCAT** [comment]
I think this problem has been fixed in Windows 10 mobile since the last time I tested (probably fixed on microsoft's side). Sizes seem to be reported correctly now.
