### ISSUE TITLE
Unable to build content - Cannot load FreeImage

### ISSUE THREAD

**Issue by danzel** [MonoGame/MonoGame#3556]
```
C:/BuildAgent/work/e640bfb9e46917d7/SimpullsContent/Debug/../clouds.png: error:
Importer 'TextureImporter' had unexpected failure!
System.DllNotFoundException: Unable to load DLL 'FreeImage': The specified modul
e could not be found. (Exception from HRESULT: 0x8007007E)
   at FreeImageAPI.FreeImage.GetFileType(String filename, Int32 size)
   at FreeImageAPI.FreeImage.LoadEx(String filename, FREE_IMAGE_LOAD_FLAGS flags
, FREE_IMAGE_FORMAT& format)
   at FreeImageAPI.FreeImage.LoadEx(String filename)
   at Microsoft.Xna.Framework.Content.Pipeline.TextureImporter.Import(String fil
ename, ContentImporterContext context) in c:\Users\danzel\Code\Simpulls\MonoGame
\MonoGame.Framework.Content.Pipeline\TextureImporter.cs:line 85
   at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.F
ramework.Content.Pipeline.IContentImporter.Import(String filename, ContentImport
erContext context) in c:\Users\danzel\Code\Simpulls\MonoGame\MonoGame.Framework.
Content.Pipeline\ContentImporter.cs:line 45
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent
(PipelineBuildEvent pipelineEvent) in c:\Users\danzel\Code\Simpulls\MonoGame\Mon
oGame.Framework.Content.Pipeline\Builder\PipelineManager.cs:line 575
Build 0 succeeded, 1 failed.

Time elapsed 00:00:00.29.
```

Solution was to install the x64 version of vs 2012 c++ redistributable
http://www.microsoft.com/en-NZ/download/details.aspx?id=30679

We should probably have a nicer error for this if we can, spent ages bashing at this! (Dependency Walker told me what the missing dll was)

**Comment by tomspilman** [comment]
Hum...  the redist we need `vcredist_x64.exe` is only 7MB.  If you download and run it from the command line:
```
vcredist_x64.exe -?
```
It tells you that it has `/quiet` and `/norestart` mode:

![capture](https://cloud.githubusercontent.com/assets/103522/6315523/7322ca94-b9ca-11e4-9eb6-b0ff08bec005.PNG)

We should be able to embed this into the Windows installer fairly easily if we want.

Either that or we just add a note about it on the download site.

**Comment by theZMan** [comment]
Nobody reads websites - installers should include everything that is needed..

**Comment by KonajuGames** [comment]
Include it and use the quiet install mode.​

**Comment by Vutov** [comment]
Thanks mate, I had the same issue, thankfully found this posts.

**Comment by gms9rc** [comment]
I'm having this issue now after upgrading to MonoGame 3.5.  I'm using Visual Studio 2012 and .NET 4.5.  I tried using vcredist_x64.exe and the installer seemed to work, so I'm kind of lost on what to do here.  I verified that FreeImage.dll is in the right folder.

```
Build started 3/20/2016 8:44:44 PM

E:/Documents/Visual Studio 2012/Projects/temp/Game1/Game1/Content/20151010_120240.jpg
E:/Documents/Visual Studio 2012/Projects/temp/Game1/Game1/Content/20151010_120240.jpg: error: Importer 'TextureImporter' had unexpected failure!
System.DllNotFoundException: Unable to load DLL 'FreeImage': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at FreeImageAPI.FreeImage.GetFileType(String filename, Int32 size)
   at FreeImageAPI.FreeImage.LoadEx(String filename, FREE_IMAGE_LOAD_FLAGS flags, FREE_IMAGE_FORMAT& format)
   at Microsoft.Xna.Framework.Content.Pipeline.TextureImporter.Import(String filename, ContentImporterContext context)
   at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)
E:/Documents/Visual Studio 2012/Projects/temp/Game1/Game1/Content/signature.png
E:/Documents/Visual Studio 2012/Projects/temp/Game1/Game1/Content/signature.png: error: Importer 'TextureImporter' had unexpected failure!
System.DllNotFoundException: Unable to load DLL 'FreeImage': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at FreeImageAPI.FreeImage.GetFileType(String filename, Int32 size)
   at FreeImageAPI.FreeImage.LoadEx(String filename, FREE_IMAGE_LOAD_FLAGS flags, FREE_IMAGE_FORMAT& format)
   at Microsoft.Xna.Framework.Content.Pipeline.TextureImporter.Import(String filename, ContentImporterContext context)
   at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)

Build 0 succeeded, 2 failed.

Time elapsed 00:00:00.13.

```

**Comment by ricardosabino** [comment]
I'm having a very similar problem where freetype6.dll can't be found although it's in the same folder of the pipeline tool.

	Building Font C:\WINDOWS\Fonts\arial.ttf
	System.DllNotFoundException: Unable to load DLL 'freetype6.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
	at SharpFont.FT.FT_Init_FreeType(IntPtr& alibrary)
	at SharpFont.Library..ctor()

I've attached the list of redists installed on my machine so I'm not sure if this is a redist issue or something else.

![msvcrs](https://cloud.githubusercontent.com/assets/2054201/14579376/5f376f2c-0374-11e6-9f7a-ad8998404a94.png)

**Comment by Tzenchor** [comment]
I have just compared your redist with mine, and the only difference is that from the 2013 ones I only have the version 12.0.21005, and from the 2012 packages you are missing the x86 11.0.60610, the rest are the same

**Comment by ricardosabino** [comment]
I was able to fix it by repairing my 2012 x64 redist 11.0.61030.0.

**Comment by abyssdoor** [comment]
I'll just say I came here having the same problem, thankfully it was solved by installing the 2013 redistributable, but I think i my case the culprit was a DivX update (as soon as I noticed it was installing some c++ libraries I thought "this will haunt me later, right?")

**Comment by BrainSlugs83** [comment]
So, I ran into this today, and this is super weird, because I was able to build this project in mid-April (2016) on _**this**_ machine -- I haven't uninstalled the VC redists or anything since then, but it all worked at that time -- I'm running the same version of MonoGame that I was then (literally, nothing has changed) -- same version of Visual Studio, everything. -- but today I opened the project, and it won't build with this error.

I installed the VC++ 2013 (x64) Redistributable that @gms9rc linked to; and that fixed it... but ... how come I didn't need this in April, and suddenly I need this now?? O.O

**Comment by abyssdoor** [comment]
based from my own experience you probably installed or updated something in your computer that updated c++ libraries in the background, in my case it was the DivX Updater which messed with them

**Comment by tomspilman** [comment]
Actually the best fix here is to rebuild FreeImage to use the static version of the C runtime libraries.  This way it won't have any dependency on those redistributables.

This is the same issue with MojoShader... see https://github.com/mono/MonoGame/issues/4485.

**Comment by kras-imex-6** [comment]
I have the same error. MonoGame is not working !!! (((

**Comment by yyr57695** [comment]
I ran into this exact issue today when attempting to build images into my content pipeline under a fresh install of Windows 10 Pro, Visual Studio 2017, and the stable release of MonoGame 3.6.0.1625.  It was fixed by installing the 2013 redistributable as linked in [gms9rc's post](https://github.com/MonoGame/MonoGame/issues/3556#issuecomment-199082805) above.

This was accompanied by a similar error when the pipeline got up to building in my SpriteFont:
```
Processor 'FontDescriptionProcessor' had unexpected failure!
System.DllNotFoundException: Unable to load DLL 'freetype6.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
at SharpFont.FT.FT_Init_FreeType(IntPtr& alibrary)
at SharpFont.Library..ctor()
at Microsoft.Xna.Framework.Content.Pipeline.Graphics.SharpFontImporter.Import(FontDescription options, String fontName)
...
```

I was able to fix this issue by installing this: (http://www.microsoft.com/en-NZ/download/details.aspx?id=30679)
as recommended here: (http://community.monogame.net/t/monogame-noob-unable-to-load-freeimage/6255)

It's unfortunate that these components have to be manually fetched...it'd be great if this was easier in the future!  (If a more recent MonoGame build has already fixed this, I apologize for not trying it.)

**Comment by Al3xlab** [comment]
Same issue with **freetype6.dll** and **FreeImage** (using MonoGame 3.7.1 with VS2017).
Installing _C++2012 x64_ solve the problem for freetype, and _C++2013 x64_ for FreeImage.
My config is now: C++2010-2012-2013-2017 (x64).

**Comment by jshial** [comment]
Well.. I pretty much installed them all but VS still complains about FreeImage. 
![image](https://user-images.githubusercontent.com/36725794/93692897-5bc4a180-fb2b-11ea-8d8c-c45f87c9445a.png)

**Comment by raschuh** [comment]
I have a solution for Apple Silicon (arm64) Macs. I googled around and apparently there is no reliable solution for it, so I want to share this. 

Homebrew have FreeImage for Apple Silicon so you can install it via `homebrew install freeimage`.

Then you copy dylibs over to your .NET SDK runtime directory. For example, on my Mac I did this -- `cp /opt/homebrew/Cellar/freeimage/3.18.0/lib/* /usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.12/`.

Voila. It worked. I was able to open the MGCB Editor, load a PNG in, and then build it without any issues. Built and ran the project using arm64 .NET and it worked perfectly. 

This might be the solution that other Apple Silicon users are looking for. Hopefully it work for them as well.

**Comment by wazawoo** [comment]
@raschuh Thanks so much for the context here... Your solution didn't quite work for me. My `dotnet --version` didn't match any of the runtime directories, and even after I tried moving the FreeImage binaries to every single one of those, it still didn't work...

This, however, did work, and I wanted to share in case it helps anyone else:

---

## Original error
`Unable to load shared library 'FreeImage' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libFreeImage, 0x0001): tried: 'libFreeImage' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibFreeImage' (no such file), '/usr/lib/libFreeImage' (no such file, not in dyld cache), 'libFreeImage' (no such file), '/usr/local/lib/libFreeImage' (no such file), '/usr/lib/libFreeImage' (no such file, not in dyld cache)`

## Solution steps
1. Install FreeImage via brew as mentioned above
`brew install freeimage`
2. Find the path it was installed to
`brew info freeimage`
which for me, outputs the following, containing the path I'm looking for: `/opt/homebrew/Cellar/freeimage/3.18.0`
```
==> freeimage: stable 3.18.0 (bottled), HEAD
Library for FreeImage, a dependency-free graphics library
https://sourceforge.net/projects/freeimage/
/opt/homebrew/Cellar/freeimage/3.18.0 (16 files, 29.1MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-10-12 at 22:04:06
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/f/freeimage.rb
License: FreeImage
```
3. Move all files from that folder (for me, `/opt/homebrew/Cellar/freeimage/3.18.0`) to `/usr/local/lib`
You can either do this manually, or via the command:
`cp /opt/homebrew/Cellar/freeimage/3.18.0/lib/* /usr/local/lib/`

You will likely need sudo to run that, so if it yells at you, just add `sudo` before `cp ...`

As for the other paths mentioned in the error, I wasn't able to add files to `/usr/lib`, and I didn't mess with `/System/Volumes/Preboot/Cryptexes`.

Hopefully this helps... Such an incredibly frustrating error to debug. Hopefully in the future Monogame somehow includes it as an actual dependency so nobody has to deal with this.

**Comment by raschuh** [comment]
@wazawoo Mmm, it seems that our SDK was looking at different directories for the FreeImage binaries. Mine looked in their own directory while your SDK looked in `/usr/local/lib`. 

The generic solution might be this: Run the MGCB Editor and let it crash then inspect the error message to find which directory it was looking for the binaries then copy the binaries to that directory. 

Yeah. I think I recall reading a comment from a MonoGame developer mentioning that they will work on including FreeImage into MonoGame. Here's to hoping.

**Comment by AristurtleDev** [comment]
@raschuh indeed correcting this issue for M1/M2 macs is something currently being worked on right now. I'm hoping news of the fix will be soon, but there is a lot that needs to be done to resolve this. It's not just the FreeImage lib, but also all other dependencies that the `mgcb` uses for content building that will need to be updated for the M1/M2 architecture.

In the meantime, here is a video of the MGCB Editor building a texture on an M2 using the .NET 6 SDK (Apple Silicon) and not the Intel x64 one through Rosette to show some progress.

https://github.com/MonoGame/MonoGame/assets/103014489/853b5cd3-ce78-420b-86ad-30e8e06357b2

**Comment by wazawoo** [comment]
@AristurtleDev Awesome! So great to hear. Every time I see your turtle icon, I know monogame is getting better. You've been going hard!

**Comment by raschuh** [comment]
### Update on the Apple Silicon Specific Issue

I was experimenting with [SFML.NET](https://github.com/SFML/SFML.Net) on my M2 MacBook running native (arm64) .NET 7.0 SDK. SFML.NET should work just fine on Apple Silicon Macs as it only needs the native CSFML binaries being available. 

In this case, I had to install CSFML through Homebrew. A test project built just fine but crashed when I tried to run it. Same error. I reread the error message and the .NET runtime was looking for the CSFML binaries but couldn't find them so it crashed. One of the directories it looked in was `/usr/local/lib` and that got me thinking. Instead of copying the binaries to the .NET SDK directory as mentioned earlier in another comment, I made symlinks of the CSFML binaries in `/opt/homebrew/lib` to `/usr/local/lib`. It worked. 

The command I used: `sudo ln -s /opt/homebrew/lib/* /usr/local/lib`

It appeared that .NET runtime can't find the Hombrew installed libraries, so I googled around to find a proper and permanent solution and I came across [this](https://github.com/Homebrew/brew/issues/13481). Maybe I'm wrong but for this situation MonoGame wasn't the only one. Not only that some dependencies doesn't have Apple arm64 binaries available yet, but the .NET can't find them on the system wide library path. I had to manually link them so the .NET can see them.

Thoughts? This is a better solution than before so I wanted to update.

**Comment by mrhelmut** [comment]
Closing this because the discussion side tracked into a different issues that has [duplicates](https://github.com/MonoGame/MonoGame/labels/Setup).
