### ISSUE TITLE
effect parameter setvalue bug ?

### ISSUE THREAD

**Issue by KakCAT** [MonoGame/MonoGame#3578]
Hi!

this line in monogame gives an InvalidCastException:

effect.Parameters["SpecularPower"].SetValue (50);

(SpecularPower being a float) while it works on XNA. Changing the 50 to 50.0f makes the code work on both.

**Comment by Jjagg** [comment]
It looks like this issue is still in. The [`SetValue(int)`](https://github.com/MonoGame/MonoGame/blob/ba5c722a399fa4e192859a7dd17377b20ae4d327/MonoGame.Framework/Graphics/Effect/EffectParameter.cs#L433) method checks that the parameter type is `int`, without taking into account that it can be implicitly cast to `float`.

**Comment by ripwin** [comment]
Old but I think we can close this issue.

I created a file myEffect.fx with :

`float SpecularPower;`

I used mgfxc :

![image](https://github.com/MonoGame/MonoGame/assets/10164365/fb3c6f17-6dcb-43cf-aa43-2ed7238175fd)

And I used the following code :

![image](https://github.com/MonoGame/MonoGame/assets/10164365/61fff206-b6e0-42b1-8e1e-83ad6b74b882)

And I add 0 issue.

I also looked at the code :

![image](https://github.com/MonoGame/MonoGame/assets/10164365/f28cc385-3606-4586-952c-54abdf18cc3b)

Everything seems ok to me.

**Comment by bjornenalfa** [comment]
Yes, it was fixed in this commit https://github.com/MonoGame/MonoGame/commit/2db51bca39037ad33ef6fbc6ac9a9dcc3d4bb6f4
