### ISSUE TITLE
What is the state of SIMD support?

### ISSUE THREAD

**Issue by dsaf** [MonoGame/MonoGame#3781]
Stable version of the system package is available for BCL:

http://www.nuget.org/packages/System.Numerics.Vectors

MonoGame has expressed a keen interest in past:

https://twitter.com/monogameteam/status/301370937679421440
https://monogame.codeplex.com/discussions/248825

But unless I am mistaken the low-performance Vector2 is still being used:

https://github.com/mono/MonoGame/blob/2d43afcc304bbcc53d45c2f31471192c8b1daa32/MonoGame.Framework/Vector2.cs

On the other hand XNA used some sort of magic to make Vector2 "SIMD-ready":

http://blogs.msdn.com/b/abhinaba/archive/2011/04/10/simd-support-in-netcf.aspx

**Comment by KonajuGames** [comment]
SIMD support in .NET is unfortunately still not something you can just turn on and get immediate benefits.  Here is just a few things that need to be sorted out first.

* System.Numerics.Vectors is on some platforms and Mono.Simd is on some of the same platforms and others, and some platforms may have neither.
* The types and type members are different between the two, meaning three implementations of all math types in MonoGame (using System.Numerics.Vectors, Mono.Simd and neither).
* Mono is still slower than Microsoft .NET on platforms where both are available.  Thus to use the performance benefits of Mono.Simd on Windows platforms we would have to switch to Mono on those platforms.
* The `ForceInine` and `UnsafeCode` attributes are Mono only (as far as I know), and I don't know if they are supported across all platforms that use Mono.  It looks like Microsoft code uses `[MethodImpl(MethodImplOptions.AggressiveInlining)]` which is hint to the JIT rather than a requirement, and would again require different implementations for different compilers.
* System.Numerics.Vectors is now in GitHub, and perhaps Mono will adopt it in place of Mono.Simd?  This would help a bit, but they would also have to support the `JitIntrinsic` attribute that it relies on to get the boost.
* The "magic" to make XNA's Vector types "SIMD-ready" was simply an early version of System.Numerics.Vectors and a special JIT engine similar to RyuJIT that generated SIMD code for specially-marked methods.  This was on Windows Phone 7.5 only if I remember correctly.
* What happened in the latest update to System.Numerics.Vectors in Nuget?  Where is the release notes or any description of what changed?  I've found at least [one case](http://newscentral.exsees.com/item/6175cb3bf48824ea443d015d8dbaa381-dc64a32c5b37e9157b92c94a54e69b59) where it no longer generates SIMD for at least one developer.  I'm not saying it's all bad, but something changed and maybe it's done a different way now?

I would be happy to be corrected on any of these issues.  At the moment, SIMD support in .NET generally still appears to be in a bit of flux.

**Comment by dsaf** [comment]
@KonajuGames Thank you, that is a very detailed feedback.

By the way there is another contender to consider:

http://www.yeppp.info/index.html
http://www.nuget.org/packages/Yeppp.CLR.Bundle

> Yeppp! is a high-performance SIMD-optimized mathematical library for x86, ARM, and MIPS processors on Windows, Android, Mac OS X, and GNU/Linux systems.

> Yeppp! officially supports the C, C++, C#, Java, and FORTRAN programming languages.

This would mean a third-party dependency unfortunately.

**Comment by Inverness** [comment]
Has the status on this changed at all?

**Comment by Inverness** [comment]
System.Numerics.Vectors is a corefx library, so could it not be included with MonoGame on whatever platform it is deployed on? Then SIMD support would either happen or not at runtime?

**Comment by theZMan** [comment]
@tomspilman and I had this conversation almost exactly a year ago - certainly seems like a good time to revisit it if that library is supported on all the CoreFX platforms. Of course mobile is going to be a challenge still but the code should be able to fall back to a less efficient way.

-------------------------------------
The System.Numerics.Vectors namespace, which is now part of CoreCLR and fully open source:  https://github.com/dotnet/corefx/tree/master/src/System.Numerics.Vectors
 
This provides:
·         Vector/matrix types based on the XNA API  (100% identical for common use, but removed a few methods that turned out not to make a lot of sense and added a few other things that experience showed to be useful)

·         SIMD optimized on recent Windows CLR versions

·         Comprehensive set of unit tests

·         Common currency across not only CoreCLR but also multiple Windows 10 / WinRT APIs

---------------
Wow... that is very cool.  The second we can support CoreFx on Windows and Xamarin platforms we should totally be happy to drop our own types.

 Will be disturbing to some as some namespaces and some methods will probably change.  But eventually it is better than supporting our own if they are better maintained.
------------------

What do you mean about supporting those types? If we have the source they will just run on Xamarin and clearly they will work on windows already.

--------------
 I assume we have to build against the CoreFx and not the standard mscorlib/System/System.XML/etc and that will take some time before it is supported everywhere?

**Comment by tomspilman** [comment]
The biggest omission in `System.Numerics.Vectors` is they decided against using `ref` for large types like `Matrix4x4`.  That makes me a bit hesitant to all of it at this time without clear tests on all our major platforms that `ref` methods are not critical to performance.

Also for these to work with hardware acceleration the JIT or AOT for a platform has to include support for them explicitly.  Without that... it is no better and possibly worse than the XNA types.

Finally MonoGame doesn't need to change at all for people to start using these today.  MonoGame itself does few internal vector/matrix operations... most of the vector/matrix math comes from game code.  If you use `System.Numerics.Vectors` in your game code then copy the results to an XNA type for setting `Effect` parameters...  you should get most of the benefit without any changes to MonoGame.

**Comment by tomspilman** [comment]
Note there is a discussion of the `ref/out` issue for `System.Numerics` in https://github.com/dotnet/corefx/issues/157.

The consensus from the MS side is that they want to fix the issue in the JIT.  Why use `ref/out` tricks in this particullar API to optimize away big structure copies when they could fix the JIT to optimize them away in all cases.

The consensus from everyone else is that we have to support older JITs and AOTs...  if it is slow on Mono platforms then it won't get adopted.

If you have interest in this getting resolve I suggest commenting on it.

**Comment by tomspilman** [comment]
Sweet... MS is going to implement the `ref` methods:

https://github.com/dotnet/corefx/issues/157#issuecomment-231807676

**Comment by QuantumDeveloper** [comment]
@tomspilman But as I understood, there still will be no SIMD support for matrices and quaternions?

**Comment by Jjagg** [comment]
Closing for #7204.
