### ISSUE TITLE
AudioSessionException on iOS 8.4

### ISSUE THREAD

**Issue by ebatiano** [MonoGame/MonoGame#4119]
When returning from background, sometimes AudioToolbox throws an exception. Here's stack trace (sorry for lack of lines and file names - data is from BugSense):

```
Exeption: AudioSessionException (Unknown error code: 561015905)
Function: AudioToolbox.AudioSession.SetActive

at AudioToolbox.AudioSession.SetActive (Boolean active) [0x00000] in <filename unknown>:0 
at Microsoft.Xna.Framework.Audio.OpenALSoundController.<OpenSoundController>m__1 (System.Object sender, System.EventArgs e) [0x00000] in <filename unknown>:0 
at AudioToolbox.AudioSession.Interruption (IntPtr userData, UInt32 state) [0x00000] in <filename unknown>:0 
at (wrapper native-to-managed) AudioToolbox.AudioSession:Interruption (intptr,uint) 
```

**Comment by Eversor** [comment]
Seems fixed on ios9, i have no crashes on that platform for 5 days.

**Comment by vchelaru** [comment]
While this is fixed in iOS 9, it still occurs in iOS 7 and 8, which has a large install base for a while. Any info on why this might be happening?

**Comment by vchelaru** [comment]
I've found somewhat of a workaround. The Crash occurs in the AudioSession.SetActive(true) call, as indicated by the previous post. 

I played around with it a bit and found out that if I try/catch and consume the exception, the app will continue, but no more audio plays:

                AudioSession.Resumed += (sender, e) => {
                    try
                    {
                        AudioSession.SetActive(true);
                    }
                    catch(Exception exce)
                    {
                 }

Of course that's only a half-solution because it does mean the game is silent until the user relaunches the app. I continued to mess around with it and I found that if I got a crash, I could detect that and delay the re-activation of the Audio Session as follows:

                AudioSession.Resumed += (sender, e) => {
                    try
                    {
                        AudioSession.SetActive(true);
                    }
                    catch(Exception exce)
                    {
                        try
                        {
                            // maybe we can delay it?
                            System.Threading.Thread.Sleep(1000);
                            AudioSession.SetActive(true);
                        }
                        catch(Exception exce2)
                        {
                            System.Console.WriteLine(exce2.ToString());
                        }
                    }
                    Alc.MakeContextCurrent(_context);
                    Alc.ProcessContext(_context);
                };

Sure enough that solved it, but it does add a delay to the resuming of the app. In my opinion it's a valid workaround because I think a 1 second delay (which maybe could be reduced) is better than a crash which cannot be caught in the game code.

If the powers that be consider this a valid fix to the problem, then I can check it in. To be clear, this issue is only an issue on iOS 7 and 8, so iOS 9 devices should never be impacted by this restart delay, and as they are phased out, this issue will also go away.

Shall I PR it?

**Comment by mrhelmut** [comment]
Have you tried to monitor the ```AudioSession```'s properties with a ```PropertyListiner``` to see if something specific may happen and could cause this issue?
```AudioSession``` seems to have been deprecated since iOS 7, so maybe relying on the suggested ```AVAudioSession``` may be more reliable (and maybe some events may help knowing when the session can be re-activated).
Active waiting should be avoided, when possible.

**Comment by tomspilman** [comment]
This should be fixed now between https://github.com/MonoGame/MonoGame/pull/4180 and https://github.com/MonoGame/MonoGame/pull/6433.
