### ISSUE TITLE
Concensus? Should we drop the WindowsPhone8 project?

### ISSUE THREAD

**Issue by DDReaper** [MonoGame/MonoGame#4340]
Supporting the old WindowsPhone8 project is such a pain with it's reliance on the old XNA libraries (as I'm reminded yet again when doing a global update)

As MS don't readily support the building of these now in favour of 8.1 projects only or Win 10, should we drop this platform for the next release?

I think the same has also been said about dropping Win8 in favour of updating that platform to Win8.1 (since we are forced to re-target on new projects now)

**Comment by KakCAT** [comment]
I'm still using WP8 because I never moved to WP8.1  (I think it's been always broken and gives tons of problems compared to WP8), and I still have lots of users (actually most) on WP8. 

However WP8 version, as it is now, imho is mature and needs no updates, so I see no reason why I couldn't keep using today's version during the next years.

**Comment by nkast** [comment]
Same here. Never moved to WP8.1 and I don't think anyone did because of the bugs and not much attention was given to iron out since Win10 was anounced. On the other hand WP8.0 is very stable I  still have projects on WP8.0. Actually I still wait for an important fix for it (#3725) and I hope to make it in 3.5.
In my opinion it's very soon to drop WP8, the update to win10 mobile is not even released yet. 
Maybe next year/release would be the time to do so.

**Comment by Danthekilla** [comment]
Yes I think we should drop it. Very few phones are running windows phone 8 anymore. And it is a relative pain to support. I also agree with dropping windows 8.0 support for similar reasons, and the fact that we are forced to re-target on new projects now.

Anyone who is still working on windows 8.0 or phone 8.0 projects should have no issues using the current version for the future.

**Comment by tomspilman** [comment]
I agree with @nkast suggests is a good idea.  We should wait for Win10 for phone to actually ship which should be early next year.
