### ISSUE TITLE
Refactor GraphicsDevice.PresentationParameters

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4433]
Doing some experimenting against XNA for #4425 I found that our implementation of `GraphicsDevice.PresentationParameters` is wrong.

`GraphicsDevice.PresentationParameters` is only the output presentation values representing the state of the `GraphicsDevice` the last time the presentation was changed.

This means `GraphicsDeviceManager` shouldn't be making changes to it directly.  Instead `GraphicsDeviceManager` should be creating a new `PresentationParameters` object... populating it with the new state... then passing that to `GraphicsDeviceManager` to become the new presentation state.

Some code that currently fails under MonoGame:

```
var oldpp = GraphicsDevice.PresentationParameters;
GraphicsDeviceManager.PreferredBackBufferWidth = 100;
GraphicsDeviceManager.ApplyChanges();
var newpp = GraphicsDevice.PresentationParameters; 
Debug.Assert(!object.ReferenceEquals(oldpp, newpp));
```

**Comment by Tzenchor** [comment]
Having a look at this i have found some problems:
* `GraphicsDevice.PresentationParameters` is readonly as per xna documentation
* `GraphicsDevice` has no function that receives a `PresentationParameters` parameter as per XNA documentation except the constructors or `reset`, and currently `reset` is restricted to Windows and Directx.
That leaves two possible solutions:
* recreating the `GraphicsDevice` inside `GraphicsDeviceManager.ApplyChanges`, but this provokes that the `GraphicsDevice` is initialized twice except for MonoMac
* The second option relies on #4429, implementing the reset methods for every platform

I believe that the correct option is the second one, but i can't test if the `GraphicsDevice` is recreated or not in XNA.

**Comment by tomspilman** [comment]
> That leaves two possible solutions:

I don't think either of those is the right solution.

The docs on `GraphicsDevice.Reset()` all suggest that a full reset of the device is done.  This causes you to have to recreate textures and other resources.  Clearly this isn't what one would expect if you were just resizing the back buffer for instance.

So `GraphicsDevice.Reset()` isn't a solution here.

I suspect XNA uses some internal API... not in the docs or publicly visible...  to update the `GraphicsDevice`.  We should do the same.

My initial idea here is that once #4425 is merged then we can alter the new `GraphicsDevice.OnPresentationChanged()` call to take a new `PresentationParameters` object which will replace the existing one.

**Comment by Tzenchor** [comment]
The `GraphicsDeviceManager.PreparingDeviceSettings` [XNA documentation](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphicsdevicemanager.preparingdevicesettings.aspx) is giving me feeling that the `GraphicsDevice` is being recreated
Can you test with the example code you gived if the `GraphicsDevice` is still the same or not in XNA?

**Comment by tomspilman** [comment]
Someone will have to setup some unit tests to run on XNA to prove all that actually happens and re-create that for MonoGame.  I just don't have the time to do the investigation myself.

**Comment by flibitijibibo** [comment]
I sat down with something similar to this and found at least one detail: The reason a new PresentationParameters instance is being made on ApplyChanges is likely because device resets/recreations have a PreparingDeviceSettings call before it. So the result might look something like this:

https://github.com/FNA-XNA/FNA/blob/master/src/GraphicsDeviceManager.cs#L222

The only thing I didn't check is it this throws out the GDM preferences or if the GDM properties get priority, but my guess is this is done both for resets and possible D3D device recreations (caused by adapter changes maybe?).

Hope this helps!

**Comment by flibitijibibo** [comment]
One more update: I can now definitely confirm that the above mess is what XNA is doing. It turns out Cthulhu Saves the World is a game that depends on this PreparingDeviceSettings event to apply any settings at all (despite using GDM... yeah, I dunno either), and it actually has the power to override the GDM's own preferences. So I was just barely off:

https://github.com/FNA-XNA/FNA/commit/bf6f5381e8f1edd9cde3cc0dfa304159e7d5fb4b

But yeah, hopefully this clarifies some of the notes above.

**Comment by tomspilman** [comment]
> I can now definitely confirm that the above mess is what XNA is doing

That is what I figured.  A few unit tests should allow us to verify and make the correct fixes.

**Comment by Tzenchor** [comment]
I little update, i have made some tests on XNA changing one property of the `GraphicsDeviceManager` each time before calling `GraphicsDeviceManager.ApplyChanges`, and always the `PresentationParameters` is different from the one retrieved before the call. The `GraphicsDevice` is only recreated after changing `GraphicsProfile`
