### ISSUE TITLE
MacGameNSWindow throwing exception at startup

### ISSUE THREAD

**Issue by tanis2000** [MonoGame/MonoGame#4451]
I've just updated to the latest git version of MonoGame at the time I'm writing this. 

I created a new MonoGame (MonoMac) project and run it and it throws the following error:

```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at ObjCRuntime.Class.Register (System.Type type) [0x00001] in <filename unknown>:0 
  at ObjCRuntime.Class.GetHandle (System.Type type) [0x00001] in <filename unknown>:0 
  at Foundation.NSObject.AllocIfNeeded () [0x0001e] in <filename unknown>:0 
  at Foundation.NSObject..ctor (Foundation.NSObjectFlag x) [0x00007] in <filename unknown>:0 
  at AppKit.NSResponder..ctor (Foundation.NSObjectFlag t) [0x00000] in <filename unknown>:0 
  at AppKit.NSWindow..ctor (CGRect contentRect, NSWindowStyle aStyle, NSBackingStore bufferingType, Boolean deferCreation) [0x00000] in <filename unknown>:0 
  at Microsoft.Xna.Framework.MacGameNSWindow..ctor (CGRect rect, NSWindowStyle style, NSBackingStore backing, Boolean defer) [0x00000] in /Users/tanis/Documents/MonoGame/MonoGame.Framework/MacOS/MacGameNSWindow.cs:64 
  at Microsoft.Xna.Framework.MacGamePlatform.InitializeMainWindow () [0x0002f] in /Users/tanis/Documents/MonoGame/MonoGame.Framework/MacOS/MacGamePlatform.cs:133 
  at Microsoft.Xna.Framework.MacGamePlatform..ctor (Microsoft.Xna.Framework.Game game) [0x00038] in /Users/tanis/Documents/MonoGame/MonoGame.Framework/MacOS/MacGamePlatform.cs:117 
  at Microsoft.Xna.Framework.GamePlatform.PlatformCreate (Microsoft.Xna.Framework.Game game) [0x00002] in /Users/tanis/Documents/MonoGame/MonoGame.Framework/GamePlatform.Desktop.cs:18 
  at Microsoft.Xna.Framework.Game..ctor () [0x0020d] in /Users/tanis/Documents/MonoGame/MonoGame.Framework/Game.cs:68 
  at StencilBuffer.MacOS.Game1..ctor () [0x00000] in /Users/tanis/Documents/MonoGame/Test/Interactive/MacOS/StencilBuffer.MacOS/Game1.cs:19 
  at StencilBuffer.MacOS.AppDelegate.FinishedLaunching (MonoMac.Foundation.NSObject notification) [0x00028] in /Users/tanis/Documents/MonoGame/Test/Interactive/MacOS/StencilBuffer.MacOS/Main.cs:39 
  at (wrapper dynamic-method) System.Object:[StencilBuffer.MacOS.AppDelegate:Void FinishedLaunching(MonoMac.Foundation.NSObject)] (MonoMac.Foundation.NSObject,MonoMac.ObjCRuntime.Selector,MonoMac.Foundation.NSObject)
  at (wrapper native-to-managed) System.Object:[StencilBuffer.MacOS.AppDelegate:Void FinishedLaunching(MonoMac.Foundation.NSObject)] (MonoMac.Foundation.NSObject,MonoMac.ObjCRuntime.Selector,MonoMac.Foundation.NSObject)
  at (wrapper managed-to-native) MonoMac.AppKit.NSApplication:NSApplicationMain (int,string[])
  at MonoMac.AppKit.NSApplication.Main (System.String[] args) [0x0003d] in <filename unknown>:0 
  at StencilBuffer.MacOS.Program.Main (System.String[] args) [0x0001d] in /Users/tanis/Documents/MonoGame/Test/Interactive/MacOS/StencilBuffer.MacOS/Main.cs:22 
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at ObjCRuntime.Class.Register (System.Type type) [0x00001] in <filename unknown>:0 
  at ObjCRuntime.Class.GetHandle (System.Type type) [0x00001] in <filename unknown>:0 
  at Foundation.NSObject.AllocIfNeeded () [0x0001e] in <filename unknown>:0 
  at Foundation.NSObject..ctor (Foundation.NSObjectFlag x) [0x00007] in <filename unknown>:0 
  at AppKit.NSResponder..ctor (Foundation.NSObjectFlag t) [0x00000] in <filename unknown>:0 
  at AppKit.NSWindow..ctor (CGRect contentRect, NSWindowStyle aStyle, NSBackingStore bufferingType, Boolean deferCreation) [0x00000] in <filename unknown>:0 
  at Microsoft.Xna.Framework.MacGameNSWindow..ctor (CGRect rect, NSWindowStyle style, NSBackingStore backing, Boolean defer) [0x00000] in /Users/tanis/Documents/MonoGame/MonoGame.Framework/MacOS/MacGameNSWindow.cs:64 
  at Microsoft.Xna.Framework.MacGamePlatform.InitializeMainWindow () [0x0002f] in /Users/tanis/Documents/MonoGame/MonoGame.Framework/MacOS/MacGamePlatform.cs:133 
  at Microsoft.Xna.Framework.MacGamePlatform..ctor (Microsoft.Xna.Framework.Game game) [0x00038] in /Users/tanis/Documents/MonoGame/MonoGame.Framework/MacOS/MacGamePlatform.cs:117 
  at Microsoft.Xna.Framework.GamePlatform.PlatformCreate (Microsoft.Xna.Framework.Game game) [0x00002] in /Users/tanis/Documents/MonoGame/MonoGame.Framework/GamePlatform.Desktop.cs:18 
  at Microsoft.Xna.Framework.Game..ctor () [0x0020d] in /Users/tanis/Documents/MonoGame/MonoGame.Framework/Game.cs:68 
  at StencilBuffer.MacOS.Game1..ctor () [0x00000] in /Users/tanis/Documents/MonoGame/Test/Interactive/MacOS/StencilBuffer.MacOS/Game1.cs:19 
  at StencilBuffer.MacOS.AppDelegate.FinishedLaunching (MonoMac.Foundation.NSObject notification) [0x00028] in /Users/tanis/Documents/MonoGame/Test/Interactive/MacOS/StencilBuffer.MacOS/Main.cs:39 
  at (wrapper dynamic-method) System.Object:[StencilBuffer.MacOS.AppDelegate:Void FinishedLaunching(MonoMac.Foundation.NSObject)] (MonoMac.Foundation.NSObject,MonoMac.ObjCRuntime.Selector,MonoMac.Foundation.NSObject)
  at (wrapper native-to-managed) System.Object:[StencilBuffer.MacOS.AppDelegate:Void FinishedLaunching(MonoMac.Foundation.NSObject)] (MonoMac.Foundation.NSObject,MonoMac.ObjCRuntime.Selector,MonoMac.Foundation.NSObject)
  at (wrapper managed-to-native) MonoMac.AppKit.NSApplication:NSApplicationMain (int,string[])
  at MonoMac.AppKit.NSApplication.Main (System.String[] args) [0x0003d] in <filename unknown>:0 
  at StencilBuffer.MacOS.Program.Main (System.String[] args) [0x0001d] in /Users/tanis/Documents/MonoGame/Test/Interactive/MacOS/StencilBuffer.MacOS/Main.cs:22 
```

Is there anything obvious that I could be missing?

Thanks!

**Comment by tanis2000** [comment]
Might it be that PLATFORM_MACOS_LEGACY is no longer defined? Is there a way to tell ProtoBuild to create the projects using the old MonoMac instead of XamarinMac?

**Comment by tomspilman** [comment]
@hach-que ?

**Comment by hach-que** [comment]
If you have Xamarin Mac installed, it will use Xamarin Mac. If the project is using MonoGame from source, the user has Xamarin Mac, the project references MonoMac then I suppose you could run into problems (I'd expect compilation errors though, not runtime errors). 

The solution is to use Xamarin Mac for the project, or use the pre-built MonoGame binaries for Mac.

**Comment by hach-que** [comment]
(or not have Xamarin Mac installed)

**Comment by tanis2000** [comment]
@hach-que I do have Xamarin.Mac installed, so it's correctly using that. Nonetheless it crashes inside the Xamarin stuff apparently.
Any clue about what else could be wrong?

**Comment by tanis2000** [comment]
I will try to recreate the project as Camarin.Mac from scratch first. I'll keep you posted.

**Comment by hach-que** [comment]
It's quite possible that it's a Xamarin.Mac bug; it's not exactly the most stable software.

**Comment by tanis2000** [comment]
@hach-que I created a Xamarin.Mac project, it compiles, but I cannot run it:

```
Error MM9030: Building Xamarin.Mac Classic projects requires Indie edition or higher. (MM9030) (StencilTest.MacOS)
```

Now that's a real problem. I saw that there's a form on Xamarin's site for Open Source contributors, but since I have not yet contributed back to MG I don't know if I could qualify. 
Any idea?

**Comment by hach-que** [comment]
Ah yeah, Xamarin.Mac requires a commercial license.  You'll need to buy one from https://store.xamarin.com/ or have a sufficently used open source software that's cross-platform to qualify for an open source license.

Until CoreCLR stabilises on Mac, and we can replace MonoMac with a suitable UI replacement, we're stuck with requiring a Xamarin.Mac license (or using MonoMac and not having 64-bit applications or support for the Mac App Store).

**Comment by tanis2000** [comment]
@hach-que now that's a real show-stopper. I wanted to have a look and fix the stencil buffer stuff on Mac but I'm stuck. I won't buy a Xamarin Mac license just for fixing a bug. 

Is there a way to disable Xamarin Mac or tell Protobuild to ignore it? It looks like I cannot uninstall it without uninstalling the whole Xamarin Studio which is not really useful :)

All that I could find is how to disable the add-in but I guess that's just not enough. 

I have high hopes for CoreCLR to be honest.

**Comment by hach-que** [comment]
One option (if you never intend to use Xamarin.Mac) is to remove the files
at the following locations:

-
/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/mono/XamMac.dll
-
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac/Xamarin.Mac.CSharp.targets

Alternatively you can try forcing it by adding `<Property
Name="ForceMacAPI" Value="MonoMac" />` to all of the projects in MonoGame
and downloading the very latest Protobuild to replace the one MonoGame has.

I'm guessing it's very likely that MonoMac and XamMac will be dropped
entirely in Xamarin Studio 6, because those two APIs depend on mdtool to
build, and Xamarin Studio 6 is entirely based on Roslyn/xbuild from what I
know.

**Comment by tanis2000** [comment]
I tried going the second route. 

I've downloaded and replaced the latest Protobuild.exe available on protobuild.org
I've added that property both to default.build and all of the *.definition files in MonoGame but it still creates Xamarin Mac projects. 

I cannot find a way to print Protobuild's version btw.

**Comment by hach-que** [comment]
Can you paste what the definition file looks like?

There's no way to print the version of Protobuild because the version is managed by the Git hash and the Git commit contains the version of Protobuild.  I suppose I could make Protobuild hash itself and lookup the SHA1 hash online to get the Git commit that contains it...

**Comment by hach-que** [comment]
@tomspilman I think we seriously need to start considering CoreCLR (even while it's not production-ready) if this is how much pain the MonoMac/XamMac/Xamarin.Mac nonsense is causing users.

**Comment by KonajuGames** [comment]
How would CoreCLR help with bindings for the OS X APIs? That's the other major part that Xamarin provide.

**Comment by tomspilman** [comment]
> I think we seriously need to start considering CoreCLR 

We should rope in @dellis1972 into that conversation.  I have no idea what mess we will get ourselves into to take that path right now.  

> how much pain the MonoMac/XamMac/Xamarin.Mac nonsense is causing users

I agree it is all a mess... however isn't this something simply solved by generating the correct projects?

**Comment by hach-que** [comment]
We *can't* generate the right projects in all circumstances.  If you download Xamarin Studio right now, you will get the Xamarin.Mac APIs because that's what Xamarin Studio installs.  We can't check if Xamarin Studio is licensed (I don't know of any way of doing this), so all we can do is check if the Xamarin Mac APIs are available and use them.

We also can't just always use MonoMac, because it doesn't support 64-bit and it can't be distributed on the Mac app store.  I highly doubt it'll stick around for much longer, since it's pretty much inevitable that Apple will do something (like announce 64-bit only apps) that will force MonoMac to be deprecated (or maybe Xamarin will just stop shipping it).

If we leave it up to the end user and not try to do the auto-detection, then we end up with three platforms, MacOS, MacOSMonoMac and MacOSXamMac which is all still worse than just figuring out a way to make one set of APIs work on Mac OS.  It also means if you get the wrong APIs, nothing works, or worse, things work but you develop against a set of APIs you can't actually distribute for.

In terms of OS X APIs, we actually use a very small component of them as far as I can tell; we use basically enough to get an OpenGL window going and that's it.  We can use P/Invokes (coupled with the "drop OpenTK" work) to get to a point where we just P/Invoke to create the window and then perform all rendering from there, and not require any of the Mac APIs that Xamarin provide.

**Comment by hach-que** [comment]
This is perhaps an up-to-date alternative to MonoMac/XamMac/Xamarin.Mac: http://www.monobjc.net/

It's open source, up-to-date and according to the FAQ it supports 64-bit.  Presumably alongside Kickstart, this is something that could be shipped in an App store bundle as well.

**Comment by hach-que** [comment]
This heavily implies you can create an app bundle: http://www.monobjc.net/assets/screenshots/MonoDevelop_Addins_Bundle.png

**Comment by tanis2000** [comment]
@hach-que I'll post my build files as soon as I get in front of a Mac.

Anyway I agree that migrating to CoreCLR seems the best option. You get MS support which is surely better than any other OSS support you can get (see what happened with OpenTK).

Why aren't you evaluating using SDL as well for desktop windowing/input/filesystem replacing completely the need for the xam mac stuff?

**Comment by hach-que** [comment]
The issue is that Xamarin Mac is not just APIs; it is part of the way applications are built on a Mac.  If you don't have the license, it won't build if you're using the features.

For us to use something like Monoobjc, we'd actually end up changing the applications so that they're console executables instead of "Mac applications" (the latter meaning using the Xamarin Mac build process).

CoreCLR is still not yet production ready, in particular, there's no support for debugging CoreCLR applications in Xamarin Studio (and doesn't give us any UI APIs, so we'd still need to have something like Monoobjc for the UI).

I think the best solution the near-term future is:

 * Still use Mono, but Mac applications are just console executables instead of using the Xamarin build process, and
 * Use Monobjc to provide the windowing and operating system APIs

**Comment by tanis2000** [comment]
While I agree with most of the things you're saying, this is just a short term solution.

If MonoMac 64 bit will never come out, the long term plan should be to migrate from MonoMac to something else.
If Xamarin Mac is the best solution you guys are in a position to negotiate discounted indie licenses for Mac then. And that woul be better than spending time trying yet another different dependency that might disappear from night to day.

Is access to the UI API of Mac really necessary for MG? Isn't that something that could be dropped? Is it needed only for the content pipeline tool?

I think you guys need to take some time and plan this carefully and evaluate finding a deal with Xamarin if that would save everyone time and money in the long run. Keep in mind that the real problem is that you need a pricey license only if you want to fix MG yourself or if you want to contribute to the project.
Game developers can just use the dll you guys provide.

My case is a bit weird because I want to fix stuff and I can't, but I'm not the majority of the user base.

**Comment by dellis1972** [comment]
The Current "DesktopGL" works fine on MacOS (and Linux and Windows). I tend
to use that rather than the actual Mac projects at the moment. The SDL2
port which replaces OpenTK will remove the need to have a mac specific
build (as does the current DesktopGL) but you still can't get access to
those native API's, you need Xamarin.Mac (or monoobjc) for that.

We can currently use MonoKickstarter for non-mac store deployments. because
the end user can swap out the runtime. If you publish anything on a store
that needs a signed package/assemblies and uses mono you need a commercial
licence from Xamarin because the user cannot upgrade the runtime
themselves. That includes anything done using monoobjc, SDL2 or what ever,
if it uses mono and the end your cannot upgrade you need a licence.

CoreCLR will probably run the SDL2 port once that is done, but there are
definitely issues with it at this time so its not really an option yet.

It might be worth investigating monoobjc for the Game Center API's (because
thats probably all we need)

**Comment by hach-que** [comment]
> If MonoMac 64 bit will never come out, the long term plan should be to migrate from MonoMac to something else.

There will never be a 64-bit MonoMac.  This is how Xamarin pushes people towards Xamarin.Mac.

> If Xamarin Mac is the best solution you guys are in a position to negotiate discounted indie licenses for Mac then. And that woul be better than spending time trying yet another different dependency that might disappear from night to day.

We can't.  There have been multiple attempts to get more suitable Xamarin licensing for indie game developers using MonoGame over several years, but nothing has eventuated.  Unfortunately Xamarin does not understand how independent video games are funded, and are instead focused on enterprise businesses where monthly and annual subscriptions are financially viable.

> Is access to the UI API of Mac really necessary for MG? Isn't that something that could be dropped? Is it needed only for the content pipeline tool?

It is something I need to consider in the broader scope of "applications on Mac" which is what I need to consider (I'd like to drop MonoMac/XamMac/Xamarin.Mac for all types of cross-platform applications, not just MonoGame using OpenGL).

**Comment by dellis1972** [comment]
@tanis2000 just use the Linux port on mac. it works and you can fix bugs :)

**Comment by tanis2000** [comment]
@dellis1972 :-? Linux port on Mac? Please explain, I'm definitely interested :)

**Comment by dellis1972** [comment]
The Linux project is the core of the "DesktopGL" platform. It's goal is to have one set of binaries that will work across all desktop platforms. If u use the latest unstable mac install you should be able to create a monogame OpenGL project that should work.

-----Original Message-----

**Comment by tanis2000** [comment]
@dellis1972 I've got the OpenGL project setup through the latest add-in. I don't understand which one of the framework it should use though.

Which one corresponds to the DesktopGL target?

<img width="282" alt="file_to_open" src="https://cloud.githubusercontent.com/assets/287841/12537581/b9bb2260-c2c2-11e5-9498-a2d3396fa757.png">

**Comment by tomspilman** [comment]
@tanis2000 - WindowsGL.

@dellis1972 - That is quite confusing... we really should consider renaming that platform.

**Comment by tomspilman** [comment]
> If we leave it up to the end user and not try to do the auto-detection

I think something like that has to be allowed.  At least for the short term while we have this 3 way mac tools/api issue.

It could be a simple optional command line switch to force creation of projects for one of these mac flavors.  I see this as not much different from letting a user optionally choose to generate VS2012 projects even if they had VS2015 installed.

We can then start looking towards what resolves this in the future.

**Comment by tanis2000** [comment]
Thanks @tomspilman 
WindowsGL is missing the content pipeline stuff, though.

Trying to compile my newly created DesktopGL project gives the following error:

```
Error: /Users/tanis/Documents/tanis2000-MonoGame/Test/Interactive/MacOS/StencilBufferTest.MacOS/StencilBufferTest.MacOS.csproj: /Users/tanis/Documents/tanis2000-MonoGame/Test/Interactive/MacOS/StencilBufferTest.MacOS/StencilBufferTest.MacOS.csproj could not import "$(MSBuildExtensionsPath)\MonoGame\v3.0\MonoGame.Content.Builder.targets" (StencilBufferTest.MacOS)
```

I checked the project that has been created and there are those two lines:
```
  <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />
  <Import Project="$(MSBuildExtensionsPath)\MonoGame\v3.0\MonoGame.Content.Builder.targets" />
```

Any clue at how to fix that?

**Comment by tomspilman** [comment]
> Any clue at how to fix that?

@dellis1972 will have to answer that bit...  I know nothing about the Mac add-in really.

**Comment by tanis2000** [comment]
Thanks anyway @tomspilman :)

May I add that it's extremely hard and annoying to try to jump in the MG ship and lend a hand if you're not working on Windows? You should really keep this in mind if you happen to see that there's a lack of people contributing code to the project. 

I like that MG is in C# as this means that you're using a language that's not going to disappear anytime soon and that is backed by a serious company, compared to many other frameworks sitting on top of more trendy languages. 
On the other hand that whole Xamarin monopoly is frightening considering you need that for iOS, Android and Mac. That's three of the major platforms out there. 

I take it that most of you guys are working on Windows and aren't hitting the cross-platform wall that people like me are trying to get over on a daily basis or are deep into consoles stuff with a whole lot of different problems :)

**Comment by dellis1972** [comment]
Install the mac installer it will put all the .targets files in the right place :) at least it should.

I work on mac 90% of the time these days.

-----Original Message-----

**Comment by tomspilman** [comment]
> May I add that it's extremely hard and annoying to try to jump in the MG ship and lend a hand if you're not working on Windows?

We are aware of that.  Some of it... like what Xamarin chooses to do with its licensing ... is just out of our hands.

But generally the problem is Mac and Linux users just don't contribute as much as Windows users do.  It is a cycle that is maybe impossible to break when around 90% of desktops are running Windows:

 https://www.netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0
 http://store.steampowered.com/hwsurvey
 http://hwstats.unity3d.com/editor/os.html
 http://hwstats.unity3d.com/web/os.html
 http://hwstats.unity3d.com/pc/os.html

Now if someone wants to pay us a few thousand a month to keep Mac and Linux fantastic...  we could make something happen.  But until someone can make it a full time job it will be left to volunteers fixing random issues they need solved.

**Comment by prime31** [comment]
@tomspilan why bother even calling MonoGame cross platform with an attitude like that? If your marketing page claims cross platform with Linux and Mac support then it should be supported and not require users (and users that even want to fix the bugs in MonoGame like @tannis2000 ) to pay "a few thousand a month" to be even functional. There is a reason why most of the games on the marketing website have moved to FNA and I'm starting to see why here. I really want MonoGame to be a kickass, solid, cross platform tool but there is just so much resistance here. Just perusing recent issue discussions like this one and the SDL2 thread it is evident.

**Comment by tomspilman** [comment]
> but there is just so much resistance here

Time and time again myself and others have pushed to support for Mac and Linux on this project.  Can you explain to me what you think we are resisting in your mind?

**Comment by tanis2000** [comment]
@dellis1972 I used the pkg and installed MonoGame that way but I'd really love to know where MSBuildExtensionsPath points on Mac so that I can deploy my own stuff shall I change anything in the content pipeline. The good news that now that this file is in the correct place, the project starts :)

@tomspilman it looks like there is quite a bit of frustration going on here. I'm not making a couple bucks a month just for contributing to OSS projects myself, so it's hardly ever going to happen. The most logical solution is to find a cross-platform project that would cover the costs of bringing Mac and Linux on par with Windows. That's more likely to happen on your side or those who are already doing ports to those platforms, though. I do not have contacts in that field. If you know anyone and want to redirect that job to someone else, then I guess that you can find more people like me that would gladly take that job and contribute back to MG all the changes needed.

**Comment by dellis1972** [comment]
We lost of bunch of good Mac developers a few years ago to CocosSharp and other projects, not because they didn't want to work on MG but because they didn't have the time. Since then its been mainly me working on Mac support (like the installer, Addin Templates) all of this stuff is important. Yes there are issues which the core team are aware of but until recently no-one was willing to step up and work on them I think that @mrhelmut and now @tanis2000 are some of the few. At this point I'd like to shout out to @cra0zy and @mrhelmut for these recent efforts on the Pipeline and patching OpenTK to that the DesktopGL port can be a reality (hopefully in the next release).

**Comment by dellis1972** [comment]
@tanis2000 the installer installs into

```/Library/Frameworks/MonoGame.framework/Current```

The mono install should also be in 

```/Library/Frameworks/Mono.framework```

The installer takes care of putting that all in the right place for developers.

**Comment by tanis2000** [comment]
@dellis1972 found it in `/Library/Frameworks/MonoGame.framework/v3.5.0.1222/MonoGame.Content.Builder.targets`. I'm replying to keep it there for future reference :)

**Comment by dellis1972** [comment]
@tanis2000 cool :) I did reply :D Glad you are up and running.

**Comment by dellis1972** [comment]
@tanis2000 I'll try and get some time to write up a *Getting Setup* guide for Mac based Contributors.. I'll add it to my todo list.

**Comment by tomspilman** [comment]
@dellis1972 - How about doing it as part of a refresh to [CONTRIBUTING.md](https://github.com/mono/MonoGame/blob/develop/CONTRIBUTING.md).  Ideally then we could also link it into the website docs.

**Comment by cra0zy** [comment]
> I'll try and get some time to write up a Getting Setup guide for Mac based Contributors.. I'll add it to my todo list.

Just want to mention that I started working on an update to Contributing and Readme files since https://github.com/mono/MonoGame/pull/4418#issuecomment-173902686 so... I'll either submit a PR about it later today or tomorrow.

**Comment by dellis1972** [comment]
@tomspilman  sure no problem.
@cra0zy cool, I'll keep an eye out for that.

**Comment by prime31** [comment]
@tomspilman the apparent resistance seems to be present in [this thread](https://github.com/mono/MonoGame/issues/4399) as well. @flibitijibibo has already solved all of the Mac/Linux issues and he graciously offers up his solution for backporting to MonoGame. If there arent a lot of contributors and the core Mac folks arent around anymore it seems reducing the Mac code/dependencies (and #if statements) to a minimal set like FNA did is a good plan. I'd be happy to contribute on the Mac side of things as well but that $1000 Xamarin license is a challenge.

**Comment by hach-que** [comment]
Even though I do frequently work on Mac and Linux, I do most of my cross-platform patching in my own MonoGame branch and at a higher level in my own game engine which runs on MonoGame. Often I don't have time to go through the PR process, and I'm already maintaining patches to support embedding MonoGame in GTK# and other toolkits. So it doesn't make a lot of sense for me to run into an issue, then try and isolate it on an unpatched MonoGame, submit the PR, wait for the PR to be reviewed and maybe accepted, and then continue what I was working on. That process is far slower than just local patching and re-integrating upstream every few months.

**Comment by hach-que** [comment]
> I'd be happy to contribute on the Mac side of things as well but that $1000 Xamarin license is a challenge.

We know, but there's little anyone can do. We have a few options for Mac, but on iOS and Android we're totally screwed. There are hopes that CoreCLR might eventually run on those platforms, but that would be years away.

It's very disheartening to see developers time and time again pick Unity over something MonoGame-based purely over the issue of Xamarin's licensing, but I don't blame them. Why would you pay thousands in licensing when Unity is free?

**Comment by dellis1972** [comment]
The Xamarin Licence is only "thousands" if you want a Business licence and are unable to live without Visual Studio ;). MonoGame does run on the Indie offering which is $299 a year or $25 a month so for iOS and Android it costs $50 a month and you start and stop so no need to pay for a whole year up front so only get it when you need it. Xamarin also offers free licences for OSS contributors and Library maintainers in addition to a limited offering for free game dev licences to anyone who had a published game over the christmas period. 

Ok I admit you can't be Xamarin.Mac on Indie (which is a shame) but that might change at some point.

There are other options (RemObjects to name one) but no one seems willing to submit a port for those platforms. What there isn't is a totally free option and until CoreCLR works on all of those platforms there won't be as its a huge job to create a .net runtime.

I also find it disheartening that people choose Unity especially XNA developers.. but it is free thats because they have Pro offering funding all the people using it for free. MonoGame has no such equivalent and zero funding so its a bit difficult to compete on that side of things...

Getting back on topic
@tanis2000 I think I re-produced your issue with MonoMac with the current stable release. MonoMac does not run up.

**Comment by prime31** [comment]
Once SDL2 is in place Xamarin can be fully erased as a dependency at least on Mac (and Android as well but not iOS). That would at least make Mac work with MonoKickStart and could potentially make a single code path for all desktop platforms. That alone would be a huge improvement and it would make any fixes automatically apply to all desktop targets.

**Comment by hach-que** [comment]
It can't be replaced on Android as there's no available runtime without Xamarin.

**Comment by dellis1972** [comment]
@prime31 we cannot erase the Xamarin dependency. MonoKickStart CANNOT be used on places like the Mac/Android/iOS Store as it breaks the Mono agreements about embedding the runtime (see there comments https://github.com/flibitijibibo/MonoKickstart/commit/1c88eea3668b5e804960b02d518d70f405906189). So deployment on to mac/linux manually is ok but you cannot publish on the store. 

Also without the Xamarin bindings you can say goodbye to Google Play Integration on Android, Gamer Services Integration on Mac etc.

**Comment by tomspilman** [comment]
> the apparent resistance seems to be present in this thread as well.

FNA is a specialized fork of MonoGame that is open source and under the MonoGame license.  It makes technical compromises we don't think are suitable for MonoGame targeting desktop, mobile, and consoles.  Hence the fork.

Since OpenTK has failed us in its commitment to make a good abstraction/bindings for us we're sort of gun shy on depending on yet someone else.  However SDL2 is the alternative we originally considered at the time, has an active team behind it, and it is really one of the few other choices out there.  The bindings for this are just a little bit of code... but important to how our platform abstraction works for desktop and mobile.  And between @cra0zy on SDL and @dellis1972 on OpenGL things look to be well handled at this point.

I don't see how this is any resistance to Mac and Linux support.  We just want to do it in a way that best fits in to the more complex needs of MonoGame as a whole.

> I'd be happy to contribute on the Mac side of things as well but that $1000 Xamarin license is a challenge.

I really wish I could fix that.  However...  you and other users might be able to.

Has anyone outside of us core MonoGame maintainers ever spoken to Xamarin about the licensing for OSX?  They did it for iOS and Android... arguably their biggest platforms.  I don't see why they wouldn't with OSX if enough people demanded it.

Beyond that we can start to work out how to support Microsoft's CoreCLR for Mac/Linux and ideally all our other platforms too.  It will just be a while before that becomes a good solution.

**Comment by hach-que** [comment]
I spoke to them a few years ago about the licensing. Their response was
that if you're doing game development full time then *obviously* you're
paying yourself a salary and thus the Xamarin licenses are affordable.

Which of course is not how a lot of independent games are funded at all...

**Comment by dellis1972** [comment]
@hach-que things might have changed since then (see my earlier comment about free licences and the christmas offer) , might be worth cycling back and checking again.

**Comment by hach-que** [comment]
Well I have an open source license now because of Protobuild, so I don't really have to worry about obtaining licenses.

The christmas offer is pretty silly though; it's only available to game developers who already have something published on the app store, in which case, they're already using an engine other than MonoGame :P

**Comment by dellis1972** [comment]
If you had a published XNA game (for example) on Windows Phone, Xbox 360 or Windows then it wasn't that silly :) I know of a few developers who fell into that category and applied. 

I think the point is it was an olive branch, hopefully the first of many :)

**Comment by tanis2000** [comment]
@dellis1972 super! At least now we both see what the problem is :)
And I can start looking at the stencil buffer stuff.

Speaking from a C++ dev point of view, I don't understand why SDL2 isn't enough. I use it in my C++ engine to abstract all the platforms and SDL itself already sports ObjC and Java code to run the native C code on iOS and Android. Isn't it simply a matter of tooling to get those two platforms to run as long as you're not using Play Services or the Game Center?

Those two can be easily integrated by writing a few lines of native code if that's all that's needed to PInvoke native functions.

Please correct me if I'm wrong and help me understand if we can come up with a way to avoid all of the Xamarin stuff.

**Comment by flibitijibibo** [comment]
If it makes things any easier, the only real restriction of using MonoKickstart where signed binaries is required isn't necessary _how_ you ship Mono, it's just that you need the rights to do so. For Transistor, Supergiant opted to use Xamarin's build process, but mostly out of familiarity - it would have been feasible to ship my Mac port without the extra NSMain() function, which is the only thing that differed between the MAS SKU and the other Mac SKUs.

The question should be whether or not you want to be the software that introduces the Xamarin dependency - for stuff like GamerServices there's definitely an incentive (and hey, the Net namespaces did get split up for things like that...), but given the option between a backend that has a $1k license versus no license, when both effectively function just as good as each other, I can't think of someone that'd opt for the former. If I may forward feedback from an FNA user, one commented that they liked how FNA did not introduce commercially-licensed software into their pipeline - while it was nice for me, it's definitely not true of MonoGame and this might be making that unclear for developers evaluating it.

Of course, all of this is just about the Mac... with Android you can ship unsigned binaries as well, provided people are willing to allow those apps on their phone/tablet (but I mean, ALL of them already are and many have probably rooted the thing already, especially gamers). iOS, yeah, you're kinda screwed until CoreCLR ships for mobile or a cross-compiler gets released.

**Comment by tanis2000** [comment]
@hach-que I agree that's silly. I did get the iOS and Android licenses for a year because I have a few old Cocos2D games published.

Anyway I did inquire last November to see if they had any plans for Mac, iOS and Android and they pretty much said the same thing, that if I'm making money I can pay for the licenses. Too bad I'm making money from stuff that's got nothing to do with games.

**Comment by tanis2000** [comment]
@tomspilman so the main problem with Mac, iOS and Android is that we all depend on Xamarin for distribution as we cannot embed Mono. And I suppose you have already looked for tools that can do C# to C++ or IL to C++ transpilation and none could be found.

So our last hope is CoreCLR and .NET Native and both aren't production ready nor will they be until a couple of years.

Quoting @hach-que  and @flibitijibibo, we're kinda screwed.

**Comment by tomspilman** [comment]
> And I suppose you have already looked for tools that can do C# to C++ or IL to C++ transpilation

There will be a solution for this in one way or another within the year.  Even Microsoft has their own cross compiler now... see https://github.com/dotnet/corert.

Still these solutions are not ideal.


> we're kinda screwed

I agree that some indie devs that can't afford $25 a month are screwed.

**Comment by tanis2000** [comment]
CoreRT seems to head in the right direction. But I guess they won't look into iOS or Android for quite some time. But if they do cover Mac and Linux, that's already a good step forward. I can't seem to find their roadmap, though.

>I agree that some indie devs that can't afford $25 a month are screwed.

That's not exactly what I meant. I was referring mainly to the fact that we depend on Xamarin and that we have no control over their decisions.

**Comment by tomspilman** [comment]
> I can't seem to find their roadmap, though.

They only have this which does mention Unix as a platform goal:

  https://github.com/dotnet/corert/blob/master/Documentation/high-level-engineering-plan.md


>  the fact that we depend on Xamarin and that we have no control over their decisions.

It does worry me that Xamarin controls our fate on mobile and even consoles where you need to license their runtimes.  However good things are happening in the open source C# world which means some of that won't last much longer.

**Comment by tanis2000** [comment]
I didn't know that their runtime is needed for consoles as well.. I thought they had no runtimes for PS4, XOne or anything else...

**Comment by tanis2000** [comment]
BTW this is the part that I find most interesting for us: https://github.com/dotnet/corert/tree/master/src/ILCompiler.Compiler/src/CppCodeGen

If they manage to get that thing working and we can convert C# to C++, then it would be a breeze to write the tools to just compile that C++ stuff into native binaries bypassing all the Xamarin stuff.

**Comment by cra0zy** [comment]
There is also: https://github.com/ciplogic/CodeRefractor

**Comment by dellis1972** [comment]
@cra0zy "generics, delegates, etc. do not work." sorry dude work needs doing.
