### ISSUE TITLE
High-Level classes for material, lights and shadows

### ISSUE THREAD

**Issue by InfiniteProductions** [MonoGame/MonoGame#4480]
I would like to suggest some addition MonoGame could offer, as IMHO, mimicking XNA with also its lacks and flaws would be a mistake.

Working with XNA for quite a while now, I'm just disappointed by the incredible lack of high-level interface to material and light stuff. By material I mean things like Unity offer, a combination of textures and shaders parameters to create very common material look (metal, glass, wood, stone) with diffuse, normal/bump map, spec map, alpha map eventually.
Also, it's even more incredible to see how time wasting/painful could be to add simple lights and shadow in XNA (there are too much samples in fact).

Many people/companies tried and give-up now, leaving behind kind of junk-yard full of dead engines (Ploobs: not finished, full of annoying issues, SunBurn: dead, no way to get sourcecode, EngineNine: dead too, at least free and with source).

It's quite a shame XNA team never made anything, providing quite a high-level layer for basic 2D games is good (despite it doesn't include easy to use scrolling/camera/level building build-in features) but 3D is a lot more common and have more focus, I think, and all devs have to reinvent the wheel over and over every time for very basic things.

So, I would be really pleased to have some kind of BasicEffect class for common material settings, something like:

Material wood = new Material (woodtexture, specmap);

or 

Material rustymetal = new Material (metaltex, ... <other parameters here>);

The same for lights and shadows:

Light point1 = new Light(Pointtype, position, intensity, color);
point1.castshadow = true;
point1.shadowtype = smooth;

instead of thousands of code lines + HLSL for shaders .
(with an enum to specify light type or various constructors for point/spot lights).

As MG has to support many platform, it would need obviously to offer some way to the common features supported by all (the ONLY COMMON base), and very specific features (DX10/11 on windows for example) and perhaps a way to specify which PS/VS version caller want to use.

By the way, if such thing already exist, I'm really happy to see it.

**Comment by tgjones** [comment]
Personally, I think people like MonoGame (and XNA before it) precisely because it is lower-level than Unity, while still being higher-level than raw DirectX / OpenGL.

I think there's a big - and mostly unexplored, with notable exceptions like DigitalRune - opportunity for MonoGame-based middleware. I think that's a better direction than MonoGame starting to incorporate higher-level constructs.

> (Ploobs: not finished, full of annoying issues, SunBurn: dead, no way to get sourcecode, EngineNine: dead too, at least free and with source).

I agree, this an unfortunate state of affairs (EngineNine's material system was based on my old [shader stitching system](http://timjones.tw/blog/archive/2010/11/13/introducing-stitchup-generating-shaders-from-hlsl-shader-fragments), so selfishly I hoped it would catch on! :)). I'm optimistic about more middleware appearing, as MonoGame matures. I'm working on something myself, but precisely because I don't want to add to the XNA / MonoGame engine graveyard, I won't release it until I think it has a good chance of surviving.

**Comment by InfiniteProductions** [comment]
Yep but unfortunately, if nobody make a move and take some risk nothing will change at all, I'm afraid.

as MonoGame hold XNA's legacy, the way people see it and think of it and how to use it will remain the same forever, until it dies. Which lead to the same result and fill the graveyard of amazing-unfinished things ! Making the framework or engine is very time and resource consuming, and people get burned along a way which is harder than they initially expect, doing nothing at the end :(.

**Comment by Jjagg** [comment]
Closing as out of scope.

**Comment by BrianBergh** [comment]
This is exactly why im thinking of quitting monogame. I've created a pretty cool 3D game, but i can't seem to get materials for my 3D models (i've created in Blender) to work. Im no expert in Shader, and i have a really hard time finding some "working" examples on the internet. I can find a lot of old XNA stuff (from 2010 - aka 9 years old), and they won't work, and i cant get any help anywhere. So....soon im giving up! A shame, cause i've spend more than a half year creating this game.
