### ISSUE TITLE
Write explination/defense of the Content Pipeline

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4600]
We really need to add a section to the MonoGame docs explaining what the content pipeline is, why it is important, and answers to frequently asked questions about it.  This issue comes up a lot and we need a standard place to point people at.

It would be linked to here:

http://www.monogame.net/documentation/?page=Adding_Art_Sounds_and_More

And would be specifically aimed at explaining and to some extent defending the use of content compiled before runtime.

It should not be detailing the inner workings of the pipeline like this:

https://msdn.microsoft.com/en-us/library/bb447745.aspx

It should focus entirely on why the content pipeline exists and why it is better than loading PNGs or WAVs at runtime.

**Comment by tomspilman** [comment]
@dellis1972 - Did you write something like this recently?

**Comment by dellis1972** [comment]
I blogged about it. 

http://www.infinitespace-studios.co.uk/general/monogame-content-pipeline-why/

If you think its good enough I can move it over

**Comment by tomspilman** [comment]
> If you think its good enough I can move it over

I think it probably needs to be edited some before it really fits as documentation.  Still a lot of the ideas are likely what we want to explain.

Like a simple chart of a texture and audio files sizes on disk and in memory with and without the pipeline would be a good start to explaining it.

Talking specifics like how a DXT1 textures have 8 to 1 compression...  visualizing like a 512x512 sized texture vs a 128x128 size texture.

How using PNGs means the runtime has to generate mipmaps at load time and the time that takes.

Etc.

**Comment by InfiniteProductions** [comment]
I think IMHO there is one big lack in trying to explain content pipeline, it is related to initially target game by Microsoft XNA team (if they know what their target was at this time).

From my point of view, content pipeline is a typical "it makes complicated things easy" with the usual drawback (hidden under the red carpet) "it makes easy thing complicated".
Here the complicated thing is loading assets, in various format, in a consistent way.
The easy thing is loading assets at runtime, when they're needed, and only at that time.
(no need to use memory for level 2 to 99, or even 9999, will all scenery, foes, backgrounds, if the player is still struggling to beat level1 !)

I believe Microsoft don't really know what they're aimed for, starting for small, simple games for their platforms (full game that can fit in a phone memory), and then, by keeping the same "wrong" habits without questioning what they're doing, some (apprentice) game devs keep thinking as the game class as a whole, as one game class hold its own content.

But nothing anywhere prevent us for creating many game objects with various game classes, one class of each "scene" (to use Unity vocabulary), and the main program as the "scenario" (menu -> options - [ new game ] -> level 1 -> level 2 -> secret level -> level3.. -> game over -> menu, each item is a Game class).
As each game class as LoadContent and UnloadContent, it helps managing memory between discontinuous levels/scenes.

The main issue comes with continuous games (flight/car "simulator", sandbox) for which MonoGame team (in its extensive meaning: current involved people + anyone would join later) may have/could to something. I mean, blindly copying Microsoft is a thing, but they are not perfect, what they do or did was not an absolute perfection to mimic (obviously :P), so MG can/could provide another way of dealing with assets which will be more efficient for continuous games.
Maybe something which can use the content pipeline, but outside LoadContent method (mostly in Update) and/or a disk caching system (all assets still loaded/processed in LoadContent, but only loaded in the memory when a dedicated method is called) which provide option for settings memory devs/players would like to reserve for it, mostly to allow support for future/more expensive hardware.

**Comment by dellis1972** [comment]
You can use Content.Load outside of a LoadContent method. The ContentManager does not restrict you in anyway, the only real requirement is the existence of a GraphicsDevice instance for loading GPU resources like textures.

So loading content in an Update method can be done.. whether its a good idea or not in a different question.  You can load on a background thread but eventually you will need to hit the "UI" thread to create texture/shader. But designing your game so that it loads "levels" (i.e not textures/shaders) during game play is perfectly possible. 

[InfiniteFlight](http://www.infinite-flight.com) is a perfect example of a flight simulator that uses MonoGame. You can fly between airports, and afaik it loads terrain dynamically and runs in mobile devices.

If we had blindly copied XNA we would have a .contentproj project which was tied to the IDE and not a command line content processor which can easily be used outside of the IDE. XNA API Compatibility was an important focus of the project at the start but we are now in a position to add API's which will improve things.

**Comment by KonajuGames** [comment]
> you will need to hit the "UI" thread to create texture/shader

MonoGame takes care of that, and it's only for OpenGL-based platforms.

The main issue here is management of ContentManager instances.  We do not know how your game will be loading content, so it is left up to you to control the lifetime of the ContentManager instances.  Games more complex than a single screen will likely have several ContentManager instances.  How you manage these instances will depend on how your game works.

In TY4, we had several ContentManager instances with varying lifetimes:
- one for global assets, such as fonts and some textures.  This was created at launch, the assets loaded and never released.
- one for the main menu assets.  Outside of the global assets, these assets could be unloaded when the player left the main menu to start a game.
- one for the level assets.  This was the background artwork, enemy models and animations and sounds associated with the level.  These stayed alive for the duration of the level.
- one for the player character.  Since the player could change the look of their character, this had a ContentManager all to itself.

I have made open world games before (not in MonoGame, but the concepts stay the same).  We broke the world up into chunks, and considered each chunk to be similar to a level in a regular game, except we could have several chunks loaded at any one time, and chunks would be loaded and unloaded as the player moved around the world.  In this case, each chunk would have its own ContentManager to manage the assets loaded by that chunk.

**Comment by InfiniteProductions** [comment]
@dellis1972  and @KonajuGames: that's interesting and deserve a few paragraphs in a documentation with also some samples to see how it works actually and how to deal with it.

**Comment by InfiniteProductions** [comment]
Another critical issue to address: in this [post](http://community.monogame.net/t/external-reference-in-model-processor/7381/7) (there are a few others on this too).
As long as such issue are alive, I'm afraid deferred rendering/forward shading will be hard/impossible to do, so no decent 3D engines could be made with MG at all :|.

**Comment by tomspilman** [comment]
> Another critical issue to address: in this post (there are a few others on this too).

That thread went in the wrong direction.  As @mgarstenauer said you need to pass the `.fx` file to the 

 http://community.monogame.net/t/external-reference-in-model-processor/7381/2

You can find numerous XNA examples online that show that is how it works.  If there is a bug when doing that... then report that bug.

I suggest you start a new issue to discuss this.

> As long as such issue are alive, I'm afraid deferred rendering/forward shading will be hard/impossible to do, so no decent 3D engines could be made with MG at all :|.

There are several 3D engines and deferred renders written in MonoGame.  There is no problem here.

**Comment by mrhelmut** [comment]
[Likely fixed](https://docs.monogame.net/articles/content/why_content_pipeline.html).
