### ISSUE TITLE
Playing Songs stop before finishing in Windows, WindowsGL, and DesktopGL

### ISSUE THREAD

**Issue by neofuji** [MonoGame/MonoGame#4666]
When the streaming finishes, Songs will invoke the `OnSongFinishedPlaying` method.
However, the samples are still in a sound buffer, so they will not be played.

**Comment by mrhelmut** [comment]
Confirmed on DesktopGL.

This is because ```OggStreamer``` invokes ```OggStream.FinishedAction``` when the last buffer is filled & queued, not when it has finished playing. This represents about 500ms of sound (depending on how fast the decoder thread works).
I'll try to take a look at this, but it's not as simple as checking the last buffer state (because there are many reasons which make the state not so reliable to detect the end of a ```Song```).

I believe other implementations are not affected, could someone confirm?

**Comment by neofuji** [comment]
I tried fixing it on Windows, and it has gone well.
