### ISSUE TITLE
Samsung Smart TV Support

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4670]
We should look to see what it would take to support Samsung's Smart TV gaming:

https://www.youtube.com/watch?v=8mjQ2Ew2RO0
https://www.samsungdforum.com/devtools/sdkdownload

It seems like maybe Samsung is moving towards Tizen (https://www.tizen.org/) for future devices, so maybe we should focus on it instead?

**Comment by cra0zy** [comment]
This isn't gonna be an easy task :| http://kitsilanosoftware.github.io/MonoTizen/

**Comment by tomspilman** [comment]
@cra0zy - We have other options... like the cross compiler I use on Vita and XB1.  We don't need Mono to support new platforms anymore.

The bigger question is if Tizen is worth our time and effort?

**Comment by cra0zy** [comment]
> like the cross compiler I use on Vita and XB1

Wait we do? Sweet. What is the cross compiler compiling to? Can it be used for Android to avoid mono? Is the cross compiler open to public?

**Comment by tomspilman** [comment]
> What is the cross compiler compiling to? 

IL to C/C++.

> Can it be used for Android to avoid mono?

It could support it, but mostly the goal was consoles and other non-Mono platforms.  I would want to wait and see what happens with Xamarin in the coming months with the merger before worrying about this again.

> Is the cross compiler open to public?

Not yet, but it will be...  I plan to fully open source the whole thing.

**Comment by cra0zy** [comment]
> Not yet, but it will be... I plan to fully open source the whole thing.

Do notify me when I can get my hands on it, I have so many evil ideas in my head.... Ubuntu Touch... mhmmm...

**Comment by tomspilman** [comment]
> I have so many evil ideas in my head

I figured many people would find interesting uses for it. :)

**Comment by tomspilman** [comment]
Tizen is now the clear path for this.  See https://github.com/MonoGame/MonoGame/issues/5302.

**Comment by ludescher** [comment]
> like the cross compiler I use on Vita and XB1

I know I’m a bit late to the party, but I’m really eager to know—have you released or open-sourced the transpiler? If so, where can I access it? I’d be thrilled to explore its potential and see just how far we can take it.
Thank you in advance!

**Comment by ThomasFOG** [comment]
> I know I’m a bit late to the party, but I’m really eager to know—have you released or open-sourced the transpiler? If so, where can I access it? I’d be thrilled to explore its potential and see just how far we can take it.
> Thank you in advance!

It's open source but access is restricted to console-registered users. You can eventually ask tom. This transpiler is slowly getting replaced by ```PublishAot``` on all platforms, and it's getting retired (and is limited to .NET 4.5/C#5).

**Comment by ludescher** [comment]
First of all, thank you @ThomasFOG so much for your help!

If I understand correctly, the transpiler for .NET 4.5/C#5 is now quite outdated.
I should mention that I'm not a registered console developer, I'm just a hobbyist who enjoys coding fun projects.

I hope I'm not being a bother, great @tomspilman, but I'm particularly curious about Vita development. If it's still functional, could you share some information about how it works? I would deeply appreciate any insights or guidance you can provide.

Thank you in advance!

**Comment by ThomasFOG** [comment]
One thing to consider about the Vita port of MonoGame, is that it is based on the official Sony SDK. Which means that it's not an homebrew software and can only be used by Sony-registered developers. Even if Tom gives you an access to the transpiler, it won't be usable without Sony's bits and the MonoGame port itself will not be sharable with you for the same reason. You would just end up with a non-functional C++ generator.

**Comment by ludescher** [comment]
Thank you for the information, @ThomasFOG.
I understand your concerns. I'm well aware that all those Sony specific Vita tools aren’t accessible to everyone, myself included, which is a real shame since the indie scene was so vibrant, especially towards the end.

If you ask me, Sony should consider open-sourcing their Vita SDKs and related resources, or at least making them publicly available. This would allow the community to engage with their technology more easily and, naturally, help strengthen the community. It could even be a clever strategy for a future handheld, if they ever decide to release one again! After all, focusing solely on AAA titles was a major reason why the Vita didn’t succeed.
Sorry, I’m completely rambling here!

What I really wanted to say is that I'm well aware that if I want to develop for the Vita, I'll need to rebuild the entire backend from scratch using the homebrew SDK. This is an enormous effort and should not be underestimated. The graphical part will be more challenging for me, as I have little experience in that area. On the other hand, I do have experience with interpreters and compilers, which is why I'm particularly interested in the C++ transpiler. 

I’d love to learn more about the approach and structure for this. Starting everything from scratch feels a bit overwhelming for a hobby project. 

Nevertheless, thank you so much for your time and your help!
