### ISSUE TITLE
Offer custom installation path

### ISSUE THREAD

**Issue by InfiniteProductions** [MonoGame/MonoGame#4682]
The installer of the MG 3.5 release force install into C:\Program Files (x86)\MonoGame directory, I don't get any way to change it.
Linked to issue #1372, I have another, old 3.4 in another directory, so I have no idea on what could happen now when creating new project (especially with #3808)

And for some reason, pipeline tool failed to install (nothing helpful to provide unfortunately, except installer can't copy the file for some reason, and only this executable, perhaps because I don't run the installer as administrator, on my win7 system)

**Comment by tomspilman** [comment]
> The installer of the MG 3.5 release force install into C:\Program Files (x86)\MonoGame directory, I don't get any way to change it.

It has always been like this that I can see.  I went back and tried all the installers back to 3.0 and none of them offered an option for install location.


> And for some reason, pipeline tool failed to install 

The pipeline installs to the `MSBuild` folder...

https://github.com/mono/MonoGame/blob/develop/Installers/Windows/MonoGame.nsi#L19

... the only difference from everything else being that it lives in the 32bit 'Program Files (x86)' folder and not just `Program Files`.

Could be that maybe you didn't have permission for install into that folder for some reason?

We explicitly ask for admin level access during install, so that shouldn't happen.

**Comment by tomspilman** [comment]
@KonajuGames  @dellis1972 

Should we offer an option of install location for the non-MSBuild bits of MonoGame?

I guess the complication there is how the templates access assemblies for each platform?  Currently it assumes the `Program Files` path:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/MonoGame.Common.props#L5

Maybe we finally need to add an environment variable on install for this?

**Comment by harry-cpp** [comment]
No longer an issue with 3.8.

**Comment by Phrenomythic** [comment]
It's an issue for me. I installed mono and clearly there's no option to specify installation folder. I had to manually append the path to the PATH environment variables, after being confounded why for a moment, why I couldn't run nuget from the command prompt.

**Comment by mrhelmut** [comment]
The installer is being deprecated for the official 3.8 release. MonoGame will no longer require an installation and will assume a purely nuget-based distribution model.

**Comment by Phrenomythic** [comment]
Aw, shucks! Didn't realize this was Monogame... My beef is with Mono itself. Sorry 'bout that.
