### ISSUE TITLE
Cleanup remains of MonoMac

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#4693]
With the announcement of Xamarin tools all being free to use:

  https://blog.xamarin.com/xamarin-for-all/

Should we continue to support MonoMac or just push people to use Xamarin.Mac now?

**Comment by dellis1972** [comment]
I've vote drop MonoMac in favour of DekstopGL.. I just need to test we can publish DesktopGL in the store.

**Comment by hach-que** [comment]
DesktopGL doesn't replace MonoMac, the Xamarin.Mac path replaces MonoMac.

**Comment by tanis2000** [comment]
Better wait until the free version of Xamarin.Mac is actually available and make sure the licensing is as expected before dropping support for MonoMac. But AFAIK MonoMac isn't going to be of much use anyway in the near future due to the 32bit restriction.

**Comment by tomspilman** [comment]
@dellis1972 - Do you happen to know the timeline for the free version of Xamarin.Mac ?

**Comment by dellis1972** [comment]
@tomspilman if people upgrade.. it should be there now. in the latest stable afaik

**Comment by tomspilman** [comment]
@dellis1972 @cra0zy - Does dropping MonoMac mean we loose the single binary DesktopGL feature?  Would a Xamarin.Mac title need to be packaged/built differently?

**Comment by tanis2000** [comment]
I checked this morning but the update server for the stable channel wasn't working.. I guess we'll find out by monday morning though.

**Comment by hach-que** [comment]
The Xamarin.Mac version is already packaged differently from DesktopGL. We
currently have both MacOS and DesktopGL, which are different.

The difference is that DesktopGL doesn't produce an app package that can be
uploaded to the app store, because it runs using the full .NET framework
and doesn't use native linking.

**Comment by dellis1972** [comment]
The current Xamarin.Mac project template uses the DesktopGL assembly
because the MonoMac one flat didn't work at all and is completely broken.
That templates does produce an .app package.

I'm currently porting a simple game over to this to confirm that it will be
publishable on the mac store.

**Comment by hach-que** [comment]
Normal .NET assemblies don't confine to the API restrictions that apply to
the Mac app store. Even if you can build it, there's no guarentee you can
publish it.

In any case, the Xamarin.Mac package should definitely *not* have DesktopGL
in it as it's not even the right target framework in the context of NuGet
packaging, let alone API compatibility.

The MonoMac version won't work, you are correct. But that was only ever for
people who couldn't afford the Xamarin.Mac license and never permitted
deployment to the app store anyway. The new Xamarin.Mac version that I
submitted a while back does work for app store publishing, as every build
under the MacOS platform in Protobuild for App projects produces a .app
file.

There's every possibility in the future that Apple will start requiring
Metal on new app store submissions on both Mac and iOS, so we should not be
removing our ability to ship different versions of the code for Mac.

**Comment by dellis1972** [comment]
At the moment DesktopGL uses OpenTK for its Graphics which uses Mac API's
under the hood on mac.
OpenAL is a mac framework which is uses to audio. NVorbis might be a
sticking point but I guess I'll find out in this test app.

If these is a new Xamarin.Mac version is that built as part of the build?
I've not seen it, I saw a bunch of LEGACY defines but nothing in the
MonoMac stuff seemed to work at all with the new Xamairn,Mac. Perhaps you
can point me to how we should build this Xamarin.Mac support as part of the
build process?

**Comment by hach-que** [comment]
Xamarin.Mac is not currently built on the MonoGame build server because
Xamarin Studio needs to be upgraded on the buildbot. I raised this issue
when I initially submitted the PR. However we couldn't leave it as-is
because people with newer versions of Xamarin Studio couldn't build
MonoGame because of the API changes.

Currently, if you have a version of Xamarin Studio that actually ships with
Xamarin.Mac, and you generate projects for MacOS, you will get the newer
APIs. If you don't have the newer APIs it will fallback to XamMac or
MonoMac depending on what you have installed.

On my build server, I track develop and have the latest Xamarin Studio, so
I'm building and testing this code path even if the upstream buildbot isn't.

There are definitely API changes between MonoMac's OpenTK and the app store
conforming Xamarin.Mac OpenTK. And yes they are different APIs again (like
how Android and iOS OpenTKs are different). In particular I had to disable
gamepads for Xamarin.Mac because the OpenTK APIs for that were dropped in
Xamarin.Mac.

**Comment by cra0zy** [comment]
If DesktopGL can function in app store there really is no point in keeping Xamarin.Mac. On a side note, just want to mention that we can use SDL + Metal combo.

**Comment by dellis1972** [comment]
I knew about the Input.* api's being missing in Xamarin.Mac OpenTK. I did
raise this issue with the Xamarin.Mac team, to be honest I don't think they
were ever there. That is kind of a big hole no GamePads.. and the newer API
which tvOS uses is a bit of a pain.

**Comment by tomspilman** [comment]
FYI.  Protobuild is removing MonoMac support as well https://github.com/Protobuild/Protobuild/issues/164.

**Comment by tomspilman** [comment]
@dellis1972 @cra0zy ??

**Comment by cra0zy** [comment]
I don't know what the status on this is.

**Comment by tomspilman** [comment]
According to @Jjagg there are still some bits of MonoMac left in the code base.  It would be good for someone to get in there and remove those last bits.
