### ISSUE TITLE
Mouse event handler works inconsistently on Xamarin.Mac but is fine on MonoMac

### ISSUE THREAD

**Issue by SoundGoddess** [MonoGame/MonoGame#4827]
I've tried doing mouse drag event handling in both MonoGame base and MonoGame.Extended and for some reason Xamarin.Mac projects do not work as expected while MonoMac projects work fine.  I can capture drag events with the middle mouse button but the right and left mouse buttons do not drag.  I tried this with some XNA drag and drop code I ported, and then further tested with a brand new project using the the MonoGame.Extended InputListener Demo code.  

This seems like a bug where the mouse movement events aren't firing for some reason while the button is in a pressed state.

**Comment by SoundGoddess** [comment]
Example project where MonoMac works and Xamarin.Mac does not:
http://HathorsLove.com/downloads/MouseInputIssuesXamarin.zip

**Comment by mini-ninja-64** [comment]
this issue is also present in the cross platform desktop application structure on mac, the mouse position does not update with a mouse button down. For a workaround you can use a bit of window forms:

Point mouseRelative = new Point(System.Windows.Forms.Control.MousePosition.X - this.Window.ClientBounds.X, System.Windows.Forms.Control.MousePosition.Y - this.Window.ClientBounds.Y);

**Comment by tomspilman** [comment]
@dellis1972 @cra0zy ?

**Comment by mrhelmut** [comment]
#4874 should fix this issue. I was experiencing it too on OS X (it was a problem with OpenTK event pump) and it doesn't occur on this branch.

**Comment by cra0zy** [comment]
This should be fixed, Mouse backend for Mac has been switched to SDL.
