### ISSUE TITLE
Monogame installer screws Visual Studios' UWP deployment

### ISSUE THREAD

**Issue by xclud** [MonoGame/MonoGame#4886]
Hi just installed Monogame 3.6 installer and I noticed my VS 2015 Update 2 gets stuck when deploying UWP apps, even those not being a Monogame project.

To make sure this issue is coming from Monogame, I installed a clean windows 10 and vs 2015 and the same problem happened.

Previously I had MG 3.5 official release with no problem.

**Comment by tomspilman** [comment]
> Monogame installer screws Visual Studios' UWP deployment

That is pretty hard to believe.

You can see the source of the installer here:

https://github.com/mono/MonoGame/blob/develop/Installers/Windows/MonoGame.nsi

Our integration with VS is limited to common things that just about every other SDK does.

We in no way touching anything to do with UWP deployment.

If anything is occurring it is some crazy unexpected dependency...  like if installing the OpenAL runtime breaks UWP deployment.

Still if someone else has the same issue please let us know.

**Comment by xclud** [comment]
I gave it another try:

I did install Windows 10 and Visual Studio on a virtual machine.

- UWP deployment works.
- Installed MG 3.5 ==> Still works.
- Created a System Restore.
- Installed MG 3.6 ==> All UWP deployments get stuck for hours with message "Registering the application to run from layout..."
- Restore my system from System Restore, Uninstalled MG ==> Everything works perfectly.
- Installed MG 3.5 ==> Still works.
- Installed MG 3.6 ==> The problem comes again.

**Comment by tomspilman** [comment]
Thanks @xclud .

I suggest looking at the existing posts and solutions reported for UWP deploy errors as most likely this issue is unrelated to MonoGame.

https://social.msdn.microsoft.com/Forums/windowsapps/en-US/efe80378-c01d-4449-92f5-02c28509cc11/uwp-stuck-at-registering-the-application-to-run-from-layout-after-installing-build-10565?forum=wpdevelop

http://stackoverflow.com/questions/34985599/uwp-deployment-error-after-deploying-to-store-windows-10

You also might want to follow the instructions here to see specifically what error the deployment process is getting:

https://msdn.microsoft.com/en-us/library/windows/desktop/hh973484(v=vs.85).aspx

**Comment by jimshalo10** [comment]
I am using Visual Studio 2015 Update 3 Community, Windows 10 Insider build 14361, and recently installed the official Monogame 3.51 from NuGet via package installer.
When I tried to make a Windows 10 UWP Monogame Project template I got an error 
"Microsoft.VisualStudio.WinRT.TemplateWizards.ApplicationInsights.Wizard" not found.
Not surprising, its not supported, not in list see http://whatdll.com/assembly/Microsoft.VisualStudio.WinRT.TemplateWizards.dll.html
This code removed from MonoGame 3.51 WindowsUniversal.vstemplate for vs 2015 Update 3 

 <WizardExtension>
    <Assembly>Microsoft.VisualStudio.WinRT.TemplateWizards, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</Assembly>
    <FullClassName>Microsoft.VisualStudio.WinRT.TemplateWizards.ApplicationInsights.Wizard</FullClassName>
  </WizardExtension>

-------------------------------------
Close Visual Studio 2015
[WindowsUniversal.zip](https://github.com/mono/MonoGame/files/346762/WindowsUniversal.zip)
This replaces the file at
 C:\%USERNAME%\Documents\Visual Studio 2015\Templates\ProjectTemplates\Visual C#\Monogame\WindowsUniversal.zip. 
Restart Visual Studio 2015 ->File ->New -> Project ->Visual C#-> Monogame then click 
"Monogame Windows 10 Universal Windows Project". 
Set the Name "GameWin10UWP", Click Ok.
Select Release,x86,Local,Right Click Manage NuGet packages, Install/Update .Net runtimes and restores NuGet packages into project
Deploy and Start without Debug. You will see a box

**Comment by tomspilman** [comment]
@jimshalo10 - You can see others [reporting the issue here](https://blogs.msdn.microsoft.com/visualstudio/2016/06/07/visual-studio-2015-update-3-rc/) to Microsoft.  We found that it is likely an issue with your VS2015 install... see [this](https://github.com/mono/MonoGame/issues/4435#issuecomment-172660324).

**Comment by cra0zy** [comment]
Gonna close this since it seems like the original issue was not on our side.

**Comment by MavundlaK** [comment]
Hi I'm new here, I have developed one MonoGame project for my practice, now I want to deploy it and I want to know if is possible to integrate my project SQL database?

**Comment by Jjagg** [comment]
@MavundlaK Sure you can use a SQL database. That's not related to MonoGame, so you can just use it like you would for any other project.

**Comment by MavundlaK** [comment]
@Jjagg thank you! now I want to deploy it so that it can visible online
