### ISSUE TITLE
UWP SoundEffects are only played on the left speaker

### ISSUE THREAD

**Issue by cra0zy** [MonoGame/MonoGame#5054]
Title says it all, it's very easy to notice if wearing headphones. I think that this might affect other XAudio platforms as well, didn't really test it.

**Comment by tomspilman** [comment]
It must be an issue in either `UpdateOutputMatrix` or `CalculatePanMatrix`:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffectInstance.XAudio.cs#L241

**Comment by cra0zy** [comment]
SoundEffectInstance is played on both... wow this was unexpected... tho it may be heard higher on the left one.

**Comment by tomspilman** [comment]
> SoundEffectInstance is played on both... wow this was unexpected

So are you saying that it wasn't only playing sounds on the left speaker?


> tho it is heard a bit higher on the left one.

I suggest verifying that it still is louder on the left by flipping your headphones around.  If it is still louder on the left with your headphones on backwards... it is your ears and not the sound effect system at fault.

I do this all the time to make sure i'm not fooling myself. :)

**Comment by cra0zy** [comment]
> So are you saying that it wasn't only playing sounds on the left speaker?

SoundEffect is playing only on the left, SoundEffectInstance is playing on the both.

**Comment by tomspilman** [comment]
> SoundEffect is playing only on the left, SoundEffectInstance is playing on both.

Got it.

Sounds like a failure to either get the right instance from the pool or properly resetting the instance before it is used.

**Comment by vcrobe** [comment]
All my sound files are stereo and have the same format _.ogg_.

In my case almost all sounds are played on the left speaker only but some sounds are played stereo.

**Comment by tomspilman** [comment]
So I think this is a bug in how our panning code is done here:

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffectInstance.XAudio.cs#L265

If we change that panning code to match what I did for MonoGame on XB1:

 https://gist.github.com/tomspilman/9464d6646c9dbe059f6c2e516a18df7e

I suspect this may fix the issue and be more correct in the process.  This cpp code is based on my porting of the MonoGame C# code and from the sound code in DirectXTK.

**Comment by leeadkins** [comment]
This seems simple enough for me to jump in on, but before I submit a PR, I just want to double check that this is what you had in mind:

https://github.com/leeadkins/MonoGame/commit/c5a9acc709bc4e19856b59523a8d5493f3bd4083

I've tested this on my own sample project with both mono (which already worked) and stereo (which I verified were broken first) source audio files, and it does fix the issue as you predicted.

The biggest caveat is it seems that this would only pan the first two speakers in any setup[0] - but will do so for mono or stereo, whereas the old method would pan only mono, but would do it across all left/right speakers in any multichannel setup.

Is that okay, or should we attempt a merger of the two so we can populate the 16 element array that would be necessary[1] to handle achieve both?

[0] Granted, I'm not familiar enough with XAudio so that assumption could easily be wrong.

[1] From here: https://msdn.microsoft.com/en-us/library/windows/desktop/hh405043(v=vs.85).aspx
> The minimum size of the output matrix is the number of channels in the source voice times the number of channels in the output voice. In this case an eight element array will handle a mono voice outputting to any output format up to 7.1 surround sound.

**Comment by tomspilman** [comment]
>  and it does fix the issue as you predicted.

Good!

> that this would only pan the first two speakers in any setup[0] - but will do so for mono or stereo,

Well for sure whatever we do we want to continue to support stereo panning.


> should we attempt a merger of the two so we can populate the 16 element array that would be necessary[1] to handle achieve both?

We can try...  what I don't understand is what is "correct" in this case.  How do we handle the LFE ... do we ever pan values to it?  Do we pan to rear right/left with the same volume level as front?  When panning right/left what happens with the center speaker?

This API sort of leaves it up to us to decide what should happen.  I just don't know what it should be.

Could be some experimenting with a 7.1 speaker setup and XNA could let someone listen closely and figure it out.  Or maybe there is some standard we should be following?

Any audio experts out there?

**Comment by tomspilman** [comment]
Looking at FMOD might provide some hints:

> This mode is for 7.1 speaker arrangements that have a left/right/center/surround left/surround right/rear left/rear right and a subwoofer speaker.
> - Mono sounds default to the center speaker. They can be panned with Channel::setPan.
> - Stereo sounds default to the left sound channel played on the front left, and the right sound channel played on the front right. 
> - They can be cross faded with Channel::setPan.
> - Multichannel sounds default to all of their sound channels being played on each speaker in order of input. 
> - Mix behavior for multichannel sounds can be set with Channel::setPanMatrix.
> - Channel::setPanLevels works and every parameter is used to set the balance of a sound in any speaker.

https://www.fmod.org/docs/content/generated/FMOD_SPEAKERMODE.html

**Comment by MichaelDePiazzi** [comment]
I have just been looking into some audio issues in the Windows DirectX build, and I am fairly confident now that `CalculatePanMatrix` is wrong.

I think the reason that stereo sounds only play on the left speaker is because the matrix calculations are assuming the input source is mono. According to the docs on [`SetOutputMatrix`](https://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.ixaudio2voice.ixaudio2voice.setoutputmatrix(v=vs.85).aspx), the level matrix needs to be an array of size SourceChannels * DestinationChannels. So if you have a stereo sample playing on stereo speakers, I think the matrix is meant to look like this (without any panning):
```c#
panMatrix[0] = 1f; // Left input / Left output
panMatrix[1] = 0f; // Right input / Left output
panMatrix[2] = 0f; // Left input / Right output
panMatrix[3] = 1f; // Right input / Right output
```
Another issue is that the `_panMatrix` array used in this class only has a size of 8. This means that if SourceChannels * DestinationChannels is greater than 8 (e.g. stereo source / 2 channels * 7.1 output / 8 channels = 16), there'll be a buffer overflow.

Yet another problem is that the current left/right volume calculation is wrong:
```c#
var lVal = (1.0f - pan) * scale;
var rVal = (1.0f + pan) * scale;
```
This can give volume levels up to 2 when fully panned (e.g. `pan` of `-1` results in `lVal` being `2`).
It should be more like this to give correct results between 0 and 1:
```c#
var lVal = Math.Min(1.0f - pan, 1f) * scale;
var rVal = Math.Min(1.0f + pan, 1f) * scale;
```
In regards to how exactly mapping needs to be performed when more than 2 speakers are involved, I have no clue how this should actually be done. All I know is that the current code gives results that are way too loud (compared to XNA) when mapping a mono source to my headphones configured as 7.1. But if I set `SoundEffect.Speakers = Speakers.Stereo` in this case (effectively meaning it's split between only the 2 front speakers), then the volume levels seem the same as XNA.

**Comment by tomspilman** [comment]
> In regards to how exactly mapping needs to be performed when more than 2 speakers are involved, I have no clue how this should actually be done

That is where I am at on this issue as well.  We need someone to fix this that either knows how this should work or is willing to make the effort to figure it out.

**Comment by MichaelDePiazzi** [comment]
Ok, I spent some time investigating this and I'm fairly confident I know what needs to be done.

I was able to monitor how XNA was outputting audio when there's more than 2 speakers using [NAudio](https://github.com/naudio/NAudio) (it gives you access to the meter information of each individual channel). I can now confirm that in these cases, XNA only ever outputs to the **front left/right** speakers (i.e. channels 0 and 1). It never outputs to any other speakers.

Based on my observations, here's how XNA is performing the mixing:

Sample Type | Panning | Left Speaker Mix | Right Speaker Mix
--- | --- | --- | ---
Mono | Centre (0.0) | 100% | 100%
Mono | Full Left (-1.0) | 100% | 0%
Mono | Full Right (1.0) | 0% | 100%
Stereo | Centre (0.0) | L:100%, R:0% | L:0%, R:100%
Stereo | Full Left (-1.0) | L:50%, R:50% | L:0%, R:0%
Stereo | Full Right (1.0) | L:0%, R:0% | L:50%, R:50%

I was not able to test what XNA does when there's only 1 speaker (mono) as this was not even an option I had in Windows (maybe my drivers don't support it?). But my assumption would be that you'd simply halve the combined results of the stereo output. i.e.

Sample Type | Panning | Mono Speaker Mix
--- | --- | ---
Mono | Centre (0.0) | 100%
Mono | Full Left (-1.0) | 50%
Mono | Full Right (1.0) | 50%
Stereo | Centre (0.0) | L:50%, R:50%
Stereo | Full Left (-1.0) | L:25%, R:25%
Stereo | Full Right (1.0) | L:25%, R:25%

Based on these results, I'll get to work on a PR which does exactly this. Hopefully I can get it submitted within the next day or two.

**Comment by KonajuGames** [comment]
There is no need to support one speaker output as there are no sound cards that support a single output.  Stereo output is the minimum, with mono input being played equally on left and right speakers.

This would give further support to an `AudioProfile` (similar to `GraphicsProfile`, to be implemented later) where the the lowest profile ("Reach" equivalent) would be XNA compatibility and a Surround ("HiDef" equivalent) profile would support 7.1, etc.

**Comment by MichaelDePiazzi** [comment]
> There is no need to support one speaker output as there are no sound cards that support a single output.

Cool, no problem. That makes it simpler.

**Comment by tomspilman** [comment]
> I was able to monitor how XNA was outputting audio when there's more than 2 speakers 

Very cool...  great job @MichaelDePiazzi !

> It never outputs to any other speakers.

 So you didn't see anything to the rear speakers or sub?  Would you be able to do the same test using XACT as the sound source?

**Comment by MichaelDePiazzi** [comment]
> So you didn't see anything to the rear speakers or sub?

No, not when playing mono or stereo `SoundEffect`'s. It always gets played on the front left/right speakers.

> Would you be able to do the same test using XACT as the sound source?

I've never used XACT... How would I test this? Keep in mind that I don't have the XNA Game Studio installed, so someone would need to provide XNB files for me if they're required to do this...

**Comment by MichaelDePiazzi** [comment]
I knocked this off much quicker than I thought I would. I've just submitted PR #5440 which fixes these issues.
