### ISSUE TITLE
Single NuGet package

### ISSUE THREAD

**Issue by aloisdeniel** [MonoGame/MonoGame#5113]
I was wondering why there's multiple NuGet packages instead of a single one that would take advantage of the target project to reference the appropriate dlls ?

**Comment by tomspilman** [comment]
I thought multiple packages was the way things are done and is what others had recommended to us.

@DDReaper ?

**Comment by aloisdeniel** [comment]
You could have only have one `Monogame.Framework` package with multiple output. At install, NuGet will reference only the dll/tools/... that stands in the target framework folder.

Several examples : 

- (MvvmCross)[https://github.com/MvvmCross/MvvmCross/blob/4.0/nuspec/MvvmCross.Platform.nuspec]
- (Refit)[https://github.com/paulcbetts/refit/blob/c906f26b47c0df3a9326590ba07abc8551ad215d/Refit/refit.nuspec]
- (Akavache)[https://github.com/akavache/Akavache/blob/53836cb84d8765fdf395d193e1c42d30c714955a/Akavache/akavache.nuspec]
- (Xamarin.Plugins)[https://github.com/jamesmontemagno/Xamarin.Plugins]

There's also a trick called `bait-and-switch` that allows you to have platform specific feature called from PCL by have the same signatures and exchange DLL : (more info)[http://log.paulbetts.org/the-bait-and-switch-pcl-trick/]

**Comment by dellis1972** [comment]
Some of the platforms like Xamarin.Mac used the same framework as windows. But had a different assembly. In which case how do you decide which assembly to use. This may well have changed recently but when the nugets were put together that was an issue. 

Also if its all in one package how to developers choose between using DirectX or OpenGL on windows? they are different assemblies but for the same framework. 
There could be a setting in the project for that but it complicated matters. 

At the time is was easier to just provide separate nuget packages. The developer just picks the one they want.

**Comment by dellis1972** [comment]
Looks like Xamarin.Mac has "Xamarin.Mac20" platform target now. But the question about DX vs GL still is a problem.

**Comment by aloisdeniel** [comment]
Why not to add a `Monogame.Framework.Core` (with common features) and two packages `Monogame.Framework.OpenGL`(compatible with Windows, Mac, iOS, Android, ...) and `Monogame.Framework.DX` (only compatible with Windows, Windows Phone) ?

**Comment by DDReaper** [comment]
As @tomspilman and others have pointed out, they are separated so that developers can pick and choose the platforms / graphics they can use.
Initially we had just one Nuget but it proved problamatic for dx/opengl devs.

As to your point @aloisdeniel on a .Core package, I've tried twice now to create a multi-platform core package containing the true multiplatform code (which also helped supporting framework devs) but it was never merged and I abandoned the work.

**Comment by Jjagg** [comment]
> Why not to add a Monogame.Framework.Core

It would be nice to split this up for testing as well.

> but it was never merged and I abandoned the work.

I found the PR and @tomspilman mentioned he wanted to wait for the 3.5 release, maybe we can get this discussion running again. It doesn't look like it would take a lot of work to get the PR in order. Not a lot of classes that can be in MonoGame.Framework.Core have been added and filtering all classes was most of the work, right?

**Comment by DDReaper** [comment]
Mostly it was re writing the build scripts to create a new project and have the existing projects reference it

**Comment by hach-que** [comment]
The issue here is that NuGet does not distinguish between native platforms in it's package structure - there is no mechanism in NuGet that lets you tell the different between "Mono on Linux" and "Mono on Mac".  Under NuGet, it's just "Mono".

The expectation is that people will alternate their P/Invokes based on determining the platform at runtime, and while that's suitable for probably 99% of projects, it's not suitable for a game engine.

This is specifically one of the reasons why Protobuild's package management is a thing; refer to https://protobuild.readthedocs.io/en/latest/package_management_nuget.html for a warning on all of the issues you're going to run into trying to do native cross-platform development in NuGet.
