### ISSUE TITLE
SetData/GetData<T>

### ISSUE THREAD

**Issue by Jjagg** [MonoGame/MonoGame#5119]
When starting to fix #1455 I thought it might be a good idea to do parameter validation for GetData and SetData in a seperate method so we do the same checks in both, don't have duplicate code here and have a better overview of it. Maybe even abstract some of the checks up to Texture itself since this code can be shared for the most part and it'll make the checks consistent for all Texture types. 

I just realized the same methods exist for Vertex/IndexBuffers, not sure if we should share all around or just do textures. Thoughts on this?

Also, there are cases the checks miss because sizeof(T) was is always expected to be equal to 4 (which is expected to be the size of the format, but that isn't always the case either) and the size of T is not explicitly checked while in XNA it is. I'm happy to fix all this once we decide on the above paragraphs.

**Comment by tomspilman** [comment]
> it might be a good idea to do parameter validation for GetData and SetData in a seperate method so we do the same checks in both

We generally avoid this because it sometimes forces us to make parameter validation that doesn't exactly match XNA behavior or limits our ability to provide helpful messages.  Also we hate introducing the extra function call.

That said if SetData/GetData tests are really identical it could be something to consider.  Generally very few SetData/GetData calls are done per-frame... usually much less than draw calls, setting effect parameters, etc....  so an extra non-virtual function call would be a very small penalty if we want to reduce our code size a bit.

> not sure if we should share all around 

I'm not sure if that would be really beneficial at this time.  I expect the tests and messages are quite different.

It is unfortunate XNA wasn't designed with a base `GraphicsBuffer` type that could share some of this common stuff.  DirectX 10/11/12 all consider index/vertex/texture/constant "buffers" and share set/get data methods....  but XNA was initially designed around DX9 where this wasn't true.

**Comment by Jjagg** [comment]
> Generally very few SetData/GetData calls are done per-frame...

I thought about this too. These functions are pretty slow themselves, so I think the extra overhead is negligible.

> I'm not sure if that would be really beneficial at this time. I expect the tests and messages are quite different.

Yeah, you're right... doesn't really make sense the way MG is set up. Would be weird to have some internal static method somewhere.

> It is unfortunate XNA wasn't designed with a base GraphicsBuffer type that could share some of this common stuff.

Maybe we can do something like this internally. I'll think about this for a bit. Not sure how well this maps to DX/OpenGL though and it seems like a lot of work for little gain. Still it would be nice to clean up all the duplication.

**Comment by tomspilman** [comment]
> These functions are pretty slow themselves, so I think the extra overhead is negligible.

Very true.

> Maybe we can do something like this internally.

Probably isn't worth it with the current XNA based design of the API.  I think this is an idea best kept for the future API changes to support DX12/Vulkan/Metal/etc.
