### ISSUE TITLE
No portability guidelines for PS4

### ISSUE THREAD

**Issue by Kleenox** [MonoGame/MonoGame#5162]
I haven't found a list of what namespaces are supported when using Monogame in PS4. I can't test my game in PS4 before we get the dev kit but I would like if possible to prepare for this, and find out which one of the System.\* facilities are available, I'm sure others are in the same predicament.

I know about the portable class library, but it seems to be a lot of trouble and I don't mind having different projects, all I really need to know is which libraries are available on PS4 to be prepared, my understanding is this involves a Xamarin compiler, true? Is this available anywhere? I didn't find any information about this in their public docs.

Also does this mean I have to buy Xamarin to use Monogame in the PS4?

**Comment by mrhelmut** [comment]
You don't have to buy Xamarin, but answering your other questions will require you to get in the private PS4 repository, because NDA and such.

Search for the MonoGame and Mono threads on the Sony devnet, and ask in both of these threads to have access to the private repositories. You don't need to own a devkit for that, but you will need to be a registered devnet user.

Alternatively you can try converting your project to the Cross-Platform project type and try running it on MacOS / Linux. Supported namespaces are quite the same and it will help you to know if your C# is nicely portable.
