### ISSUE TITLE
Can't create a Continuous Integration environment due to installer issues.

### ISSUE THREAD

**Issue by azchohfi** [MonoGame/MonoGame#5171]
There is no simple way, at least not one that I am aware of, to create a CI build for a UWP MonoGame project, for example.
The content pipeline requires a dependency to:
`<Import Project="$(MSBuildExtensionsPath)\MonoGame\v3.0\MonoGame.Content.Builder.targets" />`
which is fine on a developer machine, but the main issue is that MonoGame Installer(http://www.monogame.net/releases/v3.5.1/MonoGameSetup.exe) requires administrative credentials, and that's not allowed on a build machine that you don't have admin credentials, like VSTS's Hosted Build (https://www.visualstudio.com/en-us/docs/build/admin/agents/hosted-pool).

There should be a way to easily install all MonoGame Content Pipeline dependencies locally, or something else.

It's really bad to not be able to use this kind of setup.

I already apologize if there is a way that I'm not aware of, but I tried several ways to do this and got into a dead end.

Maybe we can have a "portable" ContentPipeline, maybe like a zipfile with all dependencies to MGCB.exe distributed as easily as we have the MonoGameSetup.exe, on a static URL at monogame.net website.
Any ideas on how to provide such a setup would be appreciated.

**Comment by tomspilman** [comment]
I guess the first question is why we need admin credentials for the installer.  I think it is because we install to the `Program Files` folder and put stuff into the `MSBuild` install folder too.

Is there something better we could be doing here?  @KonajuGames @dellis1972 ?


> Maybe we can have a "portable" ContentPipeline

NuGet packages for the content pipeline tools has come up a lot:

 - [NuGet Packages for the Pipeline](https://github.com/MonoGame/MonoGame/issues/4688)
 - [Add NuGets MonoGame.Framework.Content.Pipeline?](https://github.com/MonoGame/MonoGame/issues/4735)
 - [Getting the Content Pipeline through NuGet](https://github.com/MonoGame/MonoGame/pull/4332)
 - [Include Content Pipeline Tool in NuGet Packages](https://github.com/MonoGame/MonoGame/issues/3985)

@dellis1972 @DDReaper ...  we need to resolve this one once and for all.

**Comment by dellis1972** [comment]
We can do a Nuget for the content pipeline but there are issues. The main one being how to deal with Mac/Linux.. MGCB.exe and Pipeline.exe are all find on windows, but those same .exe files don't work on Mac/Linux, so we would need separate packages. I also wouldn't want to switch the default templates over to using the Nuget because who wants to be downloading all that stuff for every project (on of Nuget's downfalls in my option). That said having it available for people to use would be a good idea. 

The other downside is the .props/.targets import paths would be incompatible with the current templates. So you'd have to always use the nugets, or add some msbuild conditionals  so that locally you use the installation and no the build server you use Nuget.

I do know that CocosSharp has a nuget package for the Content Pipeline. They have separate packages for windows/mac. [1] and I'm not sure how up to date it is.

[1] http://www.nuget.org/packages/CocosSharp.ContentBuild.Windows/

**Comment by hach-que** [comment]
Well an alternative to NuGet in this scenario is Protobuild's package management - it does correctly pull down the right platform-specific binaries for your host platform when needed, but we'd need to ship compiled Protobuild packages for MonoGame.

Then you could either add MonoGame as a dependency of your Protobuild project, or if you're just using plain .NET solution files, you could install it with `Protobuild.exe --install https://protobuild.org/MonoGame/MonoGame` and run the content pipeline with `Protobuild.exe --execute MGCB <args>`.

**Comment by harry-cpp** [comment]
As both installers and protobuild have been killed, this is no longer an issue.
