### ISSUE TITLE
Flickering. DrawUserIndexedPrimitives.

### ISSUE THREAD

**Issue by krasnotsvetov** [MonoGame/MonoGame#5294]
Hello!

I have some troubles with DrawUserIndexedPrimitives method.

Here you can see an example of flickering. (DirectX)
https://github.com/krasnotsvetov/MonogameRenderBugExample

If I want to set offset in vertex declaration data and indices in DrawUserIndexedPrimitives i will have flickering of mesh which this method will draw.

How can i fix it?
Why can it happend?

P.S: here is video:
https://www.youtube.com/watch?v=2CBfgcWhiuw

**Comment by krasnotsvetov** [comment]
Here i post a thoughts about it(in 3rd post)
http://community.monogame.net/t/issue-with-flickering-drawuserindexedprimitives/8385

**Comment by Jjagg** [comment]
Your data does not match up. If you don't pass all vertices that the indices point to, you'll get the flickering issue. The problem is, if you pass a vertex offset your indices will be wrong as an index of 0 will point to the vertex at vertices[vertexOffset].

The same thing happens in XNA. This is not an issue with MonoGame you're just not using the API it's meant to be used. If MG would want to warn the user it'd have to check every index in the buffer which is obviously not a good idea.

**Comment by tomspilman** [comment]
@Jjagg - Maybe there is something we can do with the reference docs to make it more clear?

**Comment by Jjagg** [comment]
That's a good idea. I only found out by trying.
