### ISSUE TITLE
Regression in 2MGFX

### ISSUE THREAD

**Issue by Danthekilla** [MonoGame/MonoGame#5315]
I think I have found a bug in 2MGFX.

I have a FXAA shader that compiles fine in the 3.5 version of 2MGFX but fails to compile with some strange errors in the latest version from the development branch.

I have attached the shader with a bat file that processes it both successfully with the old version and shows the new failure.

I have about 20 other effects being compiled with the latest 2MGFX correctly. The issue only effects this shader.

[Monogame 2MGFX Fail.zip](https://github.com/MonoGame/MonoGame/files/605595/Monogame.2MGFX.Fail.zip)

**Comment by Vodacek** [comment]
I am experiencing similar issue with my shader, current 2MGFX version don't like sampler2D as argument in function.

**Comment by Danthekilla** [comment]
I have also experienced that issue, it seems like there have been a few regressions in the latest branch then.

I have also found that Global Constant Arrays don't work. Something like this for instance will cause the shader to fail and return a single color across the entire mesh.

    const float gaussian[] =
    {
        0.0539909676,
        0.241970733,
        0.3989423,
        0.241970733,
        0.0539909676,
    };

I have also found that even when compiling a shader with the debug option it still performs variable trimming of unused variables.

And I have also found that the new 2MGFX no longer creates shader code that can be debugged on the GPU with the visual studio GPU debugger, it complains that the generated code was built with a unknown compiler.

**Comment by tomspilman** [comment]
> 2MGFX version don't like sampler2D as argument in function.

 @Vodacek - Please enter a new issue for that with an example of the problem.

**Comment by tomspilman** [comment]
> I have also found that Global Constant Arrays don't work.

Note that `const` in HLSL does not mean the same thing as in C++.  If you are looking to store a constant that are hard coded into the shader and cannot be changed from your game code use `static`.


> debug option it still performs variable trimming of unused variables.

This is just how the HLSL compiler works... I cannot keep it from removing unused variables.

We have discussed faking it, but it seems like the wrong thing to spend our time on... adding fake variables that are unused by your program.

> it complains that the generated code was built with a unknown compiler.

Which version of Visual Studio?  It is possible they stopped supporting the DX11 shader compiler we've been using for several years now.

**Comment by Danthekilla** [comment]
> Note that const in HLSL does not mean the same thing as in C++. If you are looking to store a constant that are hard coded into the shader and cannot be changed from your game code use static.

The actual issue I am having with arrays is that none of them seem to work for me at all. Take this small simple blur pixel shader for instance. Whenever I use the array declared on line 6 (or the one on line 12) the shader would return a solid color across the entire quad. I have had to remove arrays from all my XNA shaders. (quite a pain for my bloom as that filled a n by n array in c# based on runtime settings, so now I have to pack it into a texture and do texture lookups to get the data into the pixel shader.)

    #include "HelperMacros.fxh"
    
    DECLARE_TEXTURE(SBTex, 0);
    
    //float gWeights3x3[3][3] = {
    //        { 0.0625, 0.1250, 0.0625 },
    //        { 0.1250, 0.2500, 0.1250 },
    //        { 0.0625, 0.1250, 0.0625 }
    //    };
    
    //static float gWeights3x3[3][3] = {
    //        { 0.0625, 0.1250, 0.0625 },
    //        { 0.1250, 0.2500, 0.1250 },
    //        { 0.0625, 0.1250, 0.0625 }
    //    };
    
    float SizeX = 1280;
    float SizeY = 720;
    
    float Multi = 1;
    float Brightness = 1;
    
    float4 PixelShaderFunction(float4 in_Position : SV_Position, float4 in_Color : COLOR0, float2 uv : TEXCOORD0) : COLOR0
    {
    	float OffX = (1.0 / SizeX) * Multi;
    	float OffY = (1.0 / SizeY) * Multi;
    
    	float4 Color = (float4) 0;
    	
    	//This was a loop in DX9 XNA, returned a single pixel until I removed the array on line 6
    
    	Color += SAMPLE_TEXTURE(SBTex, float2(uv.x + (-1 * OffX), uv.y + (-1 * OffY))) * 0.0625;
    	Color += SAMPLE_TEXTURE(SBTex, float2(uv.x + (-1 * OffX), uv.y + (0 * OffY))) * 0.125;
    	Color += SAMPLE_TEXTURE(SBTex, float2(uv.x + (-1 * OffX), uv.y + (1 * OffY))) * 0.0625;
    	Color += SAMPLE_TEXTURE(SBTex, float2(uv.x + (0 * OffX), uv.y + (-1 * OffY))) * 0.125;
    	Color += SAMPLE_TEXTURE(SBTex, float2(uv.x + (0 * OffX), uv.y + (0 * OffY))) * 0.25;
    	Color += SAMPLE_TEXTURE(SBTex, float2(uv.x + (0 * OffX), uv.y + (1 * OffY))) * 0.125;
    	Color += SAMPLE_TEXTURE(SBTex, float2(uv.x + (1 * OffX), uv.y + (-1 * OffY))) * 0.0625;
    	Color += SAMPLE_TEXTURE(SBTex, float2(uv.x + (1 * OffX), uv.y + (0 * OffY))) * 0.125;
    	Color += SAMPLE_TEXTURE(SBTex, float2(uv.x + (1 * OffX), uv.y + (1 * OffY))) * 0.0625;
    	
    	//Had to unroll because of array lookup issue
    	//This is because monogame doesnt support array lookup?
    
    	Color = Color * Brightness * in_Color;
    	Color.a = 1;
    	return Color;
    }
    
    technique Technique1
    {
    	pass Pass1
    	{
    		PIXEL91(PixelShaderFunction)
    	}
    }



> This is just how the HLSL compiler works... I cannot keep it from removing unused variables.

I had assumed this was at the HLSL compiler level, I just noticed that XNA doesn't do this as I just ported about 15 shaders over the last few days.

> Which version of Visual Studio? It is possible they stopped supporting the DX11 shader compiler we've been using for several years now.

We are using visual studio 2015 and I have tried it in 2017 (VS15) also.

**Comment by Danthekilla** [comment]
Here is another instance of global arrays not working

http://community.monogame.net/t/global-constant-arrays-in-shaders-dont-work/7878

**Comment by Danthekilla** [comment]
@tomspilman 

Do you happen to know why my FXAA shader is failing from above? Or any tips on diagnosing it?

**Comment by Jjagg** [comment]
The issue is with the parser that gets the sampler state info and technique declarations. I typed out an explanation on my laptop but had some trouble with my internet connection (on mobile atm) so I'll post it here tomorrow. 
Fixing the issue is simple so I think I can squeeze that in my schedule tomorrow :)

**Comment by Danthekilla** [comment]
Awesome news.

I look forward to tomorrow :)

Thanks heaps!

**Comment by Jjagg** [comment]
This is caused by a bug in the parser that gets the FX specific data from the shader. The parser just tries to read either a sampler declaration, a technique declaration or any 1 word (any characters up until the next whitespace, called 'Code' in the parser) until it parsed the entire file. It then stores technique and sampler info so it can write that out into the xnb later. The parser only looks at the first next token to decide which one of those three things it's going to read, so when it sees 'sampler2D' it will attempt to read a sampler declaration. Which is defined [here](https://github.com/MonoGame/MonoGame/blob/develop/Tools/2MGFX/MGFX.tpg#L413) as 
`Sampler_Declaration -> Sampler Identifier Sampler_Register_Expression* Sampler_Declaration_States? Semicolon`
Since this expects a semicolon at the end the parser will crash.
A workaround would be to parse 
`Sampler_Declaration -> Sampler Identifier Sampler_Register_Expression* Sampler_Declaration_States? (Semicolon|Comma)` and skip creating and storing SamplerStateInfo if a comma was parsed since that means the sampler is a parameter in a function. Another way to do it is to parse everything in between brackets seperately, i.e. instead of parsing samplers, techniques or Code at the top level parse samplers, techniques, \(Code*\) and then Code. Since none of the stuff we're interested in can be in between brackets. Note that comments are stripped by the preprocessor before the parsing.

Oh, there's a related bug here. Samplers cannot be declared and assigned on a single line inside a function as a local variable. I think the best thing to do is to parse code between brackets **and** square brackets seperately. There's no way to declare techniques and samplers inside (square) brackets, right?

**Comment by Jjagg** [comment]
Actually, on second thought I prefer the allowing a comma at the end of `Sampler_Declaration` for two reasons. 

- The parser should be as simple as possible to avoid crashes because it can't throw decent error messages.
- The precedence rules in the parser make it pick the longest matching token. This complicates things a lot because of the Code token. We want 'functionName(int arg)' to be matched as something like `Identifier OpenParen (FunctionArg (Comma FunctionArg)*)? CloseParen` but since Code matches 'functionName(int' and Identifier only matches 'functionName' the parser will pick Code. We can solve this by having a single token that matches `Identifier? OpenParen Identifier?` (including whitespace) so it matches the same length as Code, but have it declared before Code (for equal length matches we can choose precedence by order of definition). That fixes the *sampler as parameter* issue. However we cannot do the same for braces to fix the *sampler as local var issue* since that will ruin technique parsing because 'technique { pass' will be matched by this new token. There's probably a way around this too, but it makes the parser more complex, which means more chance of crashes which means not very helpful error messages for the user.

I'm working on this now, but it's a bit harder than I thought.
