### ISSUE TITLE
WindowsDX fullscreen debug causes soft-lock

### ISSUE THREAD

**Issue by GameKyuubi** [MonoGame/MonoGame#5342]
Using:
- NuGet WindowsDX package 3.6.0.1184 OR Dev installer from downloads page
- Visual Studio 2015
- Windows 10 Home Insider Preview

Steps to recreate:
- Create new project
- Add Monogame WindowsDX package 3.6.0.1184
- Add this to Initialize:
```
    protected override void Initialize()
    {
      // TODO: Add your initialization logic here
      graphics.PreferredBackBufferWidth = 1920;
      graphics.PreferredBackBufferHeight = 1080;
      graphics.ToggleFullScreen();
      base.Initialize();
    }
```
- Set a breakpoint anywhere in the Update method
- Run project

Problem:
Game launches, breakpoint is hit, but game window gets stuck in the foreground and it's very hard to close it.  Alt tab, windows key, even ctrl+alt+escape for task manager doesn't work.  The only way I've gotten around it is by using the multiple desktop function of Insider Preview to open task manager on another desktop and then killing vshost32.exe.  I've done some experimentation and it seems like it's not actually crashed, it just doesn't yield foreground control to Visual Studio.  I can drag VS to another desktop and it functions normally, properly stopped at the breakpoint I set.

**Comment by Jjagg** [comment]
Unfortunately, this is not something MG can do anything about. When going full screen the DXGI SwapChain grabs control of the screen and doesn't release it for the VS debugger...

This issue was created because of the discussion in http://community.monogame.net/t/cant-debug-in-fullscreen-after-upgrade-to-dev-branch/8468/15
The conclusion there was that you can bypass the problem either by setting GraphicsDeviceManager.HardwareModeSwitch to false (it's true by default; setting to false makes fullscreen just set the window to the display resolution and not draw the border) or debug on a second monitor. Remote debugging can also work if you don't have a second monitor.

The [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/bb205075(v=vs.85).aspx#Debugging) on DXGI says something about this too:

> A DXGI swap chain relinquishes full-screen mode only when absolutely necessary. This means that you can debug a full-screen application using multiple monitors, as long as the debug window doesn't overlap the swap chain's target window.

So I guess this can be closed.

**Comment by KonajuGames** [comment]
This is the behaviour of full-screen exclusive mode on Windows. It always has been.  There is nothing MonoGame can do about this.  The comments by @Jjagg above contain all the suggestions we can offer in regard to this.
