### ISSUE TITLE
SDL2 broken on MacOS Sierra

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#5346]
Hello,

Since the dependencies for SDL 2.0.5 have been updated, MonoGame doesn't work anymore on MacOS Sierra (but does on prior versions).

I rebuilt SDL from scratch and it works, so I believe the build process of the dylib was missing something.

I'm going to push an update to the dependencies.

**Comment by cra0zy** [comment]
The one I added came from: https://www.libsdl.org/download-2.0.php

**Comment by tomspilman** [comment]
Weird... so the official SDL lib for Mac doesn't work?

**Comment by mrhelmut** [comment]
Weird, indeed. The official doesn't work on Sierra but rebuilding it (or using the one from the FNA binaries) works on Sierra.

I believe that it is related to how libs are bundled on MacOS, the official dmg is meant to go in the system libraries and includes headers etc, while the dylib is a standalone. I can't be sure but I believe you can't simply grab a lib from a system bundle.

**Comment by gillesboisson** [comment]
Hi guys, I'm not sure I have the same issue here, My xamarin.mac project and crossplatform opengl project crash since I update to Sierra. I tried to make a new xamarin.mac classic solution from scratch, it add the libSDL2-2.0.0.dylib to bin directory when I compile but throw dllnotfound  exception libSDL2-2.0.0.dylib when it execute.

**Comment by mrhelmut** [comment]
DllNotFound is another problem. Are you on the latest develop branch? Templates should have changed a bit to better handle this.
But if you're on Sierra, you'll run into this problem once the dll path is resolved.

**Comment by Jjagg** [comment]
Posting this in case you didn't read it @mrhelmut. 
In the [SDL wiki](https://wiki.libsdl.org/Installation) it says:     

> SDL on Unix should only link against the C runtime (glibc). Every thing else it needs will be dynamically loaded at runtime: X11, ALSA, d-bus, etc. This means it is possible to build an SDL that has support for all sorts of targets built in, and it will examine the system at runtime to decide what should be used (for example, if Xlib isn't available, it might try to load Wayland support, etc). **In that respect, if you plan to ship the SDL binary that you build, it is to your benefit to make sure your system has development headers for as many targets as possible, regardless of what you plan to personally use, so your final library is as robust as possible.** See docs/README-linux.md for more details. 

Something else on that page that's important and maybe we should put in the docs:

> When shipping a Linux game on Steam, do not ship a build of SDL with your game. Link against SDL as normal, and expect it to be available on the player's system. This allows Valve to make fixes and improvements to their SDL and those fixes to flow on to your game.
We are obsessive about SDL2 having a backwards-compatible ABI. Whether you build your game using the Steam Runtime SDK or just about any old copy of SDL2, it should work with the one that ships with Steam.
In fact, it's not a bad idea to just copy the SDL build out of the Steam Runtime if you plan to ship a Linux game for non-Steam platforms, too, since you know it's definitely built sanely.

**Comment by mrhelmut** [comment]
Thanks! I'm not sure how to interpret this, because the dll which fails comes from a "sanely built" runtime (and fails on a Steam game)... but I may be wrong somewhere.

> This allows Valve to make fixes and improvements to their SDL and those fixes to flow on to your game.

Steam Linux... On one hand they recommend you to ship all the dependencies with your game, and on the other hand, SDL don't recommend it. With Slouken working at Valve, this is puzzling.
Also, it's not always a version with the fixes you would expect (I remember a couple bugs related to this, notably the problems SDL had with windowing on Linux, and gamepads).

It's good to have this wiki info though, I'll link to it when I'll get back on packaging documentation.

Meanwhile, I've been encountering players unable to run our game on Ubuntu 16.04 since the SDL 2.0.5 update... May not related to this issue, but I'm investigating.
