### ISSUE TITLE
Game Events (InitializationEvent, LoadContentEvent, etc)

### ISSUE THREAD

**Issue by GeoDoX** [MonoGame/MonoGame#5353]
There should be pre, execution, and post events for things in the Game class.

base.Initialize and other overridden methods shouldn't rely on being executed last, and could benefit by being called one after another wherever the first get's called, instead of being chained.

A use case for an InitializationEvent in the pre execution state would be as follows:
Initializing classes that are required before Initialization gets called. I realize this is a broad use case, but it covers a lot of different scenarios.

**Comment by DDReaper** [comment]
Nick Gravelyn wrote an excellent article back in 2008 called "life of an xna game", which shockingly has always been pointed to but never repeated 💃 even in the XNA docs.  Which details the full XNA execution order.
I've contacted Nick to see if he still has it, else I'll redo it myself.

From memory it's:

- Constructor
- Initialize
- LoadContent
- GameServices (initialize, Update)
- Game Components (initialize, Load Content, Update)
- Update
- Draw

There are also several timesteps to manage between elapsed and fixed timings (amongst others)

**Comment by KonajuGames** [comment]
There are already protected methods BeginRun(), EndRun() and BeginDraw(), EndDraw() from XNA to do something before and after the run loop and each draw.

The problem I have come across with systems trying to specify before and after events or similar is that it starts bad and gets worse as it evolves.  In a previous engine I worked with, they had draw layers.  These layers were named PreDraw, Draw, and PostDraw.  Then someone wanted something after PostDraw, so we added Final.  Then someone wanted something after that because they had something they wanted drawn after the things that were drawn in the Final layer, so we added a ReallyFinal layer.  Then someone suggested a ReallyReallyFinal layer.  You can see where this goes.

The calls to `base.Initialize()` and so on don't need to be called last.  The whole point is that they are called where you want them to be executed within the override method.  The call to `base.Initialize()` sets up the `GraphicsDevice` based on parameters set in the constructor or before the call to `base.Initialize()`, which itself calls the initialize on components that have been added prior and calls `LoadContent()`.  I don't think there is a need to add any additional pre or post protected virtual methods.

**Comment by DDReaper** [comment]
I've found in the past if you wanted to specifically order draw calls or layers, then you should include calls to your own functions to do it within Draw and Update.
Draw()
{
DrawLoop1();
DrawLoop2();
etc();
}

**Comment by theZMan** [comment]
This is pretty much what the Components system is for though right? You
make a GameComponent and/or a DrawableGameComponent and their Update and
Draw methods are called for you.

These components also have LoadContent, Initialize etc on them.

**Comment by GeoDoX** [comment]
@DDReaper
I was looking for the same article, seems like Nick changed up his site and lost the articles that was on it previously.

@KonajuGames
I read that those methods were used by monogame and that I they shouldn't be used. Good to know though.

@theZMan
I see why you recommended it but I was looking for a solution that gets called before the Game methods were. Your solution works for post Game methods.

I appreciate the help!
