### ISSUE TITLE
Mouse GetState() creates garbage.

### ISSUE THREAD

**Issue by willmotil** [MonoGame/MonoGame#5355]
As said calling GetState() creates garbage that is collected and i have no clue how or if it is possible to keep a live reference to it in order to prevent it from being collected.

Running in a near empty project at about 3500 fps it creates about 1 megabyte of garbage in a minute. 
Its quite annoying not because its a huge amount but because its a constant source of garbage that basically must be on. If you want to have mouse functionality in your game.

**Comment by theZMan** [comment]
Its all going to be Gen 0 garbage and won't even show up as a blip in your game. There were a couple of things in XNA games that did this too. It didn't stop any of us releasing on steam just fine.

If this is the only thing left generating garbage when you profile the memory once your game is finished then you have done an amazing job.

In other words.. don't worry about it until you can show its a problem.

>Running in a near empty project at about 3500 fps it creates about 1 megabyte of garbage in a minute.
Don't run your game at 3500fps ;-)

**Comment by KonajuGames** [comment]
You haven't stated which platform you running this on.  I'm going to assume you're using the SDL version as I can see where it is [allocating memory in a hidden way](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Input/Mouse.SDL.cs#L18).  `Enum.HasFlag()` is a convenience method, but has performance and memory implications that we should avoid, and it is easy to do so.  It does type checks to make sure the the enum types are compatible, and it boxes each enum value to a UInt64.

This is easily avoided by replacing

    if (winFlags.HasFlag(Sdl.Window.State.MouseFocus))

with

    if (((int)winFlags & (int)Sdl.Window.State.MouseFocus) != 0)

This does not waste time on type checking and simply casts the enums to an int rather than boxing them.

We should add a code validation check that detects the use of `Enum.HasFlag()` in PRs and fails them.

**Comment by cra0zy** [comment]
I was gonna fix a bug in SDL Mouse so I'll replace the flag stuff with it.

**Comment by willmotil** [comment]
> won't even show up as a blip in your game.

It was showing up as a blip in my real time garbage output on screen display text :)

> You haven't stated which platform you running this on.

My bad the crossplatform template so ya i think that is GL.

> I was gonna fix a bug in SDL Mouse so I'll replace the flag stuff with it.

Good looking out. ill try out the nightly build tomorrow and make sure the blip is gone.

**Comment by willmotil** [comment]
The mouse isn't generating garbage anymore. even at 3500 fps.

**Comment by willmotil** [comment]
This got broke again somehow i think the changes were working.
