### ISSUE TITLE
Errors while running 

### ISSUE THREAD

**Issue by polanskij** [MonoGame/MonoGame#5369]
Hello everybody
When I test the monogame on monodeveloper 5, an error message appears
`Error: /home/user/test/test/test.csproj: /home/user/test/test/test.csproj could not import "$(MSBuildExtensionsPath)\MonoGame\v3.0\MonoGame.Content.Builder.targets" (test)`
How can I solve this problem? :-(

**Comment by cra0zy** [comment]
http://www.monogame.net/documentation/?page=Setting_Up_MonoGame_Linux

Also if you want to use development version (which I strongly recommend), I packaged up MonoDevelop 6 in .run package: https://github.com/cra0zy/monodevelop-run-installer/releases . Install it before MonoGame so that MonoGame installer installs the addin.

**Comment by cra0zy** [comment]
@tomspilman This can be closed.
