### ISSUE TITLE
RenderTarget2D constructor broken on Portable Library

### ISSUE THREAD

**Issue by impworks** [MonoGame/MonoGame#5450]
Consider the following code:

    public static RenderTarget2D CreateRT(GraphicsDevice device)
    {
        return new RenderTarget2D(
            device,
            device.PresentationParameters.BackBufferWidth,
            device.PresentationParameters.BackBufferHeight,
            false,
            SurfaceFormat.Color,
            DepthFormat.Depth16
        );
    }

This code works in a WP8.1 project, but in Portable library it throws an exception:

```
An exception of type 'SharpDX.SharpDXException' occurred in SharpDX.DLL but was not handled in user code

Additional information: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D.GenerateIfRequired()
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat preferredFormat, DepthFormat preferredDepthFormat, Int32 preferredMultiSampleCount, RenderTargetUsage usage)
```

P. S. The overload with only 3 arguments `(GraphicDevice, int, int)` works fine in Portable. Only constructors with more arguments are affected.

*Update*: here's a working reproduction:
(GitHub says it accepts ZIP uploads but actually doesn't!)

http://spark.ms/tmp/MonoGameFailTest.zip

**Comment by impworks** [comment]
This happens because `DepthFormat` definition is different across platforms:

```
 // Definition in WP8 and Android:
public enum DepthFormat
{
    None,
    Depth16,
    Depth24,
    Depth24Stencil8,
}

// Definition in PCL:
public enum DepthFormat
{
    None = -1,
    Depth24Stencil8 = 48,
    Depth24 = 51,
    Depth16 = 54,
}
```

I don't know which definition is correct, but as a temporary workaround, it is possible to cast magic constants to `DepthFormat` instead:

```
return new RenderTarget2D(
    device,
    device.PresentationParameters.BackBufferWidth,
    device.PresentationParameters.BackBufferHeight,
    false,
    SurfaceFormat.Color,
    (DepthFormat) 1         // Depth16
);
```

**Comment by Jjagg** [comment]
Not sure what happened to the PCL one, but that's not right.

**Comment by nkast** [comment]
The PCL version is meant to be referenced by you PCL libraries with Copy Local = false.
It doesn't contain any runtime copy, it' just the API definition so your PCL libraries can compile.

The executable must always reference the platform specific DLL of MonoGame.

**Comment by tomspilman** [comment]
@impworks - Which PCL assembly are you using?  This one...

https://www.nuget.org/packages/MonoGame.Framework.Portable/

... is old and not what we're using today.  You can get the new "bait and switch" PCL along with all the platform specific assemblies from the development NuGet server:

http://teamcity.monogame.net/guestAuth/app/nuget/v1/FeedService.svc/

**Comment by impworks** [comment]
@tomspilman - Yes, this is the PCL assembly I am using. Hope the newer version works.

P.S. If I reference this newer version using a custom feed URL, how can I specify the dependency to publish my project to original NuGet?

**Comment by impworks** [comment]
@tomspilman - no luck so far. NuGet says:

```
Could not install package 'MonoGame.Framework.Portable 3.6.0.1465-develop'.

You are trying to install this package into a project that targets '.NETPortable,Version=v4.6,Profile=Profile151',
but the package does not contain any assembly references or content files that are compatible
with that framework. For more information, contact the package author.
```

I am currently targeting WP8.1, Xamarin.Android and Xamarin.iOS. VS also automatically references .NET 4.5.1, Windows 8.1 and Xamarin.iOS (Classic) because they support the same APIs.

**Comment by tomspilman** [comment]
@DDReaper - What do you make of that NuGet error?  Is that an issue of what "profile" we have selected?

**Comment by DDReaper** [comment]
Hmm, that is possible it's a profile issue.  However, we made the gap for the PCL very wide so as to ensure we avoided this issue.
Checking

**Comment by impworks** [comment]
@DDReaper any luck on this?

**Comment by DDReaper** [comment]
Ok @tomspilman  @impworks  There is definitely a profile issue with the current profile 328.
I actually cannot even reference it when I select 328 profile targets from VS 2015, which it should. So there may be a piranah issue with 328.

So we ideally need to update the profile to something that matches the 3.6 supported platforms.
Checking [this table](http://portablelibraryprofiles.apps.stephencleary.com/), I believe we should target Profile 1.5.1 which supports .NET 4.5.1 / Win8.1 / WM8.1 by default (it also has support for netstandard 1.2 as an aside)

Trick is we can't test this until I do a PR and merge it really using the build process prianah setup.
Thoughts?

**Comment by impworks** [comment]
@DDReaper Profile 151 is good - my project's configuration uses it too. The current MonoGame PCL assembly from NuGet, though outdated, works fine with it.

**Comment by DDReaper** [comment]
Things are never easy.
In testing to move to a new profile, profile151 is provided with .Net4.6 and Profile111 is provided with .net4.5.  Which in it'self is not a problem.

However, Piranah it'self has a fault when compiling against anything higher than .net 4 🈂️ 
Ironically, it falls over with none other than my old friend the "SurfaceFormat"

digging deeper but it means I've had to delve back into the Piranah source to figure out why it's failing.

**Comment by DDReaper** [comment]
WHat a rabbit hole.  The error was caused because Piranah in .net 4 skipped the GraphicsDevice constructors but when using Piranah on .net4.5+ it does.
It see's that the GraphicsDevice (and only GraphicsDevice) has a dependency on itself for some reason. Will look at the code later and see if I can figure out why.  But adding in a condition in the code that was breaking resolved the issue in Piranah.

But it means I'll also need to upgrade Piranah to build against later versions of .Net

**Comment by nkast** [comment]
Looking at the problem again,  one possibility is that Piranah replaces enum values with random values. 
When the library is build, the compiler replaces DepthFormat.Depth16 with the constant value 54. 
During runtime the concrete MonoGame dll gets confused because 54 is invalid in DepthFormat.
@DDReaper, does this sound right?

**Comment by nkast** [comment]
As for the other issue with profiles, please don't change the profile, it's best to support a broad range of scenarios, starting from .Net4.0 and up.  A 4.5 library or executable can load a 4.0, but not the other way.

Another minor issue is that on Store apps, libraries fail to load when the version it was compiled with is higher than the one used. I don't know what's the purpose of this [ENTER 5 MINUTES OF RANT] limitation since a future version can be as different in it's public API as a past one. 
For Example I have a library compiled against PCL 3.2.99 and the main project against monogame git source with version [0.0.0.0](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Properties/AssemblyInfo.cs#L42). Store apps fail to load because of this and I have to change the version to something  >=3.2.99.

**Comment by DDReaper** [comment]
Ok, colour me a muppet.  Prianah on newer builds is a no go and likely needs a lot of work.  Priranah simply strips out far too much for it to be useful.

However, in testing I found the real cause for the issue above, which was far simplier.

Basically the NuSpec file doesn't actually target ANY portable platforms 🈂️ , will submit a PR to fix that shortly.

**Comment by DDReaper** [comment]
Just pushed #5505 to update NuGet target libs.  No need to change / alter Paranah for now, although it will need looking at for the future

**Comment by DDReaper** [comment]
S'all right @nkast I didn't change the Piranah build target in the end, leaving the portable DLL's alone

The install issue was because the portable NuGets (framework and content) were not using portable targets.  The PR will resolve that.  (although the NuGet is set to target from .Net 4.5 upwards, as MG Dll's are all .NET4.5 now)

I did tinker with .NETStandard as a target but it didn't behave and didn't want to push this simple fix pr.

**Comment by nkast** [comment]
> The install issue was because the portable NuGets (framework and content) were not using portable targets. 

So, #5505 fixes this issue? I can't say I understand what's really going on...!

**Comment by DDReaper** [comment]
#5505    allows the portable dll NuGet to be installed in PCL libraries 🗡 
Couldn't test the project @impworks provided as I recently rebuilt my machine and don't have the Windows Phone stuff on this machine.  But the newer DepthFormat will be in the newer PCL dll.

**Comment by impworks** [comment]
@DDReaper you can just check if the `DepthFormat` definitions match by using ILSpy or some other decompiler, without having to build a WP project. There were no other problems in the original project other than this.

**Comment by DDReaper** [comment]
The fix has been merged and you can check yourself.  Just looking at the PCL and it looks as follows:

```
        None = 0,
        Depth16 = 1,
        Depth24 = 2,
        Depth24Stencil8 = 3
```

And it's using the same format as source.

Feel free to update your NuGet using the dev Nuget now, which loads fine now
