### ISSUE TITLE
Window.IsBorderless strange behavior

### ISSUE THREAD

**Issue by energyuser** [MonoGame/MonoGame#5460]
I just updated to the latest develop build and this happened. Here's a little test I wrote in my Game1.cs constructor:

```cs
Point scrDimensions = new Point(1366, 768);
graphics.PreferredBackBufferWidth = scrDimensions.X;
graphics.PreferredBackBufferHeight = scrDimensions.Y;
Window.IsBorderless = true;
// explicitly setting Window.Position = new Point(0, 0); did not fix the issue.
```

1366x768 is my native screen resolution. So when I boot the game I can see my taskbar overlap it at the bottom of my screen. The top of the game is cut off the screen. Is this the desired behavior? Yesterday, before I updated the game was properly set to borderless fullscreen. Tested on x64 Win10 Pro with a DirectX project. Looking at the recent merge history, could this be caused by an oversight in #5419?

**Comment by nkast** [comment]
>> could this be caused by an oversight in #5456?

I don't think so. #5456 is relevant to SpriteBatch.Begin(..., Matrix);
So, the window is offeset by the taskbar and positioned somewhere at (0,-taskbarHeight) ?
Can you unpin the taskbar and dock it to the left,top,right to see how this goes? 

>> Yesterday, before I updated the game was properly set to borderless fullscreen. 

When was the last update before that?

**Comment by energyuser** [comment]
>When was the last update before that?

I actually don't remember... I think it was a week or two ago.

>So, the window is offeset by the taskbar and positioned somewhere at (0,-taskbarHeight) ?

More like (0, -(taskbarHeight / 2)); Obviously if I change the location of the taskbar, the window's position also changes. But it's always offset by -(taskbarHeight / 2).

>Can you unpin the taskbar and dock it to the left,top,right to see how this goes?

Same problem, different side of the screen.

**Comment by Jjagg** [comment]
> Window.IsBorderless = true;

You're not setting the game to run borderless fullscreen, you're just making the window borderless. Set GraphicsDeviceManager.HardwareModeSwitch to false and set GraphicsDeviceManager.IsFullScreen to true to get borderless full screen mode. I've tested that just now and it's working fine. 

That said your window position shouldn't change when setting the window to be borderless.

> #5419 because it changed the behavior of GraphicsDevice

Barely. #5419 didn't really change anything that could've caused issues. #5139 did change a bunch of things, so maybe that's related.

**Comment by energyuser** [comment]
Is there anything else I can test to help you guys get to the root of the issue? And does the test code I posted lead to the same behavior for you too?

**Comment by Jjagg** [comment]
The issue is here: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Windows/WinFormsGameForm.cs#L50
The code there centers the form in the WorkingArea which does not include the Windows taskbar. I think that's how XNA does it too, however after manually setting the position of the Window it should not recenter it. This is an issue I introduced, so I'll fix it.

**Comment by Jjagg** [comment]
I'll do some more checking to see if we completely match XNA regarding this with the fixes I just implemented, but I tested your code and that's working at least. Make sure you include `Window.Position = new Point(0, 0);` or the window will get centered in the working area (not the screen). It seems Windows hides the taskbar automatically when the window covers the whole screen, so essentially setting the back buffer size (and by extension the window size) to your screen resolution and the window position to (0,0) will make the game run in borderless fullscreen mode, however I don't recommend doing that because MonoGame will not know it's running in fullscreen.

**Comment by energyuser** [comment]
>the game run in borderless fullscreen mode, however I don't recommend doing that because MonoGame will not know it's running in fullscreen.

I have a preprocessor directive that tells the game to `graphics.IsFullscreen = true;` in RELEASE and to be borderless fullscreen in DEBUG. I do this because if the game is in fullscreen I won't be able to read the exceptions I get or the breakpoints I place.

**Comment by Jjagg** [comment]
In debug mode set HardwareModeSwitch in your graphicsdevicemanager to false. That will make the game run in borderless fullscreen when you enable full screen mode.
