### ISSUE TITLE
[WinDX] Window is not centred on startup

### ISSUE THREAD

**Issue by MichaelDePiazzi** [MonoGame/MonoGame#5568]
When using Windows DirectX, the game window is no longer centred on start up. Windows GL still works correctly.

This was previously fixed by PR #5139, but something must have broken it again since then. Any ideas on what the problem may be @Jjagg?

(P.S. This was originally raised in issue #4740, but I couldn't re-open it for some reason)

(CC @EnemyArea)

**Comment by Jjagg** [comment]
Yeah, I accidentally deleted the line that centered the window in #5467.
I think I removed it for testing or something and forgot to add it back in :/

**Comment by Jjagg** [comment]
I'll set up a fix tomorrow. I'll include tests to make sure this doesn't break again.

**Comment by MichaelDePiazzi** [comment]
> I'll set up a fix tomorrow. I'll include tests to make sure this doesn't break again.

Cool, thanks @Jjagg! :)

**Comment by Jjagg** [comment]
I started fixing this and #5533 in my branch from #5522. It's a bit unfortunate because this is just a little issue and I got the fix tangled up in a big PR. I can pull it out if anyone wants me too, but it shouldn't matter too much because I really want to get #5522 merged before the 3.6.1 release. I didn't get to testing the window stuff yet.

**Comment by MichaelDePiazzi** [comment]
No problem with me.

**Comment by Jjagg** [comment]
I split it up anyway because #5522 was getting out of hand.

**Comment by michaelpittino** [comment]
Is there any update on this? Using `MonoGame.Framework.WindowsDX.3.6.0.1625` and the window is always positioned in the top left corner when starting.
