### ISSUE TITLE
Fix or remove `checkedRect` from Texture2D Set/GetData

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#5600]
The `checkedRect` change in Texture2D Set/GetData is broken for compressed texture formats:

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/Texture2D.cs#L149

It doesn't consider that for compressed formats there is a minimum mipmap size that must be enforced.  So it passes the incorrect rectangle down to methods for setting the texture data.

IMO we sure purge this  `checkedRect` business entirely from the code base.

In particular the removal of calling SetData with a `null` rectangle is likely a performance hit.

I am willing to bet that for example `GL.TexSubImage2D` is slower than `GL.TexImage2D` when setting texture data.  Same with the methods under DirectX when the full texture level was being set instead of a sub-rectangle of the texture surface.

IMO we need to refactor all this to restore the old behavior for `null` rectangles and fix the checking when a rectangle is passed to consider compression needs.

**Comment by tomspilman** [comment]
@Jjagg @KonajuGames

**Comment by tomspilman** [comment]
Continuing a discussion with @Jjagg from https://github.com/MonoGame/MonoGame/issues/5557#issuecomment-287742618.

> Why remove it? 

For one it is wrong...  it isn't accounting for mip maps and isn't considering that all compression formats are not the same.

Second why mix validation of the input arguments with functionality.  I would love to be able to selectively disable validation later for a faster release build.  Mixing this calculation of some `checkedRect` that is used to perform the SetData/GetData makes that harder.

Third this `checkedRect` is tied to dropping the no-rectangle path from the `PlatformSetData`/`PlatformGetData` code... specifically we no longer pass a nullable `Rectangle` anymore.  The result in the OpenGL implementation is we always call `GL.TexSubImage2D` which I am willing to bet is slower than `GL.TexImage2D`.

**Comment by Jjagg** [comment]
The `checkedRect` is responsible for rounding the rectangle values passed when compressed textures are used, so we can't just 'purge' it without putting anything in place. 

> For one it is wrong... it isn't accounting for mip maps and isn't considering that all compression formats are not the same.

It does take mipmaps into account.
The issue is that it assumes 4x4 blocks for compressed formats which is wrong for PVRTC with 2 bits per pixel which uses 8x4 blocks. I'm not sure that's the only format for which it's wrong, but the point is it needs to be more flexible regarding block size.

> Second why mix validation of the input arguments with functionality.

I didn't bother separating it because in a discussion when I was about to implement this we agreed that the cost of actually getting/setting of data dwarfs the cost of the checks. But sure, it'd be nice to separate.

**Comment by KonajuGames** [comment]
#5614 implemented the fast path that uses `glTexImage2D`.
