### ISSUE TITLE
SpriteBatch with custom effect is not applying the Matrix Transform to the correct effect

### ISSUE THREAD

**Issue by Eversor** [MonoGame/MonoGame#5622]
During Setup() It's instead saving the multiplied matrix 
 - Matrix.Multiply(ref _matrix, ref projection, out projection);
to the 
 - _matrixTransform.SetValue(projection);
that is a readonly and is never updated when a custom effect is added to the SB.Begin.
 - readonly EffectParameter _matrixTransform;

I'm not sure if this is an easy fix, or is instead very complex due to "not all Effects expose a "MatrixTransform" parameter. But the spritebatch should at least warn the user that the projection matrix must be set by hand and the one that is given to the Begin() method will be discarded.
Hope i was clear enough.

**Comment by Jjagg** [comment]
This is expected behaviour. At least XNA doesn't set the transform for custom effects. 

Though there was a discussion a while ago about setting a 'MatrixTransform' uniform in custom shaders too. See #5213

**Comment by Eversor** [comment]
Yeah, that's the same issue. I'd say it would be at least correct to advise the dev. that the matrix is not being set? Doesn't make much sense that the method takes Effect **and** Matrix, but can only manage an Effect **or** a Matrix.

**Comment by Jjagg** [comment]
XNA devs made the decision to implement it like they did, so MG replicates that behavior. 

The thing is, if we set the matrix for custom effects the name of the matrix is just based on convention. I.e. you need to name your transformation 'TransformMatrix' to have it set by SpriteBatch. IMO that's not very nice. I think that's why XNA devs decided not to do this.
Also usage of custom effects with SpriteBatch is mostly for post processing effects that only have a pixel shader and don't need a transformation matrix.

I prefer how things are right now.

**Comment by Eversor** [comment]
If I understand correctly, original XNA code was setting the input transform to the DefaultEffect, regardless the Effect parameter we passed to the Begin method?

**Comment by Eversor** [comment]
I got a little more documented on the matter and it seems that Shawn confirmed that the Transform is set to the DefaultEffect projection as a way to support partial Pixel-Shaders, that will need the default transform to be set to the default VertexShader. 

http://xboxforums.create.msdn.com/forums/t/71972.aspx

This means the actual behaviour is correct, even if i wouldn't want to find myself in the shoes of someone trying his code out against this behaviour.
