### ISSUE TITLE
Lets talk about DesktopGL 

### ISSUE THREAD

**Issue by cra0zy** [MonoGame/MonoGame#5708]
I was gonna talk about this in #3831 but that become too crowded.... anyway, right now DesktopGL is still split into WindowsGL and Linux projects, while we only use binaries from one of those and package it into DesktopGL stuff. Right now there are 4 possibilities, either we:
 1. Merge the projects into one, tho that might create a bit of problem for the Pipeline Tool since it resides in main platform projects
 2. Keep stuff as they are
 3. Add a DesktopGL platform, use it for NuGet and keep the rest as is
 4. Add a DesktopGL and MacGL platforms to source, add WindowsGL, MacGL, LinuxGL nuget packages and make sure that each platforms package only provides the needed native libs for that platform (bonus we can hardcode libs so there is no config file, solves 1 of the problems we have for .net core support)

CC. @tomspilman @hach-que

**Comment by Jjagg** [comment]
I talked a bit about this with @hach-que some time ago. She said the following:

"You can't merge Linux and WindowsGL into one DesktopGL solution.
Well I mean you can have it so that DesktopGL is a platform that's treated the same as WindowsGL,
but you can't remove Linux from the list of platforms without breaking downstream projects.
The whole "merge projects / solutions" never made sense to me since the projects and solutions Protobuild generates are just temporary files anyway the only other way to do it would be to have an external C# project (that isn't generated by protobuild), and reference that from both platforms by an ExternalProject reference.

But as far as Protobuild is concerned, if two platforms have the same content, and the same defines, and when they build they produce exactly the same assembly, then they're "merged" for whatever definition you like. Yes, if you do Protobuild.exe --generate WindowsGL and Protobuild.exe --generate Linux you get MonoGame.Framework.WindowsGL.csproj and MonoGame.Framework.Linux.csproj on disk. But if I do Protobuild.exe --generate WhateverRandomStringIWant I can get Module.WhateverRandomStringIWant.csproj on disk as well. The platform names aren't a discrete bound list of options; as far as Protobuild is concerned you can put whatever you want in there.

Now technically there is a <SupportedPlatforms> tag, but this is intended to be a (strong) hint about what platforms the code will run on, not a list of projects Protobuild can generate (because Protobuild can generate an infinite number of platforms). As far as MonoGame is concerned, it runs on both Windows and Linux, which is why they are listed under SupportedPlatforms."

WindowsGL still defines WINDOWS and Linux defines LINUX, so the binaries might not be exactly equal built on Linux or Windows. The build files are a bit of a mess all over really. The defines are all over the place. There's really no reason for Linux to define OPENGL for example, since it uses the OpenGL service, which defines OPENGL (and has to remove DIRECTX in case you generate Windows with OpenGL). For selecting what files to include they should mostly use Services (e.g. OpenGL, OpenAL, DirectX...), but there's a lot of platform constraints in the files. I'm up for cleaning things when I manage to free up some time again (though there's probably a lot of higher priority stuff that I could better spend my time on first).

**Comment by cra0zy** [comment]
@Jjagg A long time ago in a PR fat far away I did merge the Linux and WindowsGL platforms, but then @hach-que and @tomspilman got into an argument and we ended up without an answer, that is why I tagged those two. It has been an year and a half since then, in case you wanna read up more on it: #3891

PS. My only opinion is that I don't like option 2 (keep stuff as they are), everything is better (and cleaner) tan that.

**Comment by Jjagg** [comment]
I vote for option 3, but also remove WindowsGL. There's really no point in keeping it around, especially if we add a DesktopGL platform, and it just adds to the confusion. IMO it's fine to let Protobuild generate Linux/Mac/DesktopGL even though they're the same. We could add notes in the Readme and in the docs on the website in the sections that talk about how to build from source to note they're actually the same projects.

**Comment by mrhelmut** [comment]
As far as I'm concerned, anything about Linux just works super well (I've been using the Linux project for all platforms for quite some time now and I feel like WindowsGL is useless).

I'd go with renaming Linux to DesktopGL and drop WindowsGL.

Regarding nuget packages, would something like having 3 DesktopGL packages make sense? Like DesktopGL (for Windows), DesktopGL (for MacOS) & DesktopGL (for Linux), each with the related native dependencies.

I'm between 3 and 4.

**Comment by Jjagg** [comment]
I'm fine with option 4 too, but I prefer 3 because IMO for the NuGets beginner-friendliness is more important than building from source and having only 1 DesktopGL platform on there might be clearer for new users.

> Regarding nuget packages, would something like having 3 DesktopGL packages make sense? Like DesktopGL (for Windows), DesktopGL (for MacOS) & DesktopGL (for Linux), each with the related native dependencies.

We'd still want one that has all the dependencies, right? So you can build a binary for all three OS'es.

**Comment by mrhelmut** [comment]
Makes sense if you want your project files to be portable on all platforms. It questions the usefulness of having multiple nugets.
Since some platforms require specific packaging in order to publish apps (e.g. MacOS & Linux), I feel like nugets are for development purpose and having specific dependencies or all of them doesn't chose anything when it comes to publishing an app.

I'd be for 3 (and dropping WindowsGL) but the .net core issue remains.

**Comment by hach-que** [comment]
I don't care about the presence of "WindowsGL", but I do care that "Protobuild.exe --generate Linux" produces working binaries.

In the original PR that was submitted, it dropped "Linux" from the supported platforms list in the module, which would have broken all of downstream projects that have Linux support (because MonoGame's module would have been signalling that it does not support Linux).

I also don't care if "DesktopGL" and "Linux" result in the same output; that is fine too.  I just want "Protobuild.exe --generate Linux" to continue to work.

**Comment by hach-que** [comment]
(You can also rename Linux to DesktopGL with your NuGet packages, I don't care there either)

**Comment by hach-que** [comment]
.NET Core is way more complex and requires Protobuild support upstream... it's on the roadmap but I don't know when it will happen.

The difficulty is figuring out how to handle it.  Introducing a `--framework` option is bleh, and I don't really like that.  Plus I want a way of opting into whatever experimental .NET Core support we implement.

We could introduce platforms like `WindowsCore`, `MacOSCore`, `LinuxCore`, but then when .NET Core adds  support for Android and iOS we're just going to end up with `Core` variants of almost all of the supported platforms.  And if a new platform comes out that only supports .NET Core, would that have the `Core` suffix?  It's not clear either way.

So the issue with .NET Core support in Protobuild right now includes how to design it in a future-proof way that isn't going to end up junk later.

**Comment by hach-que** [comment]
(That said, I am personally very interested in having .NET Core support in MonoGame, so that I can run dedicated Linux game servers on a stable implementation of .NET)

**Comment by cra0zy** [comment]
> (That said, I am personally very interested in having .NET Core support in MonoGame, so that I can run dedicated Linux game servers on a stable implementation of .NET)

*caugh* https://github.com/cra0zy/MonoGameCore *caugh*

**Comment by hach-que** [comment]
Yeah, I saw that, but I want to wait for .NET Core to land upstream since I need to do the work on Protogame to support it as well (and that also needs Protobuild support for .NET Core).

**Comment by cra0zy** [comment]
Closing this since Protobuild is getting axed.

**Comment by hach-que** [comment]
Since when is Protobuild getting axed?

**Comment by tomspilman** [comment]
@hach-que - Axed is a premature take.  We are discussing alternatives based on what .NET is starting to support.  https://github.com/MonoGame/MonoGame/issues/6207

**Comment by hach-que** [comment]
Oh right, I wanted to make sure @cra0zy was not under the impression we had "axed" the project upstream, since it wasn't clear from what angle the statement was made.

**Comment by tomspilman** [comment]
Right... I can see how that was ambiguous now.  Really it is looking at all the new changes to .NET project management and evaluating if there is a better solution now.

**Comment by cra0zy** [comment]
I see now how it can be interpreted that way, will try to be more specific in the future, sorry about that.

**Comment by hach-que** [comment]
No need to apologize - At least one other person was confused as to the support status of Protobuild after the blog post about Protogame, so I just wanted to clarify in case that was the perception here.
