### ISSUE TITLE
Monogame does not Dispose correctly on UniversalWindowsPlatform

### ISSUE THREAD

**Issue by ZangiRider** [MonoGame/MonoGame#5762]
Hi,

I just tested an Empty game project on Windows Universal Platform and DesktopGL I noticed that on desktop when I close the game the methods OnExiting,UnloadContent and Disposed are called, but not on Windows Universal Platform only the methode OnDeactivated is called.

Is this behavior is intended? How can I dispose correctly my game on UWP?

Thanks in advance.

**Comment by nkast** [comment]
Store apps follow a different lifecycle than traditional apps. See       https://docs.microsoft.com/en-us/windows/uwp/launch-resume/app-lifecycle

**Comment by DDReaper** [comment]
Due to the way tombstoning and exit works on UWP, the process is slightly different.  When you tombstone, you don't want to dispose all of your assets as you are meant to simply resume.
Also, the tombstoning process has changed between 8.1 and UWP, in that the app is kept in a more "active" state for quicker restoration.

@nkast link is the best read for the information.  Another source is the tombstoning example in the XNAGameStudio archive. 
https://github.com/DDReaper/XNAGameStudio/wiki/Tombstoning-Sample
Although it's still referencing WP7, the methods used are the same for UWP, regarding saving state and the updated app lifecycle.

if this works for you, then please close the issue.
