### ISSUE TITLE
TargetElapsedTime for high FPS causes slow down of game (DesktopGL)

### ISSUE THREAD

**Issue by JPCZ44** [MonoGame/MonoGame#5783]
I am using _TargetElapsedTime_ to cap max FPS to some value. When I am using it for FPS around 30 or 60 it works good, bud when I want to limit FPS on higher values like 300 or 500 it causes slow down to 20 - 5 FPS. 

Im using it like this:

`TargetElapsedTime = TimeSpan.FromSeconds(1f / maxFPS);`

**Comment by mrhelmut** [comment]
Is there a specific reason you would need precisely 300 or 500 FPS?
The more FPS you ask to ```TargetElapsedTime```, the less it gets precise because of timer precision, so no wonder it gets choppy past a certain point.
If you need an uncapped framerate, ```IsFixedTimeStep = false;``` is a better strategy.

**Comment by JPCZ44** [comment]
It is not necessary, but it is strange behavior - I set maxFPS to 300,  but I will get 20. I can set IsFixedTimeStep = false of course, but I have in game console where user can set max_fps manualy. And when he enter too high value (300 or 500) it slow down his game and it doesn't look very well. I can prevent this by allowing just "normal" values (up to 200), but I didn't understand reason for this. I think that this is bug.

**Comment by willmotil** [comment]
I think that the effect you see, is due to misuse / misunderstanding of Fixed timestep. 
Fixed timestep isn't meant to be set at very high frame rates which arbitrary video cards cannot be guaranteed or more importantly expected to all be able to reach.

If a game that has its target elapsed time for 60 fps, cant hit 60 fps it will start skipping draws.

Consider a case were you set the desired frame rate to 500 frames in a second but updates alone even with is fixed time step set to false could only complete 200 per second if your draw was empty. In this case were your max fps is some were around 150 with draw code, your setting a fixed time step that exceeds the maximum fps even if isFixedTimeStep was false.  
This would cause IsRunningSlowly to be set to true and draws would be skipped constantly as it would be chalking up frames to be skipped falsely multiple times per frame.

**Comment by JPCZ44** [comment]
Thank you for your, explanation! I understand now.

**Comment by Jjagg** [comment]
Closing this because it's based on a misunderstanding.
