### ISSUE TITLE
Multisampled Texture2D.GetData() throws Invalid arguments exception

### ISSUE THREAD

**Issue by spunky44** [MonoGame/MonoGame#5834]
It seems multisampled textures will crash if you try to save a rendertarget as a png, for instance.

```
HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments]
   ved SharpDX.Result.CheckError()
   ved SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   ved SharpDX.Direct3D11.Texture2D..ctor(Device device, Texture2DDescription description)
   ved Microsoft.Xna.Framework.Graphics.Texture2D.PlatformGetData[T](Int32 level, Int32 arraySlice, Rectangle rect, T[] data, Int32 startIndex, Int32 elementCount) i C:\Users\User\Documents\Visual Studio 2017\Projects\MonoGame\MonoGame.Framework\Graphics\Texture2D.DirectX.cs:linje 138
   ved Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](Int32 level, Int32 arraySlice, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount) i C:\Users\User\Documents\Visual Studio 2017\Projects\MonoGame\MonoGame.Framework\Graphics\Texture2D.cs:linje 206
   ved Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](Int32 level, Nullable`1 rect, T[] data, Int32 startIndex, Int32 elementCount) i C:\Users\User\Documents\Visual Studio 2017\Projects\MonoGame\MonoGame.Framework\Graphics\Texture2D.cs:linje 221
   ved Microsoft.Xna.Framework.Graphics.Texture2D.GetData[T](T[] data) i C:\Users\User\Documents\Visual Studio 2017\Projects\MonoGame\MonoGame.Framework\Graphics\Texture2D.cs:linje 247
   ved MonoGame.Utilities.Png.PngWriter.GetColorData(Texture2D texture2D) i C:\Users\User\Documents\Visual Studio 2017\Projects\MonoGame\MonoGame.Framework\Utilities\Png\PngWriter.cs:linje 227
   ved MonoGame.Utilities.Png.PngWriter.Write(Texture2D texture2D, Stream outputStream) i C:\Users\User\Documents\Visual Studio 2017\Projects\MonoGame\MonoGame.Framework\Utilities\Png\PngWriter.cs:linje 36
   ved Microsoft.Xna.Framework.Graphics.Texture2D.PlatformSaveAsPng(Stream stream, Int32 width, Int32 height) i C:\Users\User\Documents\Visual Studio 2017\Projects\MonoGame\MonoGame.Framework\Graphics\Texture2D.DirectX.cs:linje 311
   ved Microsoft.Xna.Framework.Graphics.Texture2D.SaveAsPng(Stream stream, Int32 width, Int32 height) i C:\Users\User\Documents\Visual Studio 2017\Projects\MonoGame\MonoGame.Framework\Graphics\Texture2D.cs:linje 294

```

The exception is thrown here:

```
private void PlatformGetData<T>(int level, int arraySlice, Rectangle rect, T[] data, int startIndex, int elementCount) where T : struct
        {
            // Create a temp staging resource for copying the data.
            // 
            // TODO: We should probably be pooling these staging resources
            // and not creating a new one each time.
            //
            var min = _format.IsCompressedFormat() ? 4 : 1;
            var levelWidth = Math.Max(width >> level, min);
            var levelHeight = Math.Max(height >> level, min);

            if (_cachedStagingTexture == null)
            {
                var desc = new Texture2DDescription();
                desc.Width = levelWidth;
                desc.Height = levelHeight;
                desc.MipLevels = 1;
                desc.ArraySize = 1;
                desc.Format = SharpDXHelper.ToFormat(_format);
                desc.BindFlags = BindFlags.None;
                desc.CpuAccessFlags = CpuAccessFlags.Read;
                desc.SampleDescription = CreateSampleDescription();
                desc.Usage = ResourceUsage.Staging;
                desc.OptionFlags = ResourceOptionFlags.None;

                // Save sampling description.
                _sampleDescription = desc.SampleDescription;

                _cachedStagingTexture = new SharpDX.Direct3D11.Texture2D(GraphicsDevice._d3dDevice, desc); <- line that crashes
            }

```

http://community.monogame.net/t/multisampled-texture2d-saveaspng-crashes/9492

**Comment by Jjagg** [comment]
I'll take this. I had to fix the same issue for GetBackBufferData in fda7e839d6e96504e619e2c56f3b6cd2526a2e79

**Comment by Jjagg** [comment]
Working on this right now.
I don't think we can support `SetData` on multisampled textures :/
@Kosmonaut3D do you happen to know about that?

**Comment by Jjagg** [comment]
I got this fixed but I'd like some input on whether or not we should support SetData on MSAA'd render targets. I made a little drawing to explain how MSAA works in D3D11
![image](https://user-images.githubusercontent.com/14875382/28523333-37540eea-707c-11e7-923f-038fa2f554a6.png)



You have 2 D3D textures, 1 with MSAA and 1 where you resolve it which does not have MSAA. When rendering to the RenderTarget you need to set the MSAA texture. When rendering the RT to the backbuffer (or another texture) you need to set the resolved texture. You need to call `ResolveSubresource` to resolve the MSAA texture to the other one. MG does this when the RenderTarget is unset. 

My question is if we should support SetData on a MSAA RenderTarget. 
Pros:
- Convenience, users can change using MSAA on an RT without getting errors at runtime. Probably not really practical at all, because creating an RT with MSAA is only useful if you're gonna render to it, rather than use SetData.
- ???

Cons:
- We can't set data on the MSAA texture, so we must set it on the resolved texture. Of course that's invalidated once the user draws to and unsets the RenderTarget because the MSAA texture will be resolved to the texture. 
- As a consequence this can give unexpected results if users SetData, then renders to an MSAA RT because the SetData call will not have any effect (this will not be unexpected if `RenderTargetUsage.DiscardContents` was specified).

Of course there's a hack we can use. We could SetData on a temp texture and render that to the MSAA texture. But I don't think MG should do things like that transparently.

I don't like the idea of supporting SetData on MSAA RTs. IMO we should just throw in this case.
Thoughts @KonajuGames @nkast?

**Comment by Jjagg** [comment]
Actually, we should just test XNA behavior :p

**Comment by nkast** [comment]
some clues ftom MSDN docs, 
'RenderTargetUsage.PlatformContents'
`Either clears or keeps the data, depending on the current platform. On Xbox 360, the render target will discard contents. On PC, the render target will **discard if multisampling is enabled, and preserve the contents if not**.`

...seems like preserving the content of MSAA is an expensive op.
Do we have a test case for multisampling+ PreserveContents ?

**Comment by nkast** [comment]
...maybe we need to render the Resolved texture on top of the MSAA anyways.

**Comment by KonajuGames** [comment]
I would suggest that we do not support SetData on a multisampled render
target. Does XNA support SetData on a non-multisampled render target? The
idea of SetData on any render target is a bit odd.

**Comment by Kosmonaut3d** [comment]
I think using setdata on the resolved texture is the expected behaviour for most users anyways.
