### ISSUE TITLE
G-Sync slows down game

### ISSUE THREAD

**Issue by Oyyou** [MonoGame/MonoGame#5840]
Just going to jump right into it.

I have my GPU set to "Enable G-SYNC for windowed and full screen mode.".

I just ran my game, and it was noticeably slower, with no change on the frame rate.

Below is a video of both:
https://www.youtube.com/watch?v=4ftIuM6Xbhg

Left - this is without G-SYNC
Right - this is with G-SYNC

Now I must say - I'm not trying to make my game "G-SYNC" compatible, but I'm worried that if I were to release the game, those with G-SYNC enabled may have issues, and not know why.

I'm just wondering if this is actually a bug, or am I missing something?

**Comment by mrhelmut** [comment]
It doesn't look like a bug, but like an issue in your movement code.
I believe that you are updating your sprite position with a fixed amount of pixels every frame, without using the time. Am I wrong?

**Comment by Oyyou** [comment]
Yes - you are correct (temp, of course).

But I'm wondering, if it's at the same FPS, how could it make a difference?

**Comment by mrhelmut** [comment]
I suggest that you ask this on the forum and close this issue, since it's not a bug.

The thing is that the way you coded your movement is bound to the framerate, and G-sync force a fixed (lower) framerate, which is why you are getting this result. This also means that no computer will run the game at the same speed.
What you're looking for is framerate agnostic movement.

**Comment by Oyyou** [comment]
Okay - cheers!
