### ISSUE TITLE
Optimize Vector2/3/4.Transform(Vector3[] sourceArray, ...)

### ISSUE THREAD

**Issue by nkast** [MonoGame/MonoGame#5882]
All those use the same pattern where we copy the struct from sourceArray and then copy the result back to destinationArray.
 
https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Vector3.cs#L1075-L1083
```
for (var i = 0; i < length; i++)
            {
                var position = sourceArray[sourceIndex + i];
                destinationArray[destinationIndex + i] =
                    new Vector3(
                        (position.X * matrix.M11) + (position.Y * matrix.M21) + (position.Z * matrix.M31) + matrix.M41,
                        (position.X * matrix.M12) + (position.Y * matrix.M22) + (position.Z * matrix.M32) + matrix.M42,
                        (position.X * matrix.M13) + (position.Y * matrix.M23) + (position.Z * matrix.M33) + matrix.M43);
            }
```

One thing we can do here is to use the ref version of transform()
```
for (var i = 0; i < length; i++)
        Transform(ref sourceArray[sourceIndex + i], ref matrix, out destinationArray[destinationIndex +i]);
```

We can also use fixed pointers in order to get rid of the two array bound checks.

**Comment by vpenades** [comment]
Also, it would be worth to explore the possibility of having some sort of compatibility with System.Numerics.Vectors , which are the standard for Vector Maths, and are SIMD accelerated.

**Comment by theZMan** [comment]
@nkast but you are replacing the inlined method with a call that might not get inlined. Do we have a proflile run showing this is an improvement? Pointers might be a benefit but probably due to removing one of the copies rather than the bounds check. I never used to see a perf gain until I was hitting the 10s of thousands of accesses in particle systems.

@vpenades - problem with system.numerics is that we have to convert all of our structs to match theirs. the overhead will probably undo any gains we get from simd paralelism https://msdn.microsoft.com/en-us/library/mt598257(v=vs.111).aspx I can't remember if anyone has actually tried to profile it though so maybe worth some time

**Comment by tomspilman** [comment]
> We can also use fixed pointers in order to get rid of the two array bound checks.

I think we should keep the code inlined like it is right now... it is a guaranteed performance win.

We just need to used some unsafe pointers to get the last bit of performance from the code.

> problem with system.numerics is that we have to convert all of our structs to match theirs

@theZMan 

I wonder if you can use unsafe code to cast our `Vector2` to theirs then call their SIMD optimized routines?

Also strange they have no transform methods that take arrays of elements.  This means potentially the overhead of one function call per transform.

So yeah still not sold on SIMD support in .NET.

**Comment by nkast** [comment]
@theZMan
No, I haven't done any tests, just a guess. This is very similar to the Skinning XNA sample that uses a similar pattern to work around the limitations of XBOX360  & WP7 (no pointers/unsafe code). But I see your point, I don't remember if the method was inlined, maybe it was and maybe some third party CLRs might no do that. We can skip the speculations -no matter how interesting it would be to investigate- and just use fixed pointers.
