### ISSUE TITLE
Content pipeline Visual Studio integration

### ISSUE THREAD

**Issue by Ketsuban** [MonoGame/MonoGame#5963]
Towards the end of #4796 the [idea was broached](https://github.com/MonoGame/MonoGame/issues/4796#issuecomment-304155207) of integrating content management into the IDE itself rather than having a separate tool, but the conversation was muddied since the original issue was essentially a complaint about the existence of a content pipeline in the first place.

The thing that strikes me about that proposition is it's essentially how XNA worked - within your XNA project you had a Content project (similar to but not the same as the MonoGame setup, where the Content folder contains a magic file called Content.mgcb) to which you added your assets directly; the conversion to XNB files happened at compile-time, and the Visual Studio properties pane let you configure the same things as the Pipeline Tool's properties pane.

Is the separate tool just for the benefit of users on non-Windows platforms, or are there benefits to having a separate tool for everyone? Is it possible to have the convenient Visual Studio-integrated content pipeline on those platforms which support it and the separate MonoGame tool elsewhere?

**Comment by KonajuGames** [comment]
It is so the content build GUI can be used on Mac and Linux.
It is so artists in a studio do not need to have Visual Studio and the full source project loaded to add or change content in a game.
It is because the VS add-in would break almost every time VS is updated, the same as what has happened several with the MonoDevelop/Xamarin Studio/Visual Studio for Mac plug-in for project templates.
It is so we don't have to maintain two separate codebases that will get out of sync.

**Comment by tomspilman** [comment]
Hi @Ketsuban .

> The thing that strikes me about that proposition is it's essentially how XNA worked

We are very aware of how XNA worked.

We decided on a different direction which was better for the MonoGame project.

> Is the separate tool just for the benefit of users on non-Windows platforms,

No... it was not the main reason.

> are there benefits to having a separate tool for everyone?

Yes.  

### The tool works regardless of your C# IDE.

With as much stuff as there is to do on MonoGame the last thing we wanted to do was add more work chasing changes to VS and fixing our plugins to work.  

Also for a long time plugins didn't work with VS community editions... so the plugin wouldn't even work for people using free tools.

Finally we still had to deal with Xamarin's IDEs and even the free Mono IDEs and making plugins that worked there across multiple platforms.

Our time is better spent improving MG than chasing IDE integrations that arguably add very little to productivity.

### Content is not the same as code

Content building tied directly to your C# project seems like a good idea at first... especially on small samples and games.  However it is a huge mistake on any large game project.

So you just got new code for your game and go to your IDE and hit "Rebuild Solution" so that everything is fully rebuilt.  Well in XNA this would trigger a full rebuild of all game content.  This is fine in most small XNA titles.  But when you have games that take 10 to 20 minutes to build content fully... a simple mistake of hitting "Rebuild" is super costly.

We considered never allowing for a rebuild from the IDE... and ignoring rebuild commands and just doing simple incremental builds.  But then what happens when you *really* do want to do a rebuild?  How do you do that if we removed the functionally?

Finally if you look at all the other professional engines out there, content and code are treated seperately because plainly they are very different.

> Is it possible to have the convenient Visual Studio-integrated content pipeline 

Sure... but who is going to write it and maintain it for the next 10 years?

Yeah it seems harsh to put it in those terms but that is realistically what you are asking of the project.

I personally am not going to dedicate my nights and weekend to tilt at that windmill.

**Comment by tomspilman** [comment]
@Ketsuban - Follow up question for you.

What do you find lacking in having the Pipeline Tool as a separate application?  Is it just the extra step of opening it?

**Comment by cra0zy** [comment]
I'll just point out that doing something like #4816 requires almost no maintenance.

**Comment by Ketsuban** [comment]
@tomspitman Pretty much - it's a trifling matter, but with how XNA did it it was easy to have the asset name visible while writing code that used it, whereas the Pipeline Tool has an indirection because you have to switch windows. (I'm also not 100% sure if it actually *displays* the asset name, but the default is still the same as the filename without the extension by default so it's not really important.)

I was just curious for a rundown of the pros and cons of the decision to use a separate tool, I didn't seriously think the reaction would be "doy, why didn't we do that before". I guess I didn't communicate that too well.
