### ISSUE TITLE
Corrupted textures on iOS

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#5968]
Hello there,

I'm running into texture corruption issues.

For reference: https://gitlab.com/paulloz/EMMA/uploads/7601b49dbd9cac9ceb2856107ca50013/IMG_0321.PNG

A few facts:
- it's random, it can happen on all iOS devices, but sometimes it doesn't (90% repro chance)
- the first few rows of the texture are corrupted
- it's not happening on other platforms
- it's not happening when using texture compression
- it's not related to the pipeline processing of the assets, it's a runtime problem
- it may be related to loading textures from a thread
- it's urgent ^^'

Does anyone have a clue about this?

@KonajuGames @dellis1972 @roponator ?

**Comment by roponator** [comment]
I can't help you here because I don't have iOS hardware.

**Comment by mrhelmut** [comment]
Ah sorry for mentioning you, I assumed that based on your mobile work.

I found the cause, it's related to loading textures from a thread. Only textures loaded from threads have a chance to get corrupted. It may not be a MonoGame issue. Investigating.

**Comment by vpenades** [comment]
I would like to ask... which is the right approach for loading assets (not only textures) in a multithreaded environment? is it allowed? (hence, it should handle them with proper locking mechanism) or is it forbidden and assets should be loaded in the main thread? (hence, it should be forbidden and give an error when loaded from a different thread)

**Comment by Jjagg** [comment]
It's generally fine to load content on multiple threads. For DX it's fine to load textures across threads too because MG properly locks the D3DContext where it's required. For GL it's currently not because MG only creates 1 GL context (always on the main thread). [Some graphics operations](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/Texture2D.OpenGL.cs#L91) will be delayed until the end of the game loop cycle and then executed on the main thread.

See:
- [SDL game loop](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/SDL/SDLGamePlatform.cs#L109)
- [Threading helper](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Threading.cs)

**Comment by mrhelmut** [comment]
Yes, the current GL path postpone any texture loading to the end of a frame rendering and force it to happen on the main thread (in order to guarantee that everything is fine, because some OpenGL drivers are super picky about this on single context apps). Despite this, it may corrupt textures on iOS, and I'm quite sure it has something to do with threads.

**Comment by harry-cpp** [comment]
I'll close this as there is a good chance that my PR that fixed the threading helper on iOS fixed this, reopen it if you can still repro it.
