### ISSUE TITLE
UWP / Xbox games throw an exception & won't launch in newer 3.7.0.xxx builds

### ISSUE THREAD

**Issue by YugeshN** [MonoGame/MonoGame#5998]
I have a cross platform game I am working on (OpenGL, Android and XB1). It's been working fine on versions up to 3.7.0.716

However, versions 3.7.0.966 and above (not sure how much earlier than 966 the problem was introduced... but I had installed 966 a while back and hadn't tested the game on XB1 until recently) now cause the game to crash on XB1 when launching. 

I also tested the most recent build (3.7.0.990) and the problem is still there. The specific stack trace I get it:
    
    Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException occurred
      HResult=0x80131500
      Message=Failed to create graphics device!
      Source=<Cannot evaluate the exception source>
      StackTrace:
       at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
       at Microsoft.Xna.Framework.Game.DoInitialize()
       at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
       at MonoGame.Framework.XamlGame`1.Create(String launchParameters, CoreWindow window, SwapChainPanel swapChainPanel)
       at MyGame_UWP.GamePage..ctor() in D:\Dev\csharp\game\mygame\mygame-
    uwp\GamePage.xaml.cs:line 30
       at MyGame_UWP.MyGame_UWP_XamlTypeInfo.XamlTypeInfoProvider.Activate_0_GamePage() in D:\Dev\csharp\game\mygame\mygame-uwp\obj\x64\Debug\XamlTypeInfo.g.cs:line 202
       at MyGame_UWP.MyGame_UWP_XamlTypeInfo.XamlUserType.ActivateInstance() in 
    D:\Dev\csharp\game\mygame\mygame-uwp\obj\x64\Debug\XamlTypeInfo.g.cs:line 411

    Inner Exception 1:
    DllNotFoundException: Unable to load DLL 'ole32.dll': The specified module could not be found. 
    (Exception from HRESULT: 0x8007007E)
    

Note, if I re-install 3.7.0.716 and rebuild, it works just fine on XB1, so the problem is clearly introduced in one of the versions after 716.

Note, this is the windows version of the Monogame SDK with Visual Studio Community 2017.

**Comment by nkast** [comment]
Here is the list of recent builds. Can you test a couple of those?
http://teamcity.monogame.net/viewType.html?buildTypeId=MonoGame_PackagingWindows&page=1&tab=buildTypeHistoryList&branch_MonoGame=<default>

A good starting point would be #3.7.0.910 / #3.7.0.912.

**Comment by Jjagg** [comment]
@nkast are those the builds where SharpDX was upgraded? That's the first thing I thought of.

**Comment by nkast** [comment]
Yes, 3.7.0.912 is the SharpDX 4.0.1 upgrade.
The SharpDX 3.1.1 upgrade was 3.7.0.647.

**Comment by YugeshN** [comment]
@nkast @Jjagg  I had already tested 3.7.0.990 (the most recent build), and it has the same issues. The builds you are pointing to are earlier than 990.... is there a reason those specific builds might work?

I can test those... but it's likely those are broken as well. Will have an update on those builds in a little while.

**Comment by YugeshN** [comment]
@nkast FYI, there is no artifact for 910, so I am testing 911....

**Comment by YugeshN** [comment]
@nkast @Jjagg Looks like 911 still has the problem, so it's not related to the SharpsDX upgrade (which was done in 912).

Finding the specific build that introduced the problem is going to be challenging....

**Comment by YugeshN** [comment]
@nkast @Jjagg Heh... well, that took me less time than I thought it would... so I managed to narrow it down to a specific build.

It look like the problem was introduced by jesse <jessegielen@hotmail.com> (is that you @Jjagg ?) in build 903 i.e. upgrading the sharpDX dependencies.

Build 900 was good... and 903 failed, so there is a slim chance the bug could have been introduced in build 901 (also by Jesse) or in build 902 (by @KonajuGames ), but I doubt it.

The culprit most definitely looks like build 903 changes.

**Comment by Jjagg** [comment]
Yes, that's me. So we likely need the conditionally compiled assembly for UWP here. My guess is this issue is similar to #5986. I think the best move here is to use the specific desktop and uwp assemblies instead of the shared .NET Standard assemblies. Unless anyone comes up with a better idea I'll set up a PR to pull in
those dependencies :) I probably won't have time before this weekend though.

**Comment by nkast** [comment]
I tried a UWP project on my windows 10 desktop and everything seems ok.
The issue here seems to be with XBox that doesn't have Ole32.DLL.

**Comment by vpenades** [comment]
@Jjagg the Net Standard assembly of SharpDX is just the "bait" assembly of the corresponding nuget packages, it is used by Visual Studio to gather the public symbols so you can write net standard projects targeting SharpDX package (NOT the assembly). But at compile time, the net standard assembly never reaches your Bin folder, the appropiate platform specific assembly is used instead. That's the beauty of using NuGet packages.

Explained in another way:

- You reference the "Net.Standard" SharpDX **NuGet Package** in a NetFramework 4.6.2 project. At compile time MSBUILD resolves the NuGet dependency and you get a NetFramework 4.5 SharpDX assembly in your BIN folder.
- You reference the Net.Standard SharpDX **DLL** in a NetFramework 4.6.2 project. At compile time MSBUILD just copies the referenced assembly and you get the NetStandard SharpDX assembly in your BIN folder, which fails to run.

The key diference is that Assembly references are resolved at **edition time**, whereas NuGet package references are resolved at **compile time**. With NuGet packages it's like quantum physics, you only know the actuall DLLs you get in your BIN folder, only when you compile for a specific platform.

Since we're not using the original NuGet packages, we have to do, manually, what NuGet does automatically.

This has been discussed before and I know there's the requirement to keep MonoGame from using any online resources....  but if that's the issue, and not using NuGets, then this can be solved by keeping the nuget packages in the dependencies repository, and referencing them with a local nuget config.

**Comment by Jjagg** [comment]
> the Net Standard assembly of SharpDX is just the "bait" assembly of the corresponding nuget packages

This is not true. If you look at SharpDX source, you'll see the .NET Standard assemblies do contain most of the code, but at some places conditional compilation is used to work around differences between UWP and Desktop, which caused this issue.

**Comment by vpenades** [comment]
@Jjagg the conditional compilation is used to produce multiple DLLs, take a look at the csproj of SharpDX [here](https://github.com/sharpdx/SharpDX/blob/master/Source/SharpDX/SharpDX.csproj) it does conditional compilation for net40, net45, netstandard1.1 and uap10.0 , and since its a SDK style csproj, it automatically generates all the DLLs for all these platforms.

This kind of csproj is the de-facto standard for creating bait-and-switch nuget packages. the Net.Standard assembly is used only to allow cross-platform compatibility _at edition time_. But when you compile a project, you target a specific platform, and it's at compile time when the net40, net45 or uap10 assemblies are copied to your bin folder.

**Comment by KakCAT** [comment]
I'm being affected by this bug too trying to port a game to XBox One. I'm trying to download version 900 or previous from teamcity but it seems older package versions are deleted. Is there any way to access version 900 other than teamcity?

**Comment by tomspilman** [comment]
> Is there any way to access version 900 other than teamcity?

@KakCAT - I rebuilt it for you...

http://teamcity.monogame.net/project.html?projectId=MonoGame&branch_MonoGame=5948&guest=1

**Comment by Jjagg** [comment]
I will fix this issue this weekend. Sorry for the delay!

**Comment by KakCAT** [comment]
Thanks @tomspilman ! It works :)

**Comment by dellis1972** [comment]
Closed via #6010
