### ISSUE TITLE
SamplerState.PointClamp, PointWarp not working

### ISSUE THREAD

**Issue by SParanagama** [MonoGame/MonoGame#6043]
I am trying to implement the pixelated/retro look in a small project. From what I've read, I have to disable texture filtering to get the pixelated look. Therefore, I used the following approaches:
1. Referred SamplerState.PointClamp in the spriteBatch.begin method and
2. Directly assigned the SamplerState in the draw() method using;
this.GraphicsDevice.SamplerStates[0] = SamplerState.PointClamp;

Both approaches fail when I view my output in fullscreen. The tile I am drawing appears very blurry.
I have attached a zip containing my project.

Platform: Windows 10
MG Version: 3.6
Graphics card: NVidia GTX 460
Project template: Monogame Windows Project
[WinDesktopPlatformer.zip](https://github.com/MonoGame/MonoGame/files/1450825/WinDesktopPlatformer.zip)

**Comment by Jjagg** [comment]
This is because of how the back buffer is upscaled to the full screen size. AFAIK DirectX does not allow you to specify how this should happen and I think it might be driver specific. 

To resolve this you can use a higher resolution back buffer. Render your game to a RenderTarget first, then when you've done all your rendering, draw the RT scaled so it fills the back buffer with point sampling enabled. That will fix your issue. 

I modified your Game1 file to use a render target and do proper scaling: https://gist.github.com/Jjagg/f6eb94ef687505ca468ff65240c26ebf

**Comment by tomspilman** [comment]
> AFAIK DirectX does not allow you to specify how this should happen and I think it might be driver specific.

Also you cannot specify this on other platforms like consoles or mobile devices.

> Render your game to a RenderTarget first,

Exactly... this is the correct way to control the filtering for a pixel art game.  It is how all the others you've seen do it.

**Comment by SParanagama** [comment]
Thanks so much @Jjagg  and @tomspilman 
It works!
