### ISSUE TITLE
MonoGameSetup 3.6.0.1625 - UWP Project creation failed in VS2017

### ISSUE THREAD

**Issue by jmroyb** [MonoGame/MonoGame#6049]
Hi folks,

I downloaded last setup (3.6.0.1625). I'm using VS 2017 15.4.3.

I received Project creation failed after platform selection (I selected both Fall Creators Update). 

Please can you help me?

**Comment by jmroyb** [comment]
Any update?

Is this project alive?

**Comment by Jjagg** [comment]
Yes, this project is very much alive :)

I think you haven't supplied enough information to troubleshoot. Maybe @DDReaper can help out.

**Comment by jmroyb** [comment]
No much information available. I updated to VS 2017 15.4.4 and reinstall MonoGameSetup 3.6.0.1625. Same error. Only sln is created but csproj is not created

**Comment by DDReaper** [comment]
Can you try the development release on the MG download page.
[MonoGame for Visual Studio](http://teamcity.monogame.net/repository/download/MonoGame_PackagingWindows/latest.lastSuccessful/MonoGameSetup.exe?guest=1)
I'm using this version without issue and it also includes all the latest fixes for the pending 3.7 release

**Comment by jmroyb** [comment]
@DDReaper I uninstalled old version 3.6.0.1625. Then I restarted computer and installed new version 3.7.0.1070. Now Monogame templates are missing

**Comment by DDReaper** [comment]
Well something is certainly off, as I have exactly the same setup, however, I have a MonoGame category with all the templates in.

Can you check in your "Documents -> Visual Studio 2017 -> Templates -> Project Templates -> Visual C#" folder and see if there is a MonoGame subfolder?

If so, you may need to run the devenv command to refresh the templates (which google will help with as I can't recall right now)

Unless you have a strange setup, no idea why the MSI is now not installing the templates, as that logic hasn't changes since 2003

**Comment by Jjagg** [comment]
@jmroyb You managed to fix this with DDReapers tips?

**Comment by jmroyb** [comment]
It did not work. I plan to format my pc an try again
