### ISSUE TITLE
ContentManager inside Game class null after Nuget Install

### ISSUE THREAD

**Issue by serramatutu** [MonoGame/MonoGame#6161]
So I'm pretty sure I've got my Monogame installed correctly because I can just do a git reset --hard and my code works just fine. 

I wanted to use the IntermediateSerializer, so I decided to download Monogame.Framework.Content.Pipeline.Portable from NuGet into my project. After compiling it again, the program throws an error inside the my Game1 class, stating that the "Content" property is null.

I've trying commenting out everything related to the ContentManager inside the constructor and after putting breakpoints inside my LoadContent, Update and Draw functions, it seems that none of them are called and the program just terminates without even opening a game window.

I've tried everything, but I think this is a MonoGame issue. The error occurs after installing the package, so it's not my code's fault

**Comment by cra0zy** [comment]
Monogame.Framework.Content.Pipeline.Portable is not a full content manager assembly, instead it's just a bait and switch one. If you want to use the actual content pipeline assembly you need to reference it from the Pipeline Tool install location.

Do note that the content pipeline only works on Windows, Mac and Linux so you can't use it from the remaining platforms.

**Comment by RonenNess** [comment]
I don't think that what he meant, I experience a similar issue: I opened a new MonoGame project, everything compiles fine and I have a content manager, but once I install the Monogame.Framework.Content.Pipeline.Portable nuget Content is always null after init. 
And I still have 'Content.mgcb' working and it can even build stuff, just the Game class doesn't create a Content manager. Running on windows.

**Comment by Jjagg** [comment]
@RonenNess 
@cra0zy is right. The Portable assemblies don't actually contain any implementation. They just provide the API surface so a library author can target them, but at runtime one of the real assemblies (e.g. Windows DX or DesktopGL) can take its place (bait-and-switch). You're never supposed to run a Game with a Portable assembly. 

I'm closing this, but feel free to ask for clarification :)

**Comment by RonenNess** [comment]
@Jjagg yes I understand that, but what I don't understand is if I already had a working implementation, why does merely adding a package removes that? Can't the API co-exist with the default content manager?

It doesn't sound right that adding a nuget removes another and breaks a working project..

Thanks k you for the answer :)

**Comment by Jjagg** [comment]
If you want to use the Content API in your game project you should reference the real assembly instead of the portable one. I'm not sure of the implementation details and why ContentManager is null, but it does not make sense to reference the portable assembly in an executable project because there's no implementation in it. In your executable game project you already have a specific MonoGame.Framework version, so you don't need the portable content assembly. Hope that makes sense.

**Comment by RonenNess** [comment]
@Jjagg yes it make sense, however what bothers me is that I *did have* a reference to an implementation and after adding the portable assembly it somehow got lost. That's what I don't understand.

To be clear this is what happened:
1. I opened a cross platform desktop application with a working content manager.
2. I actually built and loaded content with it, everything was working.
3. I added the "Monogame.Framework.Content.Pipeline.Portable" nuget, didn't remove anything and didn't change any code.
4. Now when I run it the Content manager provided by MonoGame's game class is null.

Why having a reference to an API remove althe reference to the implementation and breaks the game class? I would get your answer if I didn't have any implementation reference, but I did have on and it got lost.

I want to implement my own content pipeline but continue to use the default MonoGame Content manager on the side.

Thank you for the patience and explainations :)

**Comment by Jjagg** [comment]
> what bothers me is that I did have a reference to an implementation

An implementation of MonoGame.Framework, but not the content stuff. What I'm saying is, if you want a class library that uses the content stuff, use the portable assemblies. If you're including your custom content stuff in your executable game project, **don't use any portable assemblies because they don't have an implementation**. I think the portable content assembly depends on the portable framework assembly, and that might get preference due to how dependencies are resolved. You either want both the portable assemblies (for consumption in a class library that can be used from an executable game project targeting any MG platform, or for another class lib with the portable assemblies) or both real assemblies for your executable game so it actually has the runtime.

**Comment by RonenNess** [comment]
I see, thank you for the info! :)
