### ISSUE TITLE
Make MonoGame.net website use HTTPS instead of HTTP

### ISSUE THREAD

**Issue by aaronfranke** [MonoGame/MonoGame#6354]
There are many reasons to use HTTPS. It's not just about securing sites with login information. Sites using plain HTTP are prone to hijacking. It wouldn't be good if a malicious man-in-the-middle decided to inject ads or malware onto MonoGame.net. [Some ISPs also inject unwanted content into HTTP sites.](https://i.imgur.com/orYJCFW.png)

Services such as [Let's Encrypt](https://letsencrypt.org) make getting started with HTTPS fairly easy to do.

Once MonoGame.net has HTTPS support, it's also important to redirect users to the HTTPS version of the site if they load the HTTP version, to ensure that the users are using the secure version.

**Comment by guFalcon** [comment]
Nice suggestion.
Since there obviously already is a reverse proxy and people around here already work with docker (and docker-compose), I'd suggest using https://traefik.io/ as a reverse proxy. It has an implementation of the protocol of Let's Encrypt and does all the stuff automatically. You just have to do some configuration. If anyone needs help, I've just done that at setup work.

**Comment by aaronfranke** [comment]
@tomspilman This issue is still relevant and should be a higher priority. Both Chrome and Firefox display warnings (red padlock or "Not secure" text) when visiting HTTP sites. This will likely put off many users, and personally I can't take any website seriously if it's not HTTPS.

**Comment by Jjagg** [comment]
Happy to say this is finally resolved :)
