### ISSUE TITLE
New SpriteFont Kerning list can not be smaller than Character list

### ISSUE THREAD

**Issue by VampireMonkey** [MonoGame/MonoGame#6371]
When programmatically creating a new spritefont, the List of Kernings cannot be smaller than the character list, this is odd, since not all characters need to have kernings when working with for example windows fonts.

If the Kerning list is smaller than character list you'll get this exception :
System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index'

I've tracked it down to this line and the lines below it :
https://github.com/MonoGame/MonoGame/blob/55a577440769278a17d4574f05a48271197468d4/MonoGame.Framework/Graphics/SpriteFont.cs#L83

I'm using windows' "GetKerningPairs" and how i understand it to work, is that the font has a list of kernings it will apply to a string of characters when it checks that string with the kerning list.
So each character could have multiple kernings with multiple other characters.

But the way it's in MonoGame is strange, in the SpriteFont source code we can see that each character in a new SpriteFont has to have a kerning and only one.

This is how i get the kerningpairs of a font in windows (note that it's in vb.net):

 ```
 <StructLayout(LayoutKind.Sequential)>
    Structure KerningPair
        Public wFirst As Short
        Public wSecond As Short
        Public iKernelAmount As Integer
    End Structure

    <DllImport("gdi32.dll", SetLastError:=True, CallingConvention:=CallingConvention.Winapi)>
    Public Function GetKerningPairs(hdc As IntPtr, nPairs As Integer, <MarshalAs(UnmanagedType.LPArray, SizeParamIndex:=1)> <Out()> pairs() As KerningPair) As Integer
    End Function

    <DllImport("gdi32.dll")>
    Private Function SelectObject(hdc As IntPtr, hObject As IntPtr) As IntPtr
    End Function

    Public Function GetKerningPairs(Font As Drawing.Font) As IList(Of KerningPair)
        Using Graphics As Drawing.Graphics = Drawing.Graphics.FromHwnd(IntPtr.Zero)
            Graphics.PageUnit = Drawing.GraphicsUnit.Pixel

            Dim Pairs() As KerningPair
            Dim Hdc As IntPtr = Graphics.GetHdc
            Dim HFont As IntPtr = Font.ToHfont
            Dim Old As IntPtr = SelectObject(Hdc, HFont)
            Try
                Dim NumPairs As Integer = GetKerningPairs(Hdc, 0, Nothing)
                If (NumPairs > 0) Then
                    Pairs = New KerningPair(NumPairs - 1) {}
                    NumPairs = GetKerningPairs(Hdc, NumPairs, Pairs)
                    Return Pairs
                Else
                    Return Nothing
                End If
            Finally
                Old = SelectObject(Hdc, Old)
            End Try
        End Using
    End Function
```
Doing it this way will give kernings where one of the two pairs appear multiple times.

With the way kernings are used in MonoGame it seems better to use Vector3.Zero in the entire kerning list otherwise you'll be limited to one pair for each character, which have made it difficult to render text intuitively with a new SpriteFont, we also have to keep in mind that spacing is still applied too.

**Comment by stromkos** [comment]
Kernings in MonoGame are rendered as simple offsets that may be applied to a glyph when rendering. See [https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/SpriteBatch.cs#L681](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/SpriteBatch.cs#L681) 
As far as I know, true kerning does not exist within the framework.

Addressing this issue from a technical point of view, encoding hundreds to thousands of Kerning pairs or the GPOS(OpenType) equivalent would  probably just slightly less than double the XNB size, not to mention the new XNB format incompatibly with existing files and Renderer.

My "current" solution would be to prerender the text as an image **_OR_** propose a **cross platform** solution to the runtime font rendering issue #6324.

**Comment by VampireMonkey** [comment]
@stromkos Hmm, what about kerning on linux and osx, is there any way to get the kerning pairs in those os' like that in windows above?
If so, then it would only require 2 more functions to get the kernings of a specified font on all os'.
(Altho i'm pretty sure the font has to be installed for the above to work)

I've done what you're describing in a [WIP control for a project ](https://github.com/VampireMonkey/GeonBit.UI.Extensions/blob/633c553e45ff0034ddc6483f6cc8adf0e5236a7b/SelectFont.vb#L536), where i'm rendering the font characters to a bitmap then use that bitmap for the new SpriteFont, it works but the kernings are the only problem right now.

Alternatively if you could get the kernings from the font-file itself, that might work better. I'll have to look further into it and see what i can do.

**Comment by stromkos** [comment]
@VampireMonkey, I am very impressed with your grasp of multi-threaded .Net programming.  I would encourage you to accept C# as the predominant .Net language. I was there for VB versions 1-6, QBasic before that(we won't go further back...), and then .Net came out.  I wrote one application in VB.Net and then, I switched to C# as the .Net extensions imposed make more sense in a C like language.  
(This is a personal preference, even though the VB implementation leaves much to be desired, they both produce the same MSIL code)
Are you going for prerendered fonts or runtime fonts(not available yet,[I know this is possible on desktop platforms same as building spritefont files, as well as, on Android in a simplified form])? 
I have no solution to any of these cases, but it needs to be considered.

Are you limiting your application to include only MonoGame types?
If not, I would recommend creating your own SpriteFont like description file, and processor that either, 
-A. Includes all kerning info(both ttf and otf), or 
-B. (recommended, as it would not be font dependent) Utilize the existing Kerning Vector3, but instead of distances, encode left and right as slopes(+,-) of the Chars based on the min width vs max width.  At that point It would be a simple line/line intersection equation to position glyphs with kerning applied. While this approach would not be as accurate as true kerning tables, It is much better than the existing system.  This would solve your "Pr" solution with minimal impact to the rest of the framework.
Please note this type of solution may be incompatible with right-to-left and other writing systems. 

I believe SDL handles both Linux and OSX(someone correct me if I am wrong).  As such you should review the code in SDL for cross platform hints as to how fonts are handled.

As you know, Installable font permissions are hard to come by, therefore, I would recommend finding a solution that is acceptable to Windows font licensing(Embedable).

**Comment by VampireMonkey** [comment]
@stromkos I'll stick with VB.Net it's much more similar to some scripting languages i'm used to while modding certain games, and i wouldn't want a programming job anyways, i'd rather be independent.

At runtime, we'll render the fonts, then afterwards save them locally to be used instead of regenerating them again.
I saw someone on here talking about Chinese characters, you could render those at runtime and then add them to a pool of glyph in RAM, then save only those that appear most frequently, altho, i don't see how you're going to have any glyph rendered with the process i'm using in acceptable time and without lag(waiting for the font to render).
I guess a solution to that would be to render all the Chinese glyphs to local storage and then load partial fonts when needed, that way you can limit the amount loaded into ram and just have many fonts that only include certain ranges of glyphs, that would be an adequate way to solve the large range problem.

Well for font rendering it will only ever be with MonoGame, i am using GeonBit.UI as an easy way to implement a good gui fast and as far as i remember it only uses Spritefonts too.

Ye i thought of something similar, i'll have to look into that when i deal with fonts again.

The right-to-left display problem wouldn't be a problem for my applications as i only plan to support English.

Thanks for the chat tho!

**Comment by Jjagg** [comment]
@VampireMonkey 
I'm closing this because of the complications with modifying SpriteFont to better support kerning. I think the better path is to have a good runtime solution for projects that require more complex font rendering. 

For now, something we can fairly easily do for e.g. Chinese fonts is add support to the importer to render all characters occuring in specified text files.

I have been experimenting with [SixLabors/Fonts](https://github.com/SixLabors/Fonts). It has a ways to go, but looks promising and I'm gonna try to contribute myself. You could use it to get the kerning info you need. If you get to testing it, please do post back your results! I'd be interested to hear your thoughts :)
