### ISSUE TITLE
Provide a way to prevent closing of Monogame Window

### ISSUE THREAD

**Issue by monsieurmax** [MonoGame/MonoGame#6415]
Hello,

I'm currently writing a level editor in Monogame 3.7 Desktop GL.

I'd like to intercept window exiting to be able to let the user save his work or cancel exiting.
It is a pretty common feature, maybe not useful for games, but for other tools.

Right now, we can only perform some actions while the game is exiting, but not cancel it.

What would be nice is to have a method to overload that returns true or false, depending on wether the game is authorized to exit.

Thanks in advance.

**Comment by Jjagg** [comment]
We could have a flag in the `Game.Exiting` event argument that you can set to cancel exiting. That's simple to implement and a non-breaking way to implement this feature. Sorry for the extremely late response!

**Comment by tomspilman** [comment]
If we can do it properly and support at least all desktop platforms i guess it is ok.

My concern is that you cannot keep a mobile or console game from shutting down.  So this is exclusively a PC feature really.

**Comment by Jjagg** [comment]
Yes, we'll just be able to implement this for desktop. I guess this falls in the same bucket as #6392. 

For synchronous run loop we simply wrap [this code](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Game.cs#L397-L401) in a while loop with the stop condition that the new flag blocking game exit isn't set.

I'll have to look into async run loop.

**Comment by jcsnider** [comment]
@Jjagg: I created a PR for this above (#7096) ... My changes only impact the synchronous loops because it doesn't look like async run loops are supported for the [DesktopGL](https://github.com/MonoGame/MonoGame/blob/5a75f402acf32fbed9db56a118e64ad7bac1a567/MonoGame.Framework/Platform/SDL/SDLGamePlatform.cs#L258) and [WindowsDX](https://github.com/MonoGame/MonoGame/blob/5a75f402acf32fbed9db56a118e64ad7bac1a567/MonoGame.Framework/Platform/Windows/WinFormsGamePlatform.cs#L68) platforms.

As I mentioned in the PR I'm not sure if that's exactly how we should go about this, but I'm very happy to discuss and modify in order to get this to an acceptable state. Thanks!

**Comment by topnik-code** [comment]
I am in the same situation: I would like to intercept window closing under Desktop GL. 🙂

Are there any news on this issue? I would also be happy to get any tip regarding a workaround! 😸
