### ISSUE TITLE
 Content builder - File Stream Importer (First contribution discussion) 

### ISSUE THREAD

**Issue by vikingfabian** [MonoGame/MonoGame#6427]
I want to make a custom file importer for the Monogame Pipeline Tool. 
To allow something like this:
`System.IO.Stream file = Content.Load<System.IO.Stream>("myLevel");`

This will make it easier to load custom files where file access is restricted, like on the Xbox.

Is this something that will be an accepted addition to the source? 
(Im an experienced programmer, but never worked on an open source before)

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL, WindowsUWP, XboxONE

**Comment by Jjagg** [comment]
Hi @vikingfabian! Thanks for taking the time to write this down and wanting to contribute to MonoGame :) 

> This will make it easier to load custom files where file access is restricted, like on the Xbox.

So basically, the purpose is a cross-platform function to open a stream given a file name or asset name, in a way that makes sense for the respective platform? What would you expect this function to do on e.g. Xbox? I know we already need special handling on Android to load assets. Not sure if this functionality should go in ContentManager if it's approved, because ContentManager specifically handles .xnb files (in fact, it loaded non-processed files before but that functionality was removed).

cc @tomspilman @dellis1972

**Comment by tomspilman** [comment]
> So basically, the purpose is a cross-platform function to open a stream given a file name or asset name, in a way that makes sense for the respective platform?

See `TitleContainer.OpenStream(Stream)` that already does this.

Is this all you're looking for @vikingfabian ?

**Comment by tomspilman** [comment]
Go ahead and reopen this if you need to @vikingfabian .
