### ISSUE TITLE
KeyBoardState GetKeysPressed method is being collected generating garbage every call.

### ISSUE THREAD

**Issue by willmotil** [MonoGame/MonoGame#6602]
Windows Gl crossplatform desktop tested while windowed.
This is probably the same on Dx.

_I don't think this is the same as 6601 as i tested that without even using keyboard at all and it is constant.
This varys with the amount of times its called per minute and the state of the keyboard._

In the class keyboardstate here.
https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Input/KeyboardState.cs

The method GetPressedKeys() which returns a Array of Keys which are structs is generating garbage.

The following code generates tons of garbage with fix timestep off. This does build to collections.
With it on at 60 frames per second its not too bad it will generate a collection every minute or so.

```
        KeyboardState kb = new KeyboardState();
        protected override void Update(GameTime gameTime)
        {
            // test
            kb = Keyboard.GetState();
            Keys[] keys = kb.GetPressedKeys();  // the array of struct keys goes out of scope and gets collected 
            base.Update(gameTime);
        }
```

The problem with this is in any game were you might allow the user to assign or use control group keys.
Strategy games often do this and really any game were you want to allow the user to assign arbitrary hotkeys or control groups.
This is the only monogame way to really do this, as text input isn't made for this idea.

You normally check that any keys are pressed first by getting this method. 
Checking if its length is more then zero you then procced to process the keys pressed instead of checking for every single possible key combination with getstate which would be insane.

Simply calling this method creates garbage.
Since it is a array of keys and keys are structs. It appears to be boxing and unboxing.

The couple methods associated with it have a number of odditys which appear redundant and overly complex. All for the sake of apparently avoiding garbage which it doesn't do.

Ill post my notes i took while looking it over.

```
        // All three methods associated with GetPressedKeys are heavily using bitwise math to count bits.
        // https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Input/KeyboardState.cs
        // The array is returned after being populated in .... KeyboardState.GetPressedKeys.
        // It populates the array primarily by calling  ... AddKeysToArray(uint keys, int offset, Keys[] pressedKeys, int index)
        //
        // 256 bit flags are being stored across 8 32 bit unsigned integers they are being treated as a bit array.
        //
        // Array of 256 bits:
        // uint keys0, keys1, keys2, keys3, keys4, keys5, keys6, keys7;
        //
        // It is based on this which seems out of place here.
        // http://graphics.stanford.edu/~seander/bithacks.html#CountBitsSetParallel
        //
        // The count method is only used so that a keys struct array of the correct length can be created.
        // There is no way for the user to make use of the count even though this has been calculated.
        // It generates garbage by calling the method since this is a array of structs boxing must be occuring.
        // 
```

**Comment by Jjagg** [comment]
> The method GetPressedKeys() which returns a Array of Keys which are structs is generating garbage.

The API returns an array. The only allocation that's being made is the array that's returned. It's optimal considering the API. IMO we don't need it, but we could add an alternative API that let's the user pass in an array so we don't allocate.

> Checking if its length is more then zero you then procced to process the keys pressed instead of checking for every single possible key combination with getstate which would be insane.

It is not insane to do that, really. Using `IsKeyDown` instead of `GetPressedKeys` is very reasonable.

> Since it is a array of keys and keys are structs. It appears to be boxing and unboxing.

This is wrong. Keys are enum values, which are value types. There's no boxing when you create an array of value types.

> The couple methods associated with it have a number of odditys which appear redundant and overly complex. All for the sake of apparently avoiding garbage which it doesn't do.

I agree the methods don't need the complexity for the speed boost. But it's implemented that way and it's working. IMO it's fine to leave it as is. The bit stuff implementation is not to prevent allocations but for perf. Like I said, there are no unnecessary allocations given the API.

> There is no way for the user to make use of the count even though this has been calculated.

It's the length of the array. Of course the user can access it.

**Comment by Jjagg** [comment]
> you will need somewere up to 20 if checks every single update just for that feature

That's still negligible.

> That's the question, how can a array of value types be creating garbage ?

Arrays are allocated on the heap.

Yes, we could use a list internally. I don't know why an array the size of the keys enum is used. Most likely because that's how Windows handles getting pressed keys. Even with a list we'd need to allocate the array.

Again, the way it's implemented with bit operations is completely unrelated to the allocation. The allocation is necessary to fit the API. If it's an issue we should add new API.

**Comment by tdeeb** [comment]
PR https://github.com/MonoGame/MonoGame/pull/6643 has been merged, which adds an overload that takes a pre-allocated array into `GetKeysPressed`.

**Comment by cra0zy** [comment]
Honestly with C# 7 we could return a readonly ref to our own private Keys[] list instead, but that is a story for MG 5, gonna close this for now.
