### ISSUE TITLE
Basic Effect is Nothing

### ISSUE THREAD

**Issue by TheFatTurtle** [MonoGame/MonoGame#6613]
#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by TheFatTurtle** [comment]
When I try to work with models and create a New ModelMeshPart and want to give it as effect( MeshPart.Effect = Basic Effect) I get the message MeshPart.Effect Is Nothing
I can't change the Effect.

**Comment by Jjagg** [comment]
We'll need more information for this, because I don't understand what's up.

@TheFatTurtle Could you set up a project that reproduces this error?

**Comment by TheFatTurtle** [comment]
i made a project.
in this project i initialized a new model with the name ModelA
to make a model i need a modelpart.
so i defined modelpartA as new modelpart
i defined basiceffectA as basiceffect
i tried to set the effect of modelparta  to basiceffectA:
                 modelparta.effect = basiceffectA 
this is were i got the message: "NullReferenceExcepion: meshpart.effect is nothing"

**Comment by Jjagg** [comment]
Building a model at runtime is not supported. The `ModelMeshPart` constructor should not be public. There's no way to add meshes to a model at runtime.

If I got this right, the exception occurs because `ModelMeshPart` assumes its parent is not null, which of course it is if you create one using the default constructor.

**Comment by TheFatTurtle** [comment]
Okay. Thanks for answering so quick
