### ISSUE TITLE
How to build VS2017 extension from source?

### ISSUE THREAD

**Issue by ejamshidiasl** [MonoGame/MonoGame#6626]
Hello
i built MonoGame.Framework.Windows.sln but i can't find DLL files.where are they?
And how to pack it as vs2017 extension?

**Comment by Jjagg** [comment]
MonoGame only adds project templates to visual studio, there currently is no VS extension.
The visual studio project templates are in the [ProjectTemplates](https://github.com/MonoGame/MonoGame/tree/develop/ProjectTemplates) folder.

@ejamshidiasl For questions, please use our [gitter channel](https://gitter.im/MonoGame/MonoGame) or [forum](http://community.monogame.net/) instead of opening an issue. We use issues for bug reports and feature requests.
