### ISSUE TITLE
Protobuild domain taken over

### ISSUE THREAD

**Issue by oblotzky** [MonoGame/MonoGame#6649]
Hello,

it appears to me that the process of building the solution/project files through Protobuild.exe is currently broken. I get a bunch of 404 errors when trying to run the .exe as it pings home to protobuild.org to get more stuff, which makes sense because that domain now belongs to some social media exposure boosting abomination. Are any alternatives available at this time?

Thank you

**Comment by Jjagg** [comment]
Well, this sucks. We better speed up #6207. I just set up a WIP pull request to remove Protobuild #6650.
You can use that to build DesktopGL or Windows DirectX projects.

I can't replicate this, probably because the build files are cached somewhere (and I'll not remove them just so I can keep building from source).

cc @tomspilman @cra0zy

**Comment by mrhelmut** [comment]
Probably worth pinging @hach-que :)
Maybe the protobuild.org hosted files could be moved to a github hosted site?

**Comment by oblotzky** [comment]
I think Protobuild is trying to update itself first or so, not fetching MonoGame related files.

I've also opened an issue on the Protobuild github page so they can fix it on their end. Looks like the domain change occured earlier this year according to a whois.

**Comment by hach-que** [comment]
Hey folks, this is because MonoGame has an ancient version of Protobuild. The dependency on the website that is causing this issue was removed in January 2017. I'd recommend upgrading the executable.

In particular what's happening here is when you pass no arguments to the version of Protobuild you are using, it tries to download and launch the Protobuild Manager from the very old Protobuild Index. In January 2017 we moved that dependency over to NuGet so the app didn't rely on us hosting online infrastructure for eternity.

This is only an issue if you run your current version Protobuild with no arguments, in a directory that doesn't have a Protobuild project set up.

**Comment by hach-que** [comment]
Specifically, the scenario is this:

- You run the current version of Protobuild that MonoGame is shipping, outside the MonoGame directory. In this case based on the logs the user provided, they're running it while in their `C:\Users\USERNAME` directory.
- Protobuild goes "I don't have a project here, so I don't know what to do. I wasn't provided any arguments, so I'll launch the interactive GUI so the user can do something sensible".
- The GUI isn't built in (to reduce dependencies), so it tries to download it before launching it.
- Because the version of Protobuild is so old (before January 2017), it tries to download it from the Protobuild Index instead of NuGet, which fails because the website is no longer available.

Any one of the following actions will resolve this issue:
- Upgrading Protobuild to a newer version.
- Running `cd` to the MonoGame project directory before invoking Protobuild.
- Providing arguments or `-help` to Protobuild when running it on the command line if you're running in a directory without a project.

Personally I'd recommend just updating MonoGame to the latest version to reduce user confusion, since it should all still be compatible with what you're doing in MonoGame.

**Comment by oblotzky** [comment]
Yep, I got it working now. Thanks for the help, and sorry for the fuzz. I guess a update for the Binary is in order then until the team has figured out if they want to move forward with Protobuild in the future as that seems to be a topic already.

**Comment by Jjagg** [comment]
Thanks @hach-que. I'll set up a PR to update Protobuild.
I recall upgrading Protobuild before and I believe it sped up generation a bit as well.

> until the team has figured out if they want to move forward with Protobuild in the future

The decision has been made for a while, we're removing Protobuild, but it might take some time.

**Comment by Jjagg** [comment]
Upgrading breaks a lot of the xslt, not as easy as I thought.

**Comment by harry-cpp** [comment]
We no longer depend on Protobuild.
