### ISSUE TITLE
Black rectangles when drawing non power of 2 textures using SamplerState.LinearWrap on iOS

### ISSUE THREAD

**Issue by AidanMcK** [MonoGame/MonoGame#6659]
In iOS, If you try to draw a texture that does not have a power of two size and use SamplerState.LinearWrap, a black box is drawn.

Here's  some screenshots of the problem. Using SamplerState.LinearWrap:

![screen shot 2019-02-11 at 12 04 29](https://user-images.githubusercontent.com/19970935/52562898-d8dc5080-2df7-11e9-8e7d-eee53d4c198d.png)

Using SamplerState.LinearClamp:

![screen shot 2019-02-11 at 12 05 32](https://user-images.githubusercontent.com/19970935/52562929-ee517a80-2df7-11e9-856f-fc3f8a5a795f.png)

The code used is a new MonoGame for iOS project with just the addition of loading and drawing four different sized textures:

```
private Texture2D[] _textures = new Texture2D[4];

protected override void LoadContent()
{
    // Create a new SpriteBatch, which can be used to draw textures.
    spriteBatch = new SpriteBatch(GraphicsDevice);

    //TODO: Use Content to load your game content here 

    for (int i=0; i<4; i++)
    {
         var fileStream = TitleContainer.OpenStream("Content/Main/LayoutTest" + (i+1).ToString() + ".jpg");
        _textures[i] = Texture2D.FromStream(GraphicsDevice, fileStream);
        fileStream.Dispose();
    }
}

protected override void Draw(GameTime gameTime)
{
    graphics.GraphicsDevice.Clear(Color.CornflowerBlue);

    //TODO: Add your drawing code here

    int bx = 5;
    int by = 5;
    int w2 = Window.ClientBounds.Width / 2;
    int h2 = Window.ClientBounds.Height / 2;
    int w  = w2 - bx - bx;
    int h  = h2 - by - by;

    Rectangle[] r = new Rectangle[4]
    {
        new Rectangle(bx,      by,      w, h),
        new Rectangle(w2 + bx, by,      w, h),
        new Rectangle(bx,      h2 + by, w, h),
        new Rectangle(w2 + bx, h2 + by, w, h),
    };

    for (int i=0; i<4; i++)
    {
        spriteBatch.Begin(SpriteSortMode.Deferred, null, SamplerState.LinearClamp, null, null, null, null);
        // spriteBatch.Begin(SpriteSortMode.Deferred, null, SamplerState.LinearWrap, null, null, null, null);
        spriteBatch.Draw(_textures[i], r[i], Color.White);
        spriteBatch.End();
    }

    base.Draw(gameTime);
}
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.305

#### What operating system are you using:
- Mac OS X

#### What MonoGame platform are you using:
- iOS

**Comment by AidanMcK** [comment]
This problem was discussed back in 2014 in relation to problems running on Android and apparently fixed, some mention of problems in ESTexture2D.cs - see a post in StackOverflow [here](https://stackoverflow.com/a/11765540).

**Comment by AidanMcK** [comment]
FYI, I've tested this on Android also and the problem does not show up, so it seems to be iOS specific.

**Comment by Mathetis** [comment]
Any updates on this one? Definitely iOS specific. I can confirm it happens with LinearWrap.

**Comment by tomspilman** [comment]
> I've tested this on Android also and the problem does not show up, so it seems to be iOS specific.

Interesting... not sure what about our OpenGL implementation there would be platform specific.

**Comment by Mathetis** [comment]
Is it possible that iOS does not support this? I was trying this on an iPhone 5s.

"In OpenGL ES 2.0, textures can have non-power-of-two (npot) dimensions. In other words, the width and height do not need to be a power of two. However, OpenGL ES 2.0 does have a restriction on the wrap modes that can be used if the texture dimensions are not power of two. That is, for npot textures, the wrap mode can only be GL_CLAMP_TO_EDGE and the minifica- tion filter can only be GL_NEAREST or GL_LINEAR (in other words, not mip- mapped). The extension GL_OES_texture_npot relaxes these restrictions and allows wrap modes of GL_REPEAT and GL_MIRRORED_REPEAT and also allows npot textures to be mipmapped with the full set of minification filters."
https://stackoverflow.com/questions/11557382/opengl-es-2-0-texture-mapped-but-shows-as-black

I looked at the Monogame implementation for SamplerState.OpenGL and Texture2D.OpenGL.  It does appear that Monogame sets the texture parameters are set to clamp, but the sampler state uses Repeat. I suppose if the implementation did not support repeat for npot, than we would get black.

See also here: https://stackoverflow.com/questions/11069441/non-power-of-two-textures-in-ios

Also, it looks like this was the expected behavior prior to the npot extension?

"    This extension adds support for the REPEAT and MIRRORED_REPEAT
    texture wrap modes and the minification filters supported for
    non-power of two 2D textures, cubemaps and for 3D textures, if
    the OES_texture_3D extension is supported.

    Section 3.8.2 of the OpenGL ES 2.0 specification describes
    rules for sampling from an incomplete texture. There were specific
    rules added for non-power of two textures i.e. if the texture wrap
    mode is not CLAMP_TO_EDGE or minification filter is not NEAREST or
    LINEAR and the texture is a non-power-of-two texture, then sampling
    the texture will return (0, 0, 0, 1).

    These rules are no longer applied by an implementation that supports
    this extension."

https://www.khronos.org/registry/OpenGL/extensions/OES/OES_texture_npot.txt

**Comment by mrhelmut** [comment]
The OpenGL implementation of iOS does not support wrapping (being point or linear) on non-power-of-two textures. The sampler will always return pure black in that case. This is the expected behavior of OpenGL on iOS.

**Comment by AidanMcK** [comment]
This may be the expected behavior of OpenGL on iOS, but it is not the expected behavior of MonoGame, and developer using MonoGame as a cross-platform solution probably does not know this. Maybe an exception should be thrown if trying to set wrapping on a non-power to two texture? Or somewhere else? I believe MonoGame throws exceptions in other scenarios where certain functionality is not available on a specific platform.
