### ISSUE TITLE
SharpDX Retired

### ISSUE THREAD

**Issue by tdeeb** [MonoGame/MonoGame#6691]
The [official SharpDX repository](https://github.com/sharpdx/SharpDX) states that the project is no longer active or maintained as of March 29, 2019. Since WindowsDX (and Xbox One?) projects use it to render via the DirectX API, any bugs tracing down to SharpDX won't be addressed by the maintainers. What should we do about this going forwards?
@tomspilman @cra0zy @Jjagg

**Comment by amerkoleci** [comment]
https://github.com/sharpdx/SharpDX/issues/1138

**Comment by tomspilman** [comment]
> any bugs tracing down to SharpDX won't be addressed by the maintainers.

The good news is very very few of those exist.

And if we run into issues we can choose to go fix it ourselves.

So at this point it isn't a huge concern.

What will be interesting is what happens post DX12.

**Comment by nathan-alden** [comment]
I'm concerned about this, as well. I just started work on a game engine and I'm already knee-deep in SharpDX. This is making me question whether I should throw away the SharpDX code and port the whole client to Visual C++.

Someone--or some org--needs to take ownership of the project, or at least fork it and become the "new" owner. SharpDX is an _excellent_ library and it would be a shame if the project just died.

Does Microsoft have a process where people can request they take ownership of projects such as this?

**Comment by tomspilman** [comment]
> Someone--or some org--needs to take ownership of the project,

Agreed... but I highly doubt Microsoft will do it.

It will be up to the community that already uses the project to maintain it.

I expect with the MG team needs a fix one of us will fix it and submit the PR and it will get merged.

**Comment by amerkoleci** [comment]
As I said on SharpDX forums and else where, I'm working on new DirectX bindings (https://github.com/amerkoleci/SharpWindows)

**Comment by tomspilman** [comment]
> I'm working on new DirectX bindings 

That is great.  If we ever decided SharpDX isn't working for us we would consider it.

**Comment by slmyyy** [comment]
This is really unfortunate.  I've invested heavily in SharpDX.  Wouldn't it make more sense to fork SharpdDX and redirect efforts there?

**Comment by tomspilman** [comment]
Going to close this issue for now as it isn't really serving any purpose.

There is nothing to worry about here.

SharpDX works just fine today and is 100% open source so we can create fixes when we need to.

**Comment by damian-666** [comment]
thanks. for some of the tips in this.. mabye youcould advise me if i should also just grab sharp dx build and try to find or fix it.    or if building monogame will be worth the overhead  since its been a while.     I'm using WPF interop wpf wpf for level editing , everything was fine until i ditched 48 and netsttandard so i could upgrade monogame, and im  hopelessly stuck for weeks since the MG 3.81 update pushed my wpf app to net 6.. (windows only, whch  is fine)    the issues are sharpDX related i think. ( cant create a Texture shared handle)  those  two good samples aren't maintained either.   But i easily can update the sample to netcore6 windows and MG. 3.81 , that i updated with a PR.. ( untaken, as if tis not relevant or abandoned) but  they both work. in that context, even with tab adn docking.    i want to trace deep but i  might rather go to Silk .net or something else.. Anhy suggestions?  I just want to stick an MG render target in as a wpf backing store in a tabbed window.. the samples work but they are so Naunced with load order, im dyng from this.   Should  i take the time to get the sharp dx code and trace it?   I cant get a changed texture handle from a  texture ..i get Method not [System.MissingMethodException: ‘Method not found: ‘IntPtr Microsoft.Xna.Framework.Graphics.Texture.GetSharedHandle()’.’]  Avalonia and Myra do not even build now so im lost and i only need it to work on windows for now. 
 i just wanan update to MG. 3.8.1 and release a simple part of my game, before i die.

**Comment by mrhelmut** [comment]
#4571
