### ISSUE TITLE
Backwards compatibility problem caused by #6682

### ISSUE THREAD

**Issue by AimedNuu** [MonoGame/MonoGame#6708]
https://github.com/MonoGame/MonoGame/pull/6682
Hi, it actually broke some compatibility with EmptyKeys GUI framework. Bad thing is that its source code is not open. But with this version of code and EmptyKeysUI_MonoGame version 3.1.0 from nuget I get
`Method not found: 'Void Microsoft.Xna.Framework.Graphics.SpriteBatch..ctor(Microsoft.Xna.Framework.Graphics.GraphicsDevice)'."} | System.MissingMethodException`

This happens when I call MonoGameEngine constructor which initialize EmptyKeys GUI stuff and creates SpriteBrach instance(s) internally.
My assumption is that method signature within MonoGame.Framework.dll changes enough to break compatibility at least for EmptyKeys but it might be the same case for more libraries out there.

**Comment by Jjagg** [comment]
We could have added an overload instead of adding a default parameter to prevent this from breaking. We can (and IMO should) still revert the change and add an overload instead.

More info: https://stackoverflow.com/a/9884700 
The change is not backwards compatible because the method signature is changed. It does not matter that the added argument has a default value if the method can't be found.

cc @mrhelmut

**Comment by tomspilman** [comment]
> We could have added an overload instead of adding a default parameter to prevent this from breaking.

Yeah i guess i should have expected that.  Default parameters are a responsibility of the caller and just a helper in the C# compiler.  So we broke existing libraries by adding a default parameter instead of a new function.

Can someone submit a fix?

**Comment by mrhelmut** [comment]
I'm on it, didn't expect reflection to fail here.

**Comment by mrhelmut** [comment]
Here we go #6709.
