### ISSUE TITLE
Documentation switches variable name from 'textureBall' to 'ballTexture' between two lessons

### ISSUE THREAD

**Issue by DDSuarez** [MonoGame/MonoGame#6722]
In the [Adding Content](http://www.monogame.net/documentation/?page=adding_content) page, we create a `textureBall` variable. Only to then change the name in the next section, [Adding Basic Code](http://www.monogame.net/documentation/?page=adding_basic_code), to `ballTexture`.

Recommend making the variable name in the Adding Content page `ballTexture` for consistency.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by nkast** [comment]
In the "Adding basic code" one should use 'graphics.Viewport.Width' instead of 'graphics.PreferredBackBufferWidth', same for Height.

additionally the initialization of 'ballPosition' should go after 'base.Initialize()' when everything related to the backbuffer and the window are initialized (graphics.PresentationParameters / Window.Bounds / graphics.Viewport,etc)
