### ISSUE TITLE
Please add indexed texture support.

### ISSUE THREAD

**Issue by Shadowblitz16** [MonoGame/MonoGame#6733]
Please add support for the following texture formats and a why to draw them and edit their 
palette data:
- Black and White
- Indexed 1bpp
- Indexed 2bpp
- Indexed 4bpp
- Indexed 8bpp

Reasons why this should be added:
- Proper indexed textures are hard to support through shaders in a way they can be properly loaded, saved and edited from one format to another.
- Visual studio supports these image formats in the IDE proving that they can be made on newer 
 hardware 
- These can be used to easily create retro style games in which are still quite popular.
- This would make monogame stand out from other game engines

Current specs:
- MonoGame 3.7
- Windows 7 64 bit Home
- MonoGame DesktopGL

**Comment by tomspilman** [comment]
Other than some special features in older console hardware (PS1,PS2,Vita,Gameboy,etc) i don't believe any modern GPUs have any built in support for index color textures.

The way to achieve this on a modern GPU is to write a custom shader.   Your texture encodes the index and in the pixel shader you read the palette color from either a second 1D texture or uniform constants.

Note that most retro games we've ported only use index color for art creation and storage.  Once loaded from disk at runtime they usually load the color into fully uncompressed 32bit or 16bit per pixel textures.  Yes it is inefficient, but these games rarely have so much texture data that it matters.

That said... Mercenary Kings on Vita needed the memory savings as Vita has only around 300MB for your entire game.  Some levels were too big in memory so we had to use the special index color texture support Vita had built in...  it saved our asses.  That said... nothing these days is that small.

**Comment by Jjagg** [comment]
I agree with Tom. If you want to render from indexed textures, use a shader. If it's about memory, use compresses textures or stop caring about memory so much (the modern solution). I'll address your why's (repeating some of what Tom said):

> Proper indexed textures are hard to support through shaders in a way they can be properly loaded, saved and edited from one format to another.

It's no easier to do without shaders. In fact it's harder because of the different graphics APIs that don't all support directly rendering indexed textures. That means in some (I think most) cases MG has to convert to full RGB or use a shader itself anyway.
For loading/saving I can recommend ImageSharp. Gifs use indexed colors, so that's a good way to go. ImageSharp let's you get the palette and indices from the image without directly converting to RGB.

> Visual studio supports these image formats in the IDE proving that they can be made on newer hardware

When we say hardware support, in this context it means native rendering in graphics APIs like OpenGL and DirectX. Without it there isn't much value to supporting indexed textures because they need to be decompressed anyway, so it only positively affects file size (and negatively affects texture load time). VS supporting indexed formats doesn't mean anything for GPU support.

> These can be used to easily create retro style games in which are still quite popular.

Hardware support for indexed textures doesn't matter for getting the end result to look retro. There's multiple ways to get there. Maybe google 'posterization shaders' (basically rounding your colors to a palette in a post processing step).

> This would make monogame stand out from other game engines

It's a pretty small feature to have and rarely requested so I don't think so. 

It's very complex to support natively rendered indexed textures well for MG, while it's easy for users to implement. So I'm gonna close this.
