### ISSUE TITLE
OS getting detected as Linux not Mac for Hardened Notarized release versions

### ISSUE THREAD

**Issue by AidanMcK** [MonoGame/MonoGame#6816]
After going through the convoluted process of getting an app notarised so it can run on Mac OS X 10.15 Catalina, a problem popped up for some people:

> System.TypeInitializationException: The type initializer for 'Keyboard' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Sdl' threw an exception. ---> System.DllNotFoundException: libdl.so.2 at (wrapper managed-to-native) MonoGame.Utilities.FuncLoader+Linux.dlopen(string,int)

As you can see "Linux.dlopen" was being called and not the Mac function.

Lots of delving later I discovered the problem to be in CurrentPlatform.cs, in the DLLImport call for uname:
```
[DllImport ("libc")]
static extern int uname(IntPtr buf);
```
The call to uname was causing a dll not found crash. The full path needs to be specified for Macs to cover this problem.

Note I could not reproduce this problem but many of my customers could. I believe its connected to the fact that you have to do a hardened codesign and codesign the individual dylib libraries also in the MonoBundle part of the application.

I used the following to fix the code and keep it working for Linux also.
Replace the DllImport call with:
```
[DllImport ("libc", EntryPoint="uname")]
static extern int unameNoPath(IntPtr buf);
[DllImport ("/usr/lib/libc", EntryPoint="uname")]
static extern int unameWithPath(IntPtr buf);
```
and the uname() call with:
```
int unameResult;
try {
   unameResult = unameNoPath (buf);
} catch {
   unameResult = unameWithPath (buf);
}
if (unameResult == 0) {

```

There is also a bug in the file just after the uname() call - the return needs to be removed after the line 
```
os = OS.MacOSX;
```
and instead add a check before the switch break:
```
if (os == OS.MacOSX)
   break;

os = OS.Linux;
break;
```

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Mac OS X

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Jjagg** [comment]
Oof, that's a tricky issue. It's great that you figured out the cause!
The proper fix probably needs to happen in Mono (mono/mono#15333).

I'm good with merging the workaround. It's probably not 100% robust, but at least it's better than what we have now.

**Comment by mrhelmut** [comment]
I don't know if Mono is going to address dllimport path directly in the runtime so I guess it's pretty safe to go with this workaround.

**Comment by akoeplinger** [comment]
Mono dev here, this is because you're missing the `com.apple.security.cs.allow-dyld-environment-variables` entitlement when `codesign`'ing the mono binary. Without it you can only p/invoke into libc using the full path, with it enabled you can use just the library name like before.

On Mono we currently add these entitlements, if you distribute your own mono binary you probably want to use the same:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>com.apple.security.cs.allow-jit</key>
		<true/>
		<key>com.apple.security.cs.allow-unsigned-executable-memory</key>
		<true/>
		<key>com.apple.security.cs.allow-dyld-environment-variables</key>
		<true/>
		<key>com.apple.security.cs.disable-library-validation</key>
		<true/>
	</dict>
</plist>

```

**Comment by mrhelmut** [comment]
Ah! Thanks for dropping by.

(I need to check how to codesign MonoKickstart).

On a related note, this is kind of similar to ```Environment.OSVersion.VersionString``` on Windows, which is always returning the current OS to be Windows Vista unless you have a .manifest file specify OS compatibilities.

**Comment by akoeplinger** [comment]
You also need to enable hardened runtime (by passing `-o runtime` to `codesign`) otherwise the notarization service will reject it. Let me know if you have questions.

**Comment by mrhelmut** [comment]
I'd like to encourage having this workaround in MonoGame asap.

I've read a lot about Catalina lately and it's going to be a big giant mess. We need to account for games which are going to run on entitlement-less/non-signed environments (because not every dev will be willing to use XCode for signing and notarizing).

**Comment by Jjagg** [comment]
If anyone can set up a PR, I'll merge it in :)

**Comment by cra0zy** [comment]
Instead of all of this, there is a much simpler solution I would say (we just need to pick which one):
- Check if the system is Linux, if not, its a Mac
- Use the following method, requires setting net framework version to net471: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.isosplatform

**Comment by mrhelmut** [comment]
I would go for the first one for backward compat'.

Also, would considering that a missing libc is most likely a Mac too big of a hack?

**Comment by akoeplinger** [comment]
IMHO making some workarounds is not worth the trouble and you'd be at risk of us silently introducing another dependency in the BCL. Apple will no doubt increase the pressure on enforcing  hardened runtime usage so better to get the entitlements in place.

**Comment by mrhelmut** [comment]
For sure. Though I believe we should still come up with a temporary solution because getting the runtime right might take longer.

I don't have access to a recent Mac to codesign MonoKickstart, and we're not yet fully .Net Core ready (is .Net Core even signed with the hardened entitlements? what about single-file publish?).
