### ISSUE TITLE
2mgfx.exe: invalid vs_3_0 input semantic 'SV_VERTEXID'

### ISSUE THREAD

**Issue by numberoverzero** [MonoGame/MonoGame#6833]
I'm trying to use `SV_VERTEXID` in a shader[0] with `Profile:OpenGL` and vertex shader `vs_3_0` but it's failing to build:

```
struct vsi
{
	float2 Position : POSITION0;
};
struct vso
{
	float4 Position : POSITION0;
	float2 TexCoord : TEXCOORD0;
};

vso VertexShaderFunction(vsi input, uint id:SV_VERTEXID)
{
	vso output;
	output.Position = float4(input.Position, 0, 1);
	output.TexCoord.x = (float)(id / 2) * 2.0;
	output.TexCoord.y = 1.0 - (float)(id % 2) * 2.0;
	return output;
}

technique Technique
{
	pass Pass1
	{
		VertexShader = compile vs_3_0 VertexShaderFunction();
	}
}  /* Problem.fx */
```

```
> "C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\2mgfx.exe" Problem.fx Problem.mgfxo /Profile:OpenGL
Problem.fx(11,44-55): error X4502: invalid vs_3_0 input semantic 'SV_VERTEXID'

Failed to compile 'Problem.fx'!
```

https://docs.microsoft.com/en-us/windows/win32/direct3d11/d3d10-graphics-programming-guide-input-assembler-stage-using#vertexid
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/gl_VertexID.xhtml

[0] for example, a triangle for full screen post-processing effects:
https://www.reddit.com/r/gamedev/comments/2j17wk/a_slightly_faster_bufferless_vertex_shader_trick/
https://github.com/Kosmonaut3d/DeferredEngine/blob/f772b53e7e09dde6d0dd0682f4c4c1f1f6957b69/EngineTest/Content/Shaders/BloomFilter/Bloom.fx#L33
https://github.com/Kosmonaut3d/DeferredEngine/blob/f772b53e7e09dde6d0dd0682f4c4c1f1f6957b69/EngineTest/Renderer/Helper/FullScreenTriangle.cs#L35-L51

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7.1.189

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by Jjagg** [comment]
VERTEXID is only supported from Shader Model 4 onward, i.e. not in DirectX 9 compatible shaders. https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-semantics

MojoShader - the tool we use to cross compile to OpenGL - only supports Shader model 3 and lower. Unfortunately there's no easy way to support this feature right now, but there are ways for users to work around it so I don't think it's that big of a deal. I'm gonna close this issue, though we might be able to support this feature once we upgrade the shader pipeline.

**Comment by numberoverzero** [comment]
Thanks for the answer!

> but there are ways for users to work around it so I don't think it's that big of a deal.

Can you expand on this a bit?  I'm not sure if that means there are workarounds to use sm4, or workarounds to use opengl shaders directly.  I'd be happy to explore either but came up short when looking through the documentation.  I checked the following links:

* [Custom Effects](http://www.monogame.net/documentation/?page=Custom_Effects)
* [2MGFX](http://www.monogame.net/documentation/?page=2MGFX)
* [Pipeline](http://www.monogame.net/documentation/?page=Pipeline)

**Comment by Jjagg** [comment]
I meant you don't *need* VERTEXID. You can make your shaders have the same effect without it (albeit somewhat less convenient or less performant in some cases).

**Comment by numberoverzero** [comment]
I've got a workaround for this specific case (rendering a full screen quad) but I imagine some of the additional features in Shader Model 4 could be useful.  Since it doesn't look like sm4 is high priority[0], is there at least a hacked-together-and-totally-not-supported sideloading process that would let me use OpenGL directly?  Or will monogame only support shaders that can be compiled with 2mgfx for the forseable future?

Thanks again for the quick answers!

[0] from open issues, sm4 features aren't requested much

**Comment by Jjagg** [comment]
It is pretty high on my to-do list to improve the shader pipeline. Unfortunately it's a very big job and we have some other stuff we have to finish first, so I don't have a timeline. 

There is a kind of hacked way to load OpenGL directly. At one point we almost merged GLSL format support to 2MGFX. In the end we decided that was not the direction we were going with MG. Here's my PR: https://github.com/MonoGame/MonoGame/pull/5354

It's on a pretty old version of MG that you'll have to use, unless you can rebase my PR.
The shader format is not fully GLSL, but a hybrid that includes some Effects framework syntax. I wrote a short explanation of how to use the branch on the forum: http://community.monogame.net/t/glsl-shaders/8238/27?u=jjagg. There's also some troubleshooting on that page and in the pull request comments, in case you run into issues.
One caveat I remember is that you need to use varying/attribute instead of in/out. (At the time I did it like that, because in/out would make parsing a lot more complicated)

If you try my branch, let me know how it goes :)
