### ISSUE TITLE
Unable to build from Azure DevOps Pipeline

### ISSUE THREAD

**Issue by SuperJMN** [MonoGame/MonoGame#6885]
I've created an Azure DevOps pipeline to build my Windows Desktop MonoGame.

The error I'm getting is this:

> Job: "The nuget command failed with exit code(1) and error(d:\a\1\s\Tanky.App\Tanky.App.csproj(107,11): error MSB4226: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\MonoGame\v3.0\MonoGame.Content.Builder.targets" was not found.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

**Comment by Jjagg** [comment]
The VS templates provided with the SDK depend on MG being installed on the system. For CI using the nugets is easier. 
Check out our new dotnet new template for Windows DirectX [here](https://github.com/MonoGame/MonoGame/blob/develop/ProjectTemplates/DotNetTemplate/MonoGame.Templates.CSharp/content/MonoGame.Application.WindowsDX.CSharp/MGNamespace.csproj).

**Comment by SuperJMN** [comment]
@Jjagg Thanks for the quick response! I've installed them with 
`dotnet new -i MonoGame.Templates.CSharp`

Which template should I use? Is there any template that creates projects for every supported platform, like the Xamarin Forms templates? Thank you!

**Comment by cra0zy** [comment]
You need to use the development templates, the current nuget ones still use local pipeline.

**Comment by Jjagg** [comment]
You can install the newer templates by cloning the MG repo and running dotnet new -i <template directory>.

**Comment by SuperJMN** [comment]
@Jjagg I have just tried that with a cloned repo (develop branch):

``` 
dotnet new monogame-blank -n "Tanky"
```

And this is what I'm getting :(

![image](https://user-images.githubusercontent.com/3109851/66256557-47a75900-e78f-11e9-98e4-b6d828eb95ce.png)

**Comment by Jjagg** [comment]
You'll want to use the mgwindowsdx template. I don't really now what the 'blank' one is supposed to be, @cra0zy?

**Comment by SuperJMN** [comment]
@Jjagg @cra0zy Hey people I would find specially interesting to have a template that creates a targeted project for each supported platform and a "shared" project (either Shared project or NET Standard) which holds the biggest part of the code (that should actually be shared :) )

That come quite handy because, in case you don't need a platform, the user could just remove its project and voilà.

I've seen that theres a .NET Standard template that uses OpenGL. I guess it's due to Direct X not being a standard, so .NET Standard cannot use it. Am I right? 

Thanks for the support!

**Comment by Apostolique** [comment]
@SuperJMN I created a project like that here: https://github.com/Apostolique/Apos.Framework

It starts with only the OpenGL project, but you can add more as you need.

**Comment by SuperJMN** [comment]
@Apostolique What I would like to do is to have a shared mgcb file. I haven't been able to do it. Could you help me? Thanks in advance.

**Comment by Jjagg** [comment]
> I've seen there's a .NET Standard template that uses OpenGL. I guess it's due to Direct X not being a standard, so .NET Standard cannot use it. Am I right?

WindowsDX does not target .NET Standard because it depends on WinForms, which cannot be used from .NET Standard.

MonoGame uses build-time abstractions for its different target platforms. That means there are different assemblies for each platform, though they all have the same name: 'MonoGame.Framework'. That makes it less obvious how to have a shared library project for a game that targets multiple MG platforms. The trick is to use what's called bait-and-switch for the MG assembly:
Pick an MG assembly to reference in your library project, for example DesktopGL. In your platform specific executable game project, reference the correct assembly for that platform. Because the assemblies are named the same, the assembly that your platform specific project depends on is used by the library as well when you run the game. In case of API that's missing in the platform specific API, a runtime error will occur when the missing method is executed. 

For MGCB files you can set the target platform outside of the MGCB files itself the way it's done in the old templates, by specifying the command line parameters in the MSBuild task that executes the MGCB command line tool. I think MonoGame.Content.Builder should Just Work™️, but I haven't tried it with multiple projects and 1 mgcb file.

We should set up a template that creates a library and platform specific game project (at least one so people can see how it's set up and they can add their own), and fix any issues we run into @cra0zy.

**Comment by Jjagg** [comment]
Closing, because with the new NuGet-focused setup and corresponding docs the original issue is resolved.
