### ISSUE TITLE
The template MonoGame.Application.DesktopGL.CSharp is uses the wrong nuget package

### ISSUE THREAD

**Issue by ashelleyPurdue** [MonoGame/MonoGame#6957]
The correct nuget package should be `MonoGame.Framework.DesktopGL.Core`, but the template
instead points to `MonoGame.Framework.DesktopGL.Core`.  This causes projects created from the template to fail upon using `dotnet restore`.

Additionally, the version of `MonoGame.Content.Builder` it references doesn't exist on nuget.  The latest version on nuget is `3.7.0.9`, whereas the template references `3.8.*`. 

#### What version of MonoGame does the bug occur on:
Not a version of MonoGame, but a version of the template.  The bug is present on commit da6fd5dc258f5a4739e7bea5a17f426dbc0f086c of this repo.

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by mrhelmut** [comment]
The nugets you are mentioning (3.8) are not yet on the online gallery and the current ```MonoGame.Framework.DesktopGL.Core``` (https://www.nuget.org/packages/MonoGame.Framework.DesktopGL.Core/) will be replaced by the proper one once the new build process will be integrated into the build bot.
This is because of a still ongoing transition to these new templates and .Net Core (#6879).

For now, you'll have to build those nugets from source and setup a local nuget source for them to be found from your local storage.
