### ISSUE TITLE
Unable to clone/build MonoGame due to SDL_GameControllerDB DMCA takedown

### ISSUE THREAD

**Issue by Swan** [MonoGame/MonoGame#7038]
The [SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB) dependency of MonoGame was recently subject to a [DMCA Takedown](https://github.com/github/dmca/blob/master/2020/02/2020-02-19-SDL-GameController.md) on the 19th of Feb. As it currently stands, anyone attempting to build MG themselves are unable to from a fresh clone.

Are there any temporary solutions to this?

#### What version of MonoGame does the bug occur on:
- Latest develop branch

**Comment by bartwe** [comment]
See also https://github.com/p-groarke/SDL_GameControllerDB2/issues/5

**Comment by StaxelBoulangerie** [comment]
All of this for a script that turns a header from sdl into a textfile ;p

**Comment by harry-cpp** [comment]
Why was the original taken down?

**Comment by flibitijibibo** [comment]
It’s hard to say without the commit log, but from what we’ve gathered in the FNA Discord it seems that Gabriel was trimming license text from the repository’s files (which makes sense since all the authors/copyright info are in LICENSE) and a fork author decided to use an out-of-context commit to claim that copyright information was being removed, when it actually wasn’t.

I don’t know if Gabriel will counterfile, so I would check with him first before moving to any new repo. If necessary, we’ll make a new repo at the FNA group since we don’t want to use this person’s repo. Will link to it should that happen.

**Comment by StaxelBoulangerie** [comment]
Alternatively a reader for the primary source (sdl header file) itself instead of the exported/converted .txt would also be nice

**Comment by harry-cpp** [comment]
https://twitter.com/gabrieljacobo/status/1231269762472300544

**Comment by gabomdq** [comment]
If you can use https://github.com/gabomdq/gamecontrollerdb in the meantime, it's been cleaned up of any claimed content.

**Comment by harry-cpp** [comment]
Thanks @gabomdq <3

**Comment by Owlzy** [comment]
Is anyone able to build MonoGame at the moment? 

I changed to use the cleaned up repo for game controller, but now I can't build because of StbImageSharp.  Looking at their repo they have changed around some file structure stuff recently, but even if I update to the new structure, I'm still missing ImageStreamLoader.cs and StbImage.Generated.cs , they don't seem to be present anymore ?

**Comment by rds1983** [comment]
@Owlzy StbImage.Generated.cs was split into 8 files: StbImage.Generated.Bmp.cs, StbImage.Generated.Common.cs, etc.

**Comment by rds1983** [comment]
@Owlzy btw, if I go to StbImageSharp from ThirdParty folder: https://github.com/MonoGame/MonoGame/tree/develop/ThirdParty

Then it goes to version that was before split.
So you probably could checkout to that commit and everything will build.

**Comment by Owlzy** [comment]
> @Owlzy btw, if you go to StbImageSharp from ThirdParty folder: https://github.com/MonoGame/MonoGame/tree/develop/ThirdParty
> 
> Then it goes to version that was before split(with StbImage.Generated.cs).
> So you probably could checkout to that commit and everything will build.

Ah thanks for that @rds1983 , builds fine now.  Apologies if I hijacked the thread!

**Comment by harry-cpp** [comment]
The main repo is back online!
