### ISSUE TITLE
It errors saying it requires ARB_framebuffer_object or EXT_framebuffer_object, but my system supports it.

### ISSUE THREAD

**Issue by SnowSnakz** [MonoGame/MonoGame#7045]
I am trying to make an OpenGL project but when I run it, it tells me that it requires either ARB_framebuffer_object or EXT_framebuffer_object (both of which my system *seems* to have) and suggests that I update my drivers, when I try to though, the installer tells me that my system doesn't meet the minimum requirements to install the software.

![image](https://user-images.githubusercontent.com/60198160/75574910-c47bed80-5a24-11ea-8e0f-4b6bc58dd3c8.png)

Intel Core i5-2400 CPU @ 3.10 Ghz
Intel HD Graphics 2000 (GL_VERSION: 3.1)
8 Gb DDR 3 RAM

What version of MonoGame does the bug occur on:
MonoGame 3.7.1

What operating system are you using:
 Windows

What MonoGame platform are you using:
DesktopGL

**Comment by mrhelmut** [comment]
If you're on Windows 10, that's unfortunately a real incompatibility and there is no way around it.

Despite Intel HD Graphics 2000 being physically compatible with OpenGL 3.1 (like your database is reporting), Intel is not providing an OpenGL 3.1 driver for HD 2000 on Windows 10 (they do however, for Windows 7 only).

The driver simply doesn't exist on Windows 10 because Intel deprecated OpenGL support on HD 2000 before Windows 10 came out.

To my knowledge, this concerns HD 2000 and HD 3000 on Windows 10.

**Comment by SnowSnakz** [comment]
> If you're on Windows 10, that's unfortunately a real incompatibility and there is no way around it.
> 
> Despite Intel HD Graphics 2000 being physically compatible with OpenGL 3.1 (like your database is reporting), Intel is not providing an OpenGL 3.1 driver for HD 2000 on Windows 10 (they do however, for Windows 7 only).
> 
> The driver simply doesn't exist on Windows 10 because Intel deprecated OpenGL support on HD 2000 before Windows 10 came out.
> 
> To my knowledge, this concerns HD 2000 and HD 3000 on Windows 10.

Ah, I see. Thanks for quick reply. I will look into getting a graphics card then.
