### ISSUE TITLE
Move "Rebuild" up in context menu

### ISSUE THREAD

**Issue by tomspilman** [MonoGame/MonoGame#7157]
We should move up the "Rebuild" command in the MGCB Editor context menu....

![image](https://user-images.githubusercontent.com/103522/82758839-92bdbd00-9dae-11ea-9302-68a873e686f1.png)

It is almost always the command i'm looking to execute and it is closer to the bottom of the menu than the top.

I would say it belongs as the top menu entry.

**Comment by harry-cpp** [comment]
Agreed, how about right bellow open?

**Comment by tomspilman** [comment]
> Agreed, how about right bellow open?

I could live with that... but i would think that "building" is the primary goal and why it should go first.

**Comment by harry-cpp** [comment]
That would be confusing, if you have a file explorer, the first option you expect to see is Open.

**Comment by tomspilman** [comment]
Using VS as a guide they do seem to prefer Open as the default and Compile below:

![image](https://user-images.githubusercontent.com/103522/82759337-7885de00-9db2-11ea-8b03-75c0310e1ac0.png)

**Comment by AndiAn94** [comment]
Hi I would like to start contributing to this project and it seems this issue would be a good start.
Since it doesn't seem that you have agreed to a new position, my idea would be to place it below "Open With".

Also the project itself has the "Rebuild" item. Should it stay at the current position?
![rebuild](https://user-images.githubusercontent.com/24980864/83450245-349b7480-a455-11ea-9514-5dfa51c32af7.png)

**Comment by tomspilman** [comment]
I would prefer to see `Rebuild` in the first section and not the second section of the menu.
