### ISSUE TITLE
OpenAL fails to initialize on Ubuntu 20.04, appears to be trying to use OSS API exclusively

### ISSUE THREAD

**Issue by Xaeroxe** [MonoGame/MonoGame#7230]
When trying to load sound effects with nuget package 3.8.0.1375-develop on Ubuntu 20.04 with dotnet 5.0 the following error is printed

```
AL lib: (EE) ALCplaybackOSS_open: Could not open /dev/dsp: No such file or directory
```

After which a Microsoft.Xna.Framework.Audio.NoAudioHardwareException is thrown.

My dotnet version is 
```
$ dotnet --version
5.0.100-preview.6.20318.15
```

Installed via a snap with classic confinement. I've tried installing a variety of OpenAL libraries and dev libraries, none of them seem to do the trick.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1375-develop

#### What operating system are you using:
- Ubuntu 20.04

#### What MonoGame platform are you using:

- DesktopGL

**Comment by mrhelmut** [comment]
Installing system libraries won't work to try newer version of openal-soft.
If you want to try updating the local openal-soft, you'll have to copy the binaries to the output/publish folder (in the proper directory). If you wan't to debug it, you'll have to build MonoGame from source and replace the lib there, otherwise MonoGame will always load the binary from the nuget and not the system one.

It would cool if you could try openal-soft 1.20.1 on Ubuntu. The version that MonoGame is using is maybe outdated to support the latest audio backend in Linux (or maybe not compiled with every backend enabled).

**Comment by harry-cpp** [comment]
> Installed via a snap with classic confinement.

That's the problem, snap sanboxes stuff.

**Comment by Xaeroxe** [comment]
> That's the problem, snap sanboxes stuff.

Huh, that was the problem. I guess `classic confinement` isn't quite as permissive as the documentation seems to indicate?

**Comment by Xaeroxe** [comment]
I've filed https://bugs.launchpad.net/snappy/+bug/1886840 for this problem. Thanks for the help!

**Comment by harry-cpp** [comment]
Its not a bug on the snap side either...

**Comment by Xaeroxe** [comment]
This is a bug because classically confined snaps are described by https://snapcraft.io/docs/snap-confinement as "Allows access to your system’s resources in much the same way traditional packages do."

Whether it's a documentation bug or a software bug is up to canonical to decide I suppose, but that sentence creates an expectation that wasn't met here.
