### ISSUE TITLE
Cannot uninstall MonoGame Pipeline tool

### ISSUE THREAD

**Issue by JansthcirlU** [MonoGame/MonoGame#7252]
I posted in an [earlier issue](https://github.com/MonoGame/MonoGame/issues/7248) that the MonoGame Pipeline tool icon persisted in my Ubuntu 18.04 LTS after uninstalling everything else that's related to mono, including MonoGame and MonoDevelop.

Harry posted this solution and immediately closed the issue before I could verify if my issue was fixed.

Run the uninstall command in terminal, `monogame-uninstall`.

_Originally posted by @harry-cpp in https://github.com/MonoGame/MonoGame/issues/7248#issuecomment-663839485_

It isn't, by the way.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Ubuntu 18.04 LTS

#### What MonoGame platform are you using:
- MonoGame for Linux
- MonoGame Pipeline Tool

**Comment by harry-cpp** [comment]
The way this all works is that if the maintainer knows whats most likely answer, they will close the issue with it, if it turns out to be wrong, you just have to write a comment and wait for them to come online to reopen it.

The installers have fully been dropped with 3.8 so this is no longer a valid bug report in general.

Lets continue the discussion in the original issue.
