### ISSUE TITLE
dotnet install -g dotnet-mgcb-editor" stalls

### ISSUE THREAD

**Issue by SeroyHomeServices** [MonoGame/MonoGame#7336]
dotnet install -g dotnet-mgcb-editor stalls

#### What version of MonoGame does the bug occur on:
- MonoGame 3.7

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment]
Its downloading the package, doesn't really give you a progressbar.

**Comment by Jjagg** [comment]
It's probably not stuck, but it takes a long time - especially on a slow internet connection - because the package is very big. There's no feedback on the cli because it's not necessary for most nugets since they're usually pretty small.

Easy step to take is add to docs that it might take a while.

Better would be to reduce the download size of the content pipeline. We can discuss that here.

One thing we could do is lazily install video processing deps, since that's where most of the size comes from and most people don't need it.

We should also make sure only native libs for the user OS are included, I don't think that's the case right now.

@harry-cpp

**Comment by harry-cpp** [comment]
> We should also make sure only native libs for the user OS are included, I don't think that's the case right now.

Yea, all the native libs are included, I would rather that mgcb-editor downloads mgcb and uses that if you need to compile something (which is still my plan to setup for 3.9) as than the mgcb-editor package would be like 8 MB.

**Comment by jnoyola** [comment]
> I would rather that mgcb-editor downloads mgcb and uses that if you need to compile something

I'm definitely in favor of that, but still curious about how technically to do this in a way that handles all the cases we discussed in the original design thread.

**Comment by harry-cpp** [comment]
We just let the user choose with a dropdown which version of mgcb they would like to use (also allow them to specify the path manually, which is useful for console dev peeps). Not that hard once I came to the conclusion that we don't really need to autodetect it XD

**Comment by jnoyola** [comment]
Haha fair enough. And then does it always install globally, or does it install locally within the mgcb-editor folder? (I think installing locally in the same manifest as where mgcb-editor is installed is out of the question.)

**Comment by Stiles-X** [comment]
It doesn't make sense to download everything that isn't needed when this is part of the getting started guide.
