### ISSUE TITLE
LocalizedFontProcessor extremely poor performance

### ISSUE THREAD

**Issue by jamesford42** [MonoGame/MonoGame#7351]
LocalizedFontProcessor tends to have a very large number of glyphs, and its performance tanks terribly as the number increases. Actually I believe what needs to be optimized is the glyph arrangement algorithm in the base type FontDescriptionProcessor, which currently has performance like or worse than N^N. 

#### What version of MonoGame does the bug occur on:
- Console branch

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

-

**Comment by enkeyz** [comment]
There are 3 nested foreach in that method :) That's why.

**Comment by TechnologicalPizza** [comment]
CharacterCollection (which pretty much just wraps a list, nothing else) uses a List<char> instead of a HashSet. 
There are plenty more nitpicks all over font processing though. 
Someone should profile the content builder and show some hot paths for a good start.

**Comment by enkeyz** [comment]
So I taken a deeper look at LocalizedFontProcessor.cs . It would make more sense to cache the .resx files in a HashSet of XMLDocuments, instead of constructing XMLDocuments whenever "SpriteFontContent Process" method is called.

That would eliminate most of the overhead.

**Comment by jamesford42** [comment]
Actually i think for me the hot-path was trying to place a sprite for each glyph doing a linear loop of every other sprite in the sheet to test for overlap/collision, and then offsetting by a single pixel and repeating -- this gets very very slow when you have thousands of glyphs.

**Comment by mrhelmut** [comment]
Any optimization would be welcome here.

Have you run a profiler over this? I would definitely assume ```CharacterCollection``` to be a part of the problem, I may be wrong but if I had to take a guess, I would say that time is also largely lost in parsing the XML on ```xmlDocument.Load(absolutePath);``` and  ```foreach (XmlNode xmlNode in xmlDocument.SelectNodes("root/data/value"))```.

**Comment by TechnologicalPizza** [comment]
Method ArrangeGlyphs and the nested PositionGlyph are absolurely the biggest time hog here.
![image](https://user-images.githubusercontent.com/23627133/107370156-e4e07300-6ae2-11eb-9cad-aaaeb919331c.png)
(Arial 12px, ranges [32..126] and [19968..20992] = 1120 glyphs)

I plan to make a PR for this now.

**Comment by Jjagg** [comment]
This is a [rectangle packing problem](https://en.wikipedia.org/wiki/Rectangle_packing).

Here's a great paper on it: http://pds25.egloos.com/pds/201504/21/98/RectangleBinPack.pdf.

A good algorithm for this problem is called MaxRects. I have a C# port of it [here](https://github.com/Jjagg/OpenWheels/blob/master/src/OpenWheels.BinPack/MaxRectsBin.cs).

**Comment by TechnologicalPizza** [comment]
![image](https://user-images.githubusercontent.com/23627133/107388409-1dd61300-6af6-11eb-9598-bcb9f0c4f241.png)
I don't know what kind of magic that rect packer is using but it's sure working 🌪️ 

 
Old 
![image](https://user-images.githubusercontent.com/23627133/107394792-845e2f80-6afc-11eb-9c34-c2b82bfb5d95.png)

New 
![image](https://user-images.githubusercontent.com/23627133/107394803-86c08980-6afc-11eb-8041-03cc7cf32c5b.png)

**Comment by TechnologicalPizza** [comment]
The next improvement would be recognizing missing glyphs and skipping them/reusing one "missing glyph" for every other.

**Comment by jamesford42** [comment]
What's the performance difference? If you want a really huge .resx example i could email you one privately. 
 
Also, you might want to check if the new algorithm is deterministic. That is, if you run it with the same inputs a second time, it outputs the same (read: identical) sprite sheet. That's important for games that version assets, ship patches, etc.

**Comment by TechnologicalPizza** [comment]
The performance on my 1120 char sample was 33x faster though it may be a slightly less efficient at packing.
It should absolutely be deterministic though.
@jamesford42 And you sure can send that .resx example.

**Comment by jamesford42** [comment]
@TechnologicalPizza My email is visible on my account, but yours is not, can you contact me?

**Comment by TechnologicalPizza** [comment]
Surprisingly enough tweaking how the rect packer grew made it pack exactly like the original implementaiton.
![image](https://user-images.githubusercontent.com/23627133/107437120-cd2edc00-6b2e-11eb-8134-01befa289d08.png)

**Comment by TechnologicalPizza** [comment]
And the PR #7464 is practically done, now it's just to wait for review.

**Comment by stromkos** [comment]
I took a shot at this problem and came up with a near linear time and space Glyph packer. It follows the kiss principal.
 
You can find the branch [here] (https://github.com/MonoGame/MonoGame/compare/develop...stromkos:GlyphPackerImprovements)

I am sure it is not as tightly packed as other implementations, and may be slower on smaller glyph countsL the above range took 539ms compared to 287ms(Stock 3.8). 

It does two passes the first to calculate the output size (512 x ???) and the second is to place using the square root of the calculated size as width.

All of the drawbacks above notwithstanding, this code produced a spritefont XNB file containing all 41354 unique glyphs in 
the BMP plane of "Noto Sans CJK JP" , at size 24 with a texture size of 6280x6156 in 22 seconds. (from .mgstats: Size 41616806,  Seconds 21.603508)
With a size of 65, the largest below 16384 x 16384, it ran in just over 2 minutes.
Note: anything above 16384 * 8191 elements will fail to build due to int becoming negative, and exceeding Byte[] array capacity.

The change to Texture2D.cs allows loading of compressed files up to 168384 x 16383 (Assuming 16 to 1 compression ratio like DXT3).

The test range from previous posts: [32..126] and [19968..20992]
Arial 12  64584, 0.5542461 128 x 88
![a](https://user-images.githubusercontent.com/6497378/110858780-7d0b7c80-8288-11eb-84a2-a967575d09bf.png)
The image is an Alpha8 to allow `texture.SaveAsPng()`.

Stock: Arial 12  200785, 5.2288785  512 x 288 
Stock with 1 Unknown:   18513, 0.2879005  128 x 104
Same range 16456, 0.5392444 128 x 88
