### ISSUE TITLE
TrimmerRootAssembly entry in project templates appears to be incorrect

### ISSUE THREAD

**Issue by alexrp** [MonoGame/MonoGame#7357]
MonoGame templates contain the following:

```xml
  <ItemGroup>
    <TrimmerRootAssembly Include="Microsoft.Xna.Framework.Content.ContentTypeReader" Visible="false" />
  </ItemGroup>
```

When doing `dotnet publish -p:PublishTrimmed=true`, this results in:

```
  Unhandled exception. Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.Xna.Framework.Content.ContentTypeReader, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   ---> System.IO.FileNotFoundException: Unable to find 'Microsoft.Xna.Framework.Content.ContentTypeReader.dll' or 'Microsoft.Xna.Framework.Content.ContentTypeReader.exe' file
```

It's not clear to me what this directive is there for as this assembly doesn't seem to exist anywhere.

#### What version of MonoGame does the bug occur on:

- MonoGame 3.8

#### What operating system are you using:

- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by harry-cpp** [comment]
@mrhelmut iirc. you added this, do you know something about this?

**Comment by KatPurpy** [comment]
I have just encountered the same issue, any updates?

**Comment by mrhelmut** [comment]
I believe it should be: ```<TrimmerRootAssembly Include="Microsoft.Xna.Framework" Visible="false" />```

I initially added that for the trimmer to include content types which are reflected at runtime and will be omitted by the trimmer. Apparently ```dotnet``` doesn't expose finer control over this, which means that the full assembly will be included despite trimming (and likely will make the trimmer useless for MonoGame).

**Comment by KatPurpy** [comment]
I have found `<TrimmerRootAssembly Include="MonoGame.Framework" Visible="false" />` much more efficient because TrimmerRootAssembly expects actual assembly name or dll

**Comment by KatPurpy** [comment]
But it leaves us with even more crashes related to missing types
![изображение](https://user-images.githubusercontent.com/43522532/104852771-e10b6780-590d-11eb-93b5-bcbe5e8252c1.png)

**Comment by mrhelmut** [comment]
That's what happens when you trim an assembly without telling the trimmer to include the types which might be used via reflection. Which means that the ```TrimmerRootAssembly``` syntax is wrong.

Like I noted, if ```TrimmerRootAssembly ``` only takes full assemblies, then it will be useless to even use trimming since it will include the entirety of MonoGame anyway.

**Comment by sandord** [comment]
I'm seeing the same issue again with .NET 6 and the latest Monogame. I'm not sure how long it has worked since I didn't use the option before.

**Comment by mrhelmut** [comment]
If you remove ```TrimmerRootAssembly``` from your csproj, you should be fine. Since .NET 6, assemblies don't get trimmed unless they are marked as ```IsTrimmable``` (which MonoGame isn't, so removing the property should tell the trimmer to not trim MonoGame).

I'll be patching the templates.

**Comment by sandord** [comment]
Thanks!

**Comment by Skratymir** [comment]
Not sure if I misunderstood but I am having a similar problem when using PublishTrimmed. Publishing produces

`  MonoGame.Framework.dll: [IL2104] Assembly 'MonoGame.Framework' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries`

Running the exe file (I am on Windows) doesn't do anything. Trying to run the file in cmd gives no output. When using publish without trimming, everything works. The same thing still happens when I add:
```
<ItemGroup>
  <TrimmerRootAssembly Include="MonoGame.Framework" Visible="false" />
</ItemGroup>
```

I am using Monogame 3.8.1.303 on .NET 6. Is this version incompatible with trimming or is this a bug/am I doing something wrong?
