### ISSUE TITLE
Incompatibilities with NativeAOT/CoreRT

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#7460]
Hello there,

NativeAOT (formerly known as CoreRT) has introduced breaking changes in how it process the marshalling of structures (see https://github.com/dotnet/runtimelab/issues/604).

Presently, some code paths of MonoGame will result in runtime crashes.

Here are notes to make MonoGame more reliant toward native compilation:
- Replace ```Marshal.SizeOf(typeof(T))``` by ```Marshal.SizeOf<T>()``` everywhere;
- ```Enum.GetValues(typeof(Keys))``` within ```KeysHelper``` needs to be changed (so far it concerns only WindowsDX, but it's along a hot path nonetheless);
- ```ReflectionHelpers.ManagedSizeOf()``` or its use should be reworked. As-is, it makes ```DynamicIndexBuffer``` prone to crashes.

Further notes:
- ```ContentManager.ReloadGraphicsContent()``` would fail because it relies ```MethodInfo.MakeGenericMethod()``` but this an Android path only, so can be ignored (it will raise a compilation warning by NativeAOT, though);

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL
- WindowsDX

**Comment by MichalStrehovsky** [comment]
What's the problem you're seeing with `Enum.GetValues(typeof(Keys))`? This use should be fine and shouldn't produce warnings. The API can be problematic if the type passed to `GetValues` is not known at compile time, but here a concrete type gets passed - the AOT compiler will make sure we have code generated to support the array of the enum (the problem here is that the API returns an array of the enum type and we might not have code in the general case).

Replacing `Marshal.SizeOf(Type)` with `Marshal.Sizeof<T>()` should be overall goodness since the AOT compiler can always make that work (there's no dataflow analysis needed since the method doesn't take parameters).

If it's not possible to use the generic overload because e.g. support for .NET Framework less than 4.5 is needed, making sure that calls to `Marshal.SizeOf(Type)` always have the type clearly visible in the method body would work too (`Marshal.SizeOf(typeof(SomeType))` is also fine for AOT provided `SomeType` doesn't refer to generic parameters - the problematic case is the `typeof` of a generic thing).

**Comment by mrhelmut** [comment]
Thanks for dropping by and providing details.

Regarding ```Enum.GetValues(typeof(Keys))```, I assumed (blindly) that it was related to a warning that we get while compiling MonoGame: ```ILC : AOT analysis warning IL9701: System.Reflection.Runtime.TypeInfos.RuntimeTypeInfo.GetEnumValues(): Enum.GetValues was called with an unknown enum type. It might not be possible to construct an array of this type at runtime.```
This warning doesn't come with a type attached to it, and ```typeof(Keys)``` was the only occurrence and I ended up listing them here without looking much at it, my mistake. Having a named type clearly clears out this case and I guess that the warning might be coming from an external type getting compiled.

MonoGame has a minimum target of NET45, so it'll do fine in that regard. My only real concern is here: https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Platform/Utilities/ReflectionHelpers.Default.cs#L33

But this code path is only used for custom ```IndexBuffer```, and I believe that we can safely assume that those types are not coming from any marshalling and are 100% managed.

So replacing ```Marshal.SizeOf(typeof(T))``` should do it for MonoGame itself (I'm preparing a PR. Already tested it successfully locally).
