### ISSUE TITLE
Add support for point primitives

### ISSUE THREAD

**Issue by roy-t** [MonoGame/MonoGame#7478]
Hey everyone,

I'm looking to enable support for **Point**  primitives, next to triangles and lines. As you can do very interesting things with point primitives in particle systems.

Enabling support in Windows/DirectX required less than a dozen lines to be changed. So I've made an PR for that:
https://github.com/MonoGame/MonoGame/pull/7477

In this issue I'd like to gauge interest and ask for help to enable support point primitives on other platforms.

**Comment by prollin** [comment]
The issue with point primitives is that they don't always behave the same across all gpu/driver. IIRC the max point size is usually driver dependent.
Another drawback is that they are clipped at their center coordinate. Could be an issue for larger particles at screen edges.
Those might not be showstoppers for your specific usage but are important to keep in mind. 
It is usually better to just use a single triangle for each point which allows for much more flexibility and pixel perfect AA (without MSAA)

**Comment by roy-t** [comment]
Hey Prollin,

Interesting. So far I've only used point primitives without scaling and I didn't even know it was possible to set their size. MSDN has an interesting article on sizing point primitives https://docs.microsoft.com/en-us/windows/win32/direct3d9/point-sprites. It works slightly different for OpenGL it seems: https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glPointSize.xml

For my use case I always use 1pixel sized point sprites which seems to be working the same in both architectures and is the only thing I've enabled in the MR.

The reason I'm not using triangles is that they perform a lot worse when doing techniques like this: https://directtovideo.wordpress.com/2009/10/06/a-thoroughly-modern-particle-system/ as it is at least 3x the data to process.

**Comment by prollin** [comment]
@roy-t sorry for the late reply

> The reason I'm not using triangles is that they perform a lot worse

I am not sure this is the case (depends on how points sprite are implemented themselves); and even if it is, it might be dependent on the hardware/driver.
This old article shows performance of the various methods of drawing sprites (at the time): https://www.geeks3d.com/20140929/test-particle-rendering-point-sprites-vs-geometry-instancing-based-billboards/

That being said, I didn't mean to derail your contribution; if it is useful for other ppl then it seems appropriate to merge. I just wanted to bring some attention to the fact that point sprites are an old (deprecated?) feature that might not be worth exposing since it has many gotcha's

**Comment by roy-t** [comment]
@prollin ah, yes using the geometry shader would probably (definitely?) be faster but I don't think we can use geometry shaders in MonoGame (without workarounds like this: https://gist.github.com/JSandusky/82cf0022ba78c83e1d436947a6e00926).

**Comment by japhib** [comment]
We can close this issue now that #7477 is merged, right?
