### ISSUE TITLE
Proposal: Freshen up classes using modern C#

### ISSUE THREAD

**Issue by ProgramistycznySwir** [MonoGame/MonoGame#7507]
### Main idea:
First of all, I'm new to this project (and to developing games in this framework also) soo at the beggining sorry if i don't understand basic stuff.

I'm starting this issue to ask if it would be beneficial if I would go to common classes (like Vector2) and freshen up the code using modern C# syntax like tuples, expression bodied methods/properties and pattern-matching, it could easily be done without changing public structure of the methods (even inner structure probably wouldn't change much, due to that these changes i'm speaking of are mostly syntax-sugar).

#### Expresion-bodied properties
This code:
```cs
public static Vector2 Zero
{
    get { return zeroVector; }
}
public static Vector2 One
{
    get { return unitVector; }
}
public static Vector2 UnitX
{
    get { return unitXVector; }
}
public static Vector2 UnitY
{
    get { return unitYVector; }
}
```
Could be shortened to:
```cs
public static Vector2 Zero => zeroVector;
public static Vector2 One => unitVector;
public static Vector2 UnitX => unitXVector;
public static Vector2 UnitY => unitYVector;
```

#### String interpolation
```cs
internal string DebugDisplayString
{
    get
    {
        return string.Concat(
            this.x.ToString(), "  ",
            this.y.ToString()
        );
    }
}
// This one is either way lowered to upper one in IL, soo only less boilerplate.
internal string DebugDisplayString_Short
    => $"{this.x.ToString()}  {this.y.ToString()}";
```

#### Tuples
This one is a bit iffy it's adding new functionality i'm not sure lot of people would use, feedback on this would be much appreciated:
```cs
public (float, float) Deconstruct() => (x, y);
```

### Summary:
Those above are only few examples, but by using modern syntax-sugar whole lenght of Vector2.cs could be significantly shortened. I know it's not most jarring issue, soo i'm seeking your oppinion on this topic and feedback if there is even sense of starting work and creating PRs.

**Comment by LoveDuckie** [comment]
I'm not entirely sure as I am not a regular contributor, but the usage of later C# language features may be contingent on the version of Mono being used.

**Comment by ProgramistycznySwir** [comment]
Oh, you're right, my bad, i didn't look enough into what version of .net is used, when i cloned project it clearly said that only C#5 is supported, soo i don't know if implementing changes i proposed would be worth updating project's .net version. But i'm not an expert, i would be glad if someone would correct me :)

**Comment by mrhelmut** [comment]
Contributions to MonoGame are presently enforcing a C# 5 coding guideline because the runtimes for consoles (which is not mono, but a custom tech) don't support anything above .NET 4.5 assemblies. This guideline is there to avoid merging bits which might break console targets.

The limitation isn't quite on the language version itself, but on the framework version. The console runtime technically can support more recent language features, but the BCL is limited to .NET 4.5. Even though we could back-target NET 4.5 while supporting a modern C# language version, there's a catch: some language features are not just syntactic sugars, but are calls to assemblies in disguise (assemblies which don't exist on the expected runtime).

Since dotnet doesn't offer a mechanism to enforce a coding guideline like "allow higher languages but not disguised assembly calls", we're using ```<LangVersion>5</LangVersion>``` to make sure that no PR slip through our vigilance.

There are plans to upgrade the console runtimes to ship with more recent BCL (and lift this limitation), but it's not as easy as swapping files and many low level calls have to be implemented. This takes time, and so far there hasn't been strong enough incentives to upgrade it versus other console works such as supporting new platforms.

**Comment by ProgramistycznySwir** [comment]
Thanks for clarifying everything, I'll close this issue for now :)
