### ISSUE TITLE
[Android] Keyboard.GetState() Does Not Consistently Work on Android

### ISSUE THREAD

**Issue by pnick0509** [MonoGame/MonoGame#7652]
Once opening the virtual keyboard on an Android device and calling Keyboard.GetState(), it only gets inputs sometimes, often requiring several taps before a single input to be recognized. This occurs both on an emulator and a physical device. Oddly, in the case of the emulator, using the desktop's keyboard will allow the input to be entered normally while the virtual keyboard still has problems.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.0.1641

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- Android

**Comment by KelsamGames** [comment]
@pnick0509 have you found a solution for this? I can't get Keyboard.GetState() to register any keys at any point. Though, I believe I am showing/hiding the soft keyboard in a weird/incorrect way. How are you doing it?

This is currently what I have resorted to in my Activity to listen to soft keyboard input. It is real janky, and the OnKeyPress event seems to fire twice per key release (usually?).

```
protected override void OnCreate(Bundle bundle)
{
	...
	
	inputMethodManager = Application.GetSystemService(InputMethodService) as InputMethodManager;
}


void OnKeyPress(object sender, View.KeyEventArgs e)
{
	CoreGame.AddAndroidKeycodePressed(e.KeyCode);
	e.Handled = ((MonoGameAndroidGameView)_view).OnKeyDown(e.KeyCode, e.Event); // So volume keys and stuff still work. Derpy. Why doesn't MG OnKeyDown work when there is an OnKeyPress event added? And why doesn't this OnKeyDown thing populate the keyboardstate (probably being overridden by OnKeyUp being called after this since this only seems to fire on key release)?
}


void ShowKeyboard()
{
	_view.KeyPress += OnKeyPress; // only add this event while using the virtual keyboard because it does stupid things to MonoGame's normal OnKeyDown handling (breaks it)
	inputMethodManager.ShowSoftInput(_view, ShowFlags.Forced);
	inputMethodManager.ToggleSoftInput(ShowFlags.Forced, HideSoftInputFlags.ImplicitOnly);
}


void HideKeyboard()
{
	inputMethodManager.HideSoftInputFromWindow(_view.WindowToken, HideSoftInputFlags.None);
	_view.KeyPress -= OnKeyPress; // only add this event while using the virtual keyboard because it does stupid things to MonoGame's normal OnKeyDown handling (breaks it)
}
```

**Comment by damian-666** [comment]
I would think this is polling related you are pressing the button and releasing it faster than the polling loop.. I suggest you look at  Input class.  on Nez.  You can call this from a backgound thread faster than 60 or 120 hz, it works for me.    i run that thread at up to 1000 fps.   But ultimately I think you should take the text input from Java code, does that seem more practical?  Yes you would have to do it for iOs in Swift or whatever, but then,  because then you can do cloud translations, not worry about locales and languages and code pages and backwards Arabic stuff,  as much and maybe take that input text from there and use it in your game?  I havent dealt with it myself but polling below 60 fps is not gonna work for tying and i had no issues polling the controller , keyboard at 2000 fps on a bk thread.  the nez stuff will say if its been pressed, released, or if held.    Its also can help with virutal touch joysticks.

**Comment by mrhelmut** [comment]
```Keyboard``` is not meant to capture system virtual keyboard events. If you use it in that context, it is surprising that you even get any result (and maybe why it ended up being confusing, it's not meant to work).

Please check the ```KeyboardInput``` class instead, which is the specialized way to tap into system text entry. ```KeyboardInput.Show()``` will return an async task which upon completion returns a string of the entered text. You don't have to capture individual presses.
