### ISSUE TITLE
Suspicious code that the PVS-Studio analyzer found

### ISSUE THREAD

**Issue by vkulesho** [MonoGame/MonoGame#7653]
I ran the PVS-Studio analyzer for the MonoGame project. From the warnings the analyzer issued, I selected the most interesting ones and wrote an article about them: [https://pvs-studio.com/en/blog/posts/csharp/0915/](https://pvs-studio.com/en/blog/posts/csharp/0915/). I hope our article will help you refine the code!

**Comment by Epicguru** [comment]
Half the errors reported are from external libraries... The other ones are mostly harmless, but could still do with fixing. Submitting a pull request would be a lot more useful than linking to your blog post and shilling your static analysis tool...

**Comment by mrhelmut** [comment]
Thanks for the effort. We tend to ignore static analyzers, there are several reasons to that:
- MonoGame is not your typical .NET library, it is highly specialized and we very often bend the .NET best practices to fit a usage model that is not quite an expected .NET usage. Hence, there will always be flags raised by analyzers, it is to be expected.
- We had issues with people from the same school being assigned to run analyzers on MonoGame and contribute fixes. It resulted in a lot of noise for the admins due to unconstructive contributions from people who aren't into MonoGame and will not stay as contributors.

So we will basically close such issues/PR on sight, unless the contributor shows a real interest in MonoGame, wants to engage, and  understands its usage model.
