### ISSUE TITLE
still in development?

### ISSUE THREAD

**Issue by lonely-unicorn** [MonoGame/MonoGame#7664]
Hi

Is monogame still actively developed since the last release is almost 2 years old? :(
Can we expect new release soon?

Thx

**Comment by damian-666** [comment]
2-3  years cycle isn't long for a thing like this.     I'm not a contributor to the core code and but I chose it to make a fast indie game that already runs on 5 platfroms including phones with almost no per platform repeat code or codepaths.    For every platfrom i have just a tiny EXE.   the rest of the code and game assets are  shared is all in Netstandard2.0 dlls linked to monogame (GL version as a proxy).   The exes targets line via Nuget to Monogame DX or Mongame GL depending if (windows /Xbox) or not.    MonoGame is just a bare graphics and audio framework so you can't expect new features or tools that a game engine like Unity or Unreal Engine offers more often.    If the reason you think there should be an update look at the issues ,are tons and most have workarounds published, someone contributes or makes a fork wiht the fix.    Think of Visual Studio,  it runs on only one platfrom and it comes out with a 3-4 year cycle, VS 2015, VS 2019, VS 2022.    Hopefully Visutal Studio it will run on ARM, and run Android apps on Windows.. this year or next, then we should be able to make a  phone app on thin /fast /cool running  touch laptop whtout as much remote debug or emulation.  There are other tools that do this already on Surface ARMs,   like VS Code that does work, or pay for JetBrains Rider or get an open source license one free if you contribute to some.

 with a few workarouds MG runs with the latest Net Core 6 , thats just came out adn everyone wants it cause its so much faster , and the ARM support in windows  is being overhauled by Microsoft and  Xamarin that is uses may be going through big changes.    Half the stuff Microsoft comes out with gets cancelled, so if you even  made a bet on UWP you/ they  may be in denial , but you recently got screwed.    but fortunetly for me, Net  and c# is now past 20 years old and is open sourced, and just got a super fast update and got open sourced.  they didnt even open source silverlght after they killed it.
 
  Anways, until those Xamarin/ARM/ and GPU pipeline changes happen MG won't know the strategy to even start to update.   The biggest isssue holding back updates and code changes is that poeple depend on it for consoles that use older c# and if its supporting 10+ nuanced devices so the core devs which are like 3 guys,  don't like to change stuff that  even might break even someones one game, as when they update monogame they get a fix or improvment but somethign elsecritical and worse breaks for someone who is depending on that one game as his source of income.   But, unlike Unity you get the source free, so if it does happen,  you you can use the older version,  fork the MG, and fix  your branch or revert the breaking change, and then sync you fix later maybe.  If you think its a general fix and submt a PR they prolly will say NO to it and they should.    Even Fixing something properly when someone has worked hard to place a workaroud around  a nuanced but weird behavior, well thats a breaking change and they are likely gonna be casualties.   The reason they reject PR is also because they care about the little guy, not just because they are unpaid and they don't have time.

The reason i chose Monogame adn open source libraries in generatl is that i once  trusted closed source like Silverlight and aimed at one ecosystem , Windows, once, because when Microsfoft under Gates started to dominate the CAD and most other industry, the company Autodesk  i was working stoppped supporting Mac  and Linux entirely, and my life as a developer got easier less boring (testig, , #ifdefs , fixing same feature on X platfroms is BORING)  but then when i chose one so called Multiplatfrom closed source thing,  Chrome blocked Silverlight, and Netflix dropped it, and  when Android took over Earth,   when Windows Phone was killed, 30 perscent of  my code because useless.    I got the rug pulled out from under me, my staff left, I crashed and burned.

So if you are a game developer and  you chose one platform or even on type of GPI , You  limit your audience and for indies with new IP that can't be a good strategy, u must cast a wide net to find your audience.   if its runs as browser extension, for security reasons It maybe eventually will get blocked, mutated, broken , or worse the platfrom u chose dies entirely,   you go down with their  ship and you aren't captain but you will sbe the one screaming as u drown and they will ignore you and take off from its helipad.  Your are trying to make 50-100K while they chase billions, millions dont even matter to MSFT , Apple, NVidia. 
  AS far as using game engines and prebuilt tools, with MG, You get the sourcecode free to trace or modify, and dont have to put Unity brand on the splash using the free one,  u can promote your own brand there,     Also remeber everyone esle gets those features and tools and to make a unique game you may need to make alot of your own tools your own stuff.    Most  studios make or  their own rigging tools or plugins .  Many  app companies hire two developers wihgt identical jobs descriptions that differ only by two words,  SWIFT and JAVA.   Thats expensive and boring for everyone, from devs, to testers to product managers.  They run two seperate code bases just for iOS, and Android, in two separate langages.    MG isnt for everyone buit im glad i took the year to port to it.

   There is a separate branch of MG that does a Compute Shader.  So if you want to heavily leverage the GPU you might have trouble with MG 3.8.  It realies  on MojoShader to translate the HLSL fx code as Open GL and they arent sure if its best path foward.  But for me ill wont use new core technology that isnt quite a few years mature because it won't work on so many devices at any framerate.
   
   As far as c++ goes i just ported some science code its twice as  simple, 2x as,  readable and gives me a similar framerate and i havent even for Parallel.For in or SIMD Numerics.      i spent 6 hours tryig to build and then linke his  simplest open GL sample wtih 4 arcane libaries to link, gave up, and then and 1 hour to port it to c# and used MG for hte graphics.
   
   The cloud services trend  made all this open source stuff actually a good business model even for big companies so now everyone uses it when it used to be for nonprofessionals or acedemics. 
   
    Anyways choosing languages and tools is a major exectuive descision, and  i hope this helps you decide what to do  if u read to this point, its  practically the story of my whole career since the mid 90s.

**Comment by lonely-unicorn** [comment]
Thx for the information!

**Comment by damian-666** [comment]
oh one more thing about the samples..

 i only found one sample that had shared content that build to dx , opengl
and android    u could add ios buts theres issues..    ... using
netstandard for shared stuff,  , and netcore6 so i made it work better with
a clip shader, that builds once u have Net3.1 net 5 and net6 installed (
ithink)   and put it here https://github.com/damian-666/MGShadersXPlatform..
took me like weeks to make a clip shader, so i put as an example .   its
maybe not be teh best way but the biggest problem is old samples and old
shaders that are set up wrong or for XNA.     the other issue is if u use
the wpfeditor for the content file that is shared to add something new, it
will put target windows there.  if u remove that line and thenedit it by
hand, copy pasting and changing asset and  to add  or sounds or images,  it
will just build and run..for any target.. took me a while to figure this
out and noone has shown me a better way to i put it up, hope it helps if
you are doing multiplatfrom which is kindof the whole point of monogame.
theres also Nez and Myra that extended Monogame very well but they used
more complex ways i dont think you may need.     took me like 3 months to
figure out how best to do what i was doing, hope it helps.    otherwise ull
have to copy stuf here and there but the links work greate and theres only
on content file u should edit with notepad once set up.

**Comment by lonely-unicorn** [comment]
Thx, but ...I'm just a monogame beginner and FAR from all this advanced stuff.

Lisa
