### ISSUE TITLE
go from MonoGame.Framework.DesktopGL to MonoGame.Framework.Android

### ISSUE THREAD

**Issue by ghost** [MonoGame/MonoGame#7685]
Hi

I have made a small game using MonoGame.Framework.DesktopGL. Now I want to use the MonoGame code to make a MonoGame.Framework.Android project.
I don't find any docs on what to do to convert it to Android.

- Do I just put all code inside the MonoGame.Framework.Android project or are there things needed to be changed from the original MonoGame.Framework.DesktopGL code? (for input, etc)

- How to generate an .apk file which I can install on my Android device? Will do visual studio this for me or do I need to enter some commands somewhere to build it?

Thank you

**Comment by damian-666** [comment]
. https://github.com/damian-666/MGShadersXPlatform  this mihgt save you some time and your core code it nicely organized in a shared netstandard 2.0 dll.


. https://github.com/damian-666/MGShadersXPlatform

I found this form smples somewhere  and made it better.  it used net 6 for the desktop windows and dx as Netcore exes and builds and runs on android, even w shaders and with putting sutff in the right places.   All the code is in a netstandard dll with uses Monogmae GL as a proxy nad thine netcore launchers like to dx or Gl monogame versions  .   netcore 6 is like 40 perfect faster framerate  for me than 5 , but android wont enjoy its benefits yet since its using xamarin and older mono.  but it works ok....  Then select android and build, , then when android project is selected find "archive"  do that , wait, make some keys, then  deply as adhoc.   u must sign tell ur phone to trust the drive or chrome and pass the apk to it and insta...    when yhou build,   make sure u trim only sdk and be careful wiht the settings.    its very very painful, expectg to spend a long time.    the evumalor is s slow so i suggest a touch screen pc gett the touch stuf working on pc, the over to . usb debubbing.   good luckk.   if u wait 6 montsh windows is supposed to support ARM and adroind but i spend 6 weeks and got mine working already and hope it just speeds up when they do this .. the dll setup i chose is decent because ALL the code is shared no copies.   now android beta to the store ,  wants an adb and i havent go that far yet.     give 20 $ u get a license and fill some forms...

  mp3 doesnt wrok for me tho. i use wave and soundefffect only.   if u use timers, syncs, and waithandles u might get in trouble there as well.   even if u dont use shaders this is the best way i think.  it builds new content ad put its in the right place for each platfrom.   To add asset must edit mcgb file by hand, or remove the platfrom = windows line that the visual content editor places if you use that..  hope it helps took me 6 over  weeks , had to make virtual joystick but mine runs on androind and whatever now.

**Comment by monogamefan** [comment]
Hi

I appreciate it but I don't like to use frameworks I don't understand how they are made.

And since monogame says 'code once, run everywhere' I think it's a bit of a shame there are no docs to proof this.
When I see how much time you spent, I think they should rename it to 'code once, refactor for weeks, run everywhere'?

If the devs are reading this, why are there no easy docs on how to convert one project to another (from platform to platform) since this is the GOAL of monogame or am I wrong?

**Comment by Apostolique** [comment]
You can ready this <https://github.com/harry-cpp/MonoGame/blob/newprojdocs/Documentation/setting_up_project/setting_up_project.md>.

**Comment by damian-666** [comment]
Just build.mine and run it.  It's netcore and net 6.instakll net 3.5 after tho it will build

**Comment by KelsamGames** [comment]
@Apostolique I think the reason there aren't specific docs for this within MonoGame is because the answer is the same as any multi-platform C# project. (i.e. "You can do it however you like"). There are many possible ways to do it.

One example is to setup a solution in VS with multiple projects (one per platform). You can then link your "common code" within each project and define a set of compiler constants to work around in-the-code platform-specific needs. The key here is to understand .csproj files (MSBuild) and how they tie things together (linking your .cs files from a common source rather than having copies of them in each project, while still having separate platform-specific content/assets per project, for example).

![cap1](https://user-images.githubusercontent.com/7027838/162763010-c3be0270-8483-40d6-8e5a-e85f3e9d2d32.PNG)

![cap2](https://user-images.githubusercontent.com/7027838/162763055-2b95c530-7f9e-43c2-b650-073c51eda30b.PNG)

**Comment by damian-666** [comment]
Sorry my earlier  comment had a lot of typos which I just fixed ,but they madeit incomprehensible.   But I think it is exactly proof of the whole point of monogame. Write once, use and deploy anywhere.  
 That why I shared it since I'm not much of  a engine  core  contributor.  Yes I think anofficial sln sample would be a good idea since mine is a bit specialized.   But even writing a shader once that works on everything is incredible.  Most company run two, 3 codebases on two langanges and that's crazy expensive. More testers more project management more everything it's boring. Platfroms x same features.
 Monogame plus dotnet is sort of a miracle now, after what 20 years of being sort of ok. I would consider use it to builld any app.  For text heavy Parts , or text input u might want to use the native code java or swift, or maybe another ui frameworkfor text processing where monogame isn't especially strong especially given cloud services like translation which can handle Arabic and Chinese and stuff..
  Netstandardd and netcore makes organization of this easier than earlier samples  I was blown away when I got 2000 fps on physics in background thread first try with netcore 6. I Draw latest frame at 60 fps or whenever, using producer consumer type 2 frame setup.     I don't use the update call.   U can poll input on bk thread at any rate u want.
    Otherwise   Anything with PCL  shared dlla or with dotnet specific to a platform I think is antiquated.  My console gl should run on Mac or Linux but haven't tried.l yet I trust it will.     The only difference between my windows console exe is a callbak with some windows froms calls that try to remember where the window was and if maximized or a not, to save setting and dealing with local storage.

For multiplaform,  Also best to avoid any wait handles or semaphore because timer resolution  can be 16.ms on some platfroms and those depend on it ..  I can only get a measured smooth frametate on windows for now.     To make a meaningful measurement  of time spent making a frame, u need 2ms or better timer resultion which u can set in windows but idk in other platfrom how.  
 A simple test  shows Sleep(1) can take 1 to 16 Ms.   So that's a +- whole frame 60 hz therfore useless as it's the default setting.  Anyways took me months to figure out so I thought I'd share my best result, give something bak since mg is free.
