### ISSUE TITLE
compile for game consoles

### ISSUE THREAD

**Issue by evilkomododragon** [MonoGame/MonoGame#7696]
Hi

I made a game using desktopgl project and now I want to compile it for xbox/switch/playstation but I can't find any docs on how to do it.

- how to make the project for it? 

- what.NET framework is needed for a game console? I can't find anything on Microsoft website

Thank you

**Comment by mrhelmut** [comment]
Console targets aren't publicly documented and can't be built without an access to private implementations. To request an access, please [refer to this page](https://docs.monogame.net/articles/platforms/0_platforms.html). Note that you will have to be a registered professional with each console manufacturers to be allowed an access.

**Comment by evilkomododragon** [comment]
So Microsoft (xbox), Sony (ps) and Nintendo (switch) implement their own MonoGame implementations (or is it just the .Net Runtime alone)?
Or how do I have to understand this exactly?

**Comment by mrhelmut** [comment]
Both MonoGame console implementations and the .NET runtime console implementations are maintained by the MonoGame team.

But the MonoGame team isn't entitled to give access to them because of console manufacturers policies about third party software. This is to avoid unlicensed users to have access to code under strict console usage license.

To get an access, you have to request it directly from your license manager at each of the console manufacturer. They will then issue an access request to the MonoGame admins on your behalf, proving that you are a licensed console developer.

We are not allowed to bypass this process. This applies to all third party software, being Unity, Unreal, FMOD, or other.
