### ISSUE TITLE
Feature request: Nullable context

### ISSUE THREAD

**Issue by Jessasyn** [MonoGame/MonoGame#7796]
With the new C# version, nullable contexts are now automatically enabled throughout the entire project. (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis)
I noticed that this was not the case in the MonoGame library. If no one else is working on implementing this, I would like to contribute.

**Comment by mrhelmut** [comment]
For the time being, contributions have to build on C# 5.0 (the build bot is verifying this). The reason is that the console implementations of MonoGame depend on a custom runtime that currently can't target above this and accepting C#5+ contributions would break console implementations.

We are working toward lifting this limitation but it is a giant work to be done on this custom runtime, so it's likely not going to happen tomorrow.

**Comment by Jessasyn** [comment]
I see, thanks for the quick response!
In that case, feel free to mention me in an issue or project card when this limitation is lifted.

**Comment by eosxff** [comment]
How promising is NativeAOT for publishing to consoles? I know it's already been successfully used to ship a couple of games, but I assume there's a reason for not abandoning this transpiler.

**Comment by mrhelmut** [comment]
I’m closing this issue for the time being but fear not: I’ll be writing another one to explain exactly how things go with consoles and why it is an issue (it will likely be more readable because this issue is coming up often).
I’ll link to it.

**Comment by mrhelmut** [comment]
#7873

**Comment by tvardero** [comment]
Won't making this issue open but labeled "blocked" be better? @mrhelmut

**Comment by mrhelmut** [comment]
No no, MG is not going to be split, and it's not a problem that can be summed up as "just".
