### ISSUE TITLE
OpenGLESBoard for ARM SoC support

### ISSUE THREAD

**Issue by windraak** [MonoGame/MonoGame#7833]
I want to get monogame to work (hardware accelerated) with OpenGLES on ARMxx SoC boards running Linux and SDL2 so monogame can target the evercade (console) and educational boards such as the raspberry pi.

What would need to be done? I'm guessing the following. If an experienced programmer can please agree or inform:

1) create a copy of the OpenGL desktop project, and call it OpenGLES.Board
2) change the compiler directives of the copy, undefine (or probably keep?) OpenGL and define GLES and ignore OpenGL sources and add OpenGL es platform source files to compile. Perhaps add additional gles directions for SDL stuff in the OpenGL desktop sources
3) check if you have to change the content pipeline as well or just copy the Android pipeline 
4) prune the project stuff up until a Linux build (optional). But keeping Windows support would be nice if people run windows on their arm development boards 

I've posted on the forum at https://community.monogame.net/t/monogame-on-the-evercade-platform/17664/8

I'm not sure how complicated something like this gets. Would it be a lot of work?

- Joey

**Comment by mrhelmut** [comment]
It is not documented but MonoGame should support ```linux-arm``` and ```linux-arm64``` as-is through DesktopGL (providing a local SDL2 and OpenAL-Soft installation).

Raspberry performances with MonoGame are extremely bad (if you want to run anything that isn't a sample or a tutorial), which is why we never promoted it to be officially supported.

Regarding Evercade, as far as I understand it, it doesn't support OpenGL (or at least it does, but in a too low version for MonoGame to even start, which would make it worse than Raspberry, so I don't know if it's even worst trying. You might run into more frustration than actual fun with it). If we were to support it anyway, it would require to kind of mix the Android and DesktopGL platforms to detect which OpenGL/ES version is supported and load the entry points accordingly. But I would expect the performances to be bad anyway.

This aside, a Raspeberry support could be easily added to the official support within DesktopGL. All that is needed are binaries for SDL2 and OpenAL-Soft to be compiled for ```linux-arm``` and ```linux-arm64```, and added to the DesktopGL packaging. It should then just work without any changes (but I'm sure if it would be wise to advertise MonoGame as having an official support for it since the performances are bad; it might generate more frustration than enthusiasm).

**Comment by windraak** [comment]
Hello Thomas, thank you for your time.

You have made aware that the SoC is underpowered for most (esp. modern) monogame games.

I have tried my game using the Mesa Lima shim OpenGL driver (armbians default) and for my game it works well enough on a €25 orange pi one (4x1.6 512mb mali400). There is sometimes screen tear but it's acceptable. It's a simple roguelike though but it runs at about 25-50 fps.

Would supporting OpenGLES within the build (no intermediate OpenGL to gles translation) really not make it a lot better? That's why I'm interested in adding support.

Maybe I'll try making a fork but I'll keep my expectations in check. I was hoping for better news but oh well. I think I will still pursue to get it working on the evercade, just to get my game working.

Thanks.

**Comment by windraak** [comment]
Evercade is limited to OpenGLES not OpenGL 😉

I think I'll just try to use the stuff within the GLES define together with the desktop stuff and SDL stuff. It will be mighty educational.

Not taking a shot is always a miss.

Maybe I can get a developer cartridge once I get it to build. But that depends on the company blaze. For now I'll use my orange pi.

Thanks!

**Comment by mrhelmut** [comment]
Moving forward, MonoGame will focus on platforms that are supported by AOT contexts of .NET 8+ only. That includes 64bit platforms (both x64 and arm64), and excludes 32bit (x86/arm7). Which means that the current line of Evercade products will not be supported officially because they are limited to arm7 SoC (but modern Pi boards supporting arm64 will, like the Rasp 5).

Unofficially, users brave enough can still manually build 32bit apps but this will not be documented.
