### ISSUE TITLE
content pipeline editor wrong version

### ISSUE THREAD

**Issue by rocketpowergirl** [MonoGame/MonoGame#7867]
Hello,

I have installed latest version of the visual studio 2022 extension of monogame.
I created a desktopgl application for windows using the extension.
Then when double clicking the content pipeline file , the content pipeline editor opens. But it has a different version (at the end) when going to the "about" window.

How to get the latest version of the editor that matches the nuget package version?

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1 latest version

#### What operating system are you using:
- Windows 10

#### What MonoGame platform are you using:
- DesktopGL

**Comment by mrhelmut** [comment]
That is because you still have 3.8.0 installed. Please uninstall with ```dotnet tool uninstall dotnet-mgcb -g``` and ```dotnet tool uninstall dotnet-mgcb-editor -g```.

3.8.1 doesn't need installation. Never use ```dotnet tool install``` with 3.8.1.

**Comment by rocketpowergirl** [comment]
Thx, working!

If there is again a new update to 3.8.1 in the future, do I need to update the extension and recreate my project again?
Or is updating the nuget packages enough to keep using a previously created project?

Normally with other nuget packages, I just update the packages but don't need to recreate the project again.
Why is this needed for monogame?

**Comment by mrhelmut** [comment]
> is updating the nuget packages enough to keep using a previously created project?

You will also have to update the version of the editor manually in the ```.config/dotnet-tools.json``` file. But that should be all beside the nuget packages.

Directing you to recreate the project from scratch was a shortcut to avoid you to go through that step and making sure that no misstep would happen.


This file is required because MonoGame has an external tool (MGCB) to function, and since we choose to be distributed 100% via nuget with no installer, that's how things work with .NET 6. It has other advantages like the possibility to have per-project versions of MGCB instead of having one per machine (which can be useful for developers working on different projects for different clients).

**Comment by rocketpowergirl** [comment]
Is it possible to make docs on how to upgrade a project ? This json file is otherwise forgotten by users I think because it's not explained in the docs right now.
I made request here: https://github.com/MonoGame/MonoGame/issues/7869

Is it correct the MGCB editor is inside the package monogame.content.builder.task or where is it? 

![afbeelding](https://user-images.githubusercontent.com/110139313/181585515-d4ccd5b8-c8cf-4128-8ddc-fdf3ae01cd8e.png)
