### ISSUE TITLE
question: FNA vs monogame

### ISSUE THREAD

**Issue by rocketpowergirl** [MonoGame/MonoGame#7871]
Hello

I have a question about FNA vs monogame.

- What's the difference between FNA and monogame?
https://gist.github.com/flibitijibibo/1ce4b7899b3cf1805a420330f0d2faf3#what-is-fna

- Why are TWO XNA implementations made while all developers could either work on FNA or on monogame (but not on both) to be able to have more contributors to ONE project? Is there any communication with the FNA people?
They could help monogame, write docs, example code, ... instead of duplicating everything that's already made in monogame considering code.

**Comment by Beyley** [comment]
> Hello
> 
> I have a question about FNA vs monogame.
> 
> - What's the difference between FNA and monogame?
> https://gist.github.com/flibitijibibo/1ce4b7899b3cf1805a420330f0d2faf3#what-is-fna
> 
> - Why are TWO XNA implementations made while all developers could either work on FNA or on monogame (but not on both) to be able to have more contributors to ONE project? Is there any communication with the FNA people?
> They could help monogame, write docs, example code, ... instead of duplicating everything that's already made in monogame considering code.

Monogame and FNA have different goals, FNA is designed to be a 100% accurate implementation of XNA while Monogame is meant to extend the XNA APIs

**Comment by damian-666** [comment]
If u look at Nez.they support both.   But what's happening is he's sticking to fna more. But his focus is a certain type of retro.   I take bits of nez and bits of this or that..because I'm not an engine type I'm application level coder. but monogame i use the nuget and don't dare to fork it..if u had a old successful xna game it's easier to port to fna..but if u aren't just posting and old game, with mg  u have a bigger team.   Jsit look at the front page..whiioe there are more trouvbles and hurdles, it's more ambitious, w 10x more contributors.  10x.more forks and more platforms, more history, much harder challenges

**Comment by mrhelmut** [comment]
Closing this issue because it is a discussion and not about a bug. Please use the forum for that kind of topics. I’ll be happy to answer but only if this discussion happens on the forum.

We already told you that several time (the OP) and we are chill enough to allow to come back and we are patient with you on other (real) issues, so please try to listen to rules and to respect our volunteering time. Thank you.

If you don’t know if something is a discussion or a bug, please try to go to the forum first. (The fact that we give more attention to here than the forum isn’t a valid enough to bypass rules.)
