### ISSUE TITLE
Improving the console runtime and lifting the C#5 limitation.

### ISSUE THREAD

**Issue by mrhelmut** [MonoGame/MonoGame#7873]
**Disclaimer:** This discussion is going to be very awkward because most of it can't be discussed publicly for legal reasons, but I feel like the community deserve some context (on what can be public) in regard to some details. So bear with me if this gets frustrating with no obvious answers.

-------------------

If you've been reading the repository, you might have noticed that contributing code to MonoGame requires a strict compatibility toward C# 5.0 and .NET 4.5.2, even though MonoGame targets .NET 6.0 only. This is a frequent source of frustration because we owe this limitation to gaming consoles and concerns are usually met with a "deal with it" kind of answer without much explanation.

> This only applies to the code of MonoGame itself. Games made with MonoGame are not obliged to follow that rule (unless they wish to one day be ported to consoles).

So this is the long version of it, and a disguise call for contributions.

# Why can't we talk about consoles publicly or release publicly the console implementations of MonoGame?

When you work with a console manufacturer, you are legally bound to secrecy. Any person accessing a console SDK has to first to go through a thorough selection and registration process, ending up with the signing of a Non-Disclosure Agreement (NDA). This NDA implies that no code using console SDK are shown to anyone who hasn't signed the same NDA, and manufacturers also enforce upon software distributors like MonoGame to abide to a verification process for any developer willing to see that code. Sometime it also go as far as not being allowed to even mention the console brand publicly.

# How does MonoGame run on consoles?

First and foremost, .NET can't target consoles (at least officially). It is not a supported scenario by Microsoft, and will likely never be. Which means that, by default, MonoGame can't run on consoles.

.NET is open-source you might say, so why not just compiling it on consoles? It's not that simple, porting something to console never is. Consoles are not linux, they are their own beast and basically all the system layer has to be rewritten, and this requires some of the most technical knowledge (and time). Also, .NET is a giant, just look at [the size of it](https://github.com/dotnet), it's a multi-decade project with hundreds of people involved.

Enters BRUTE. BRUTE is a private technology made by Sickhead Games, and most notably our very @tomspilman. Its development started about a decade ago. The idea was to write MonoGame's own .NET runtime from scratch, in a very thin way with the bare minimum needed for MonoGame to work, with the intent to make it less daunting to port to new consoles should any of them release in the future. BRUTE has been written over several years, and Tom had a very deep knowledge of how the internals of .NET work from before he ventured into games. It has been a tremendous amount of work and knowledge.

BRUTE is a transpiler. It doesn't compile C#. It takes compiled dll, read their IL code, and convert it to console compatible C++. But that's not enough, it also plugs that C++ to a custom minimal runtime for memory management, and some features that C++ can't do as-is. It then compiles the C++. BRUTE also applies a bunch of MonoGame-specific optimization to make it super fast. It is notably magnitude faster than the official .NET runtime (sometime 10 times faster).

# So why is there any problem?

Like noted, BRUTE's development started almost a decade ago, when .NET 4.6 wasn't even a thing. So for the most part, there was no problem. Also, if you followed properly, BRUTE is no small project, it involves a deep knowledge of .NET, and porting .NET it is no small task either.

The problem is that it's such a big project, that "upgrading its supported version" basically means almost entirely rewriting it. Which is not a task that can happen easily considering its decade of history and the knowledge required. We're talking about months of work, full time.

Also, working with BRUTE implies that anyone willing to undertake the task has to be NDA'd with consoles. The combination of time required, knowledge, and legal binding, makes it ultra hard to find anyone even available to work on it. Tom, for instance, is a busy bee who can't afford it, while I, lack the time and knowledge.

# Why not allowing MonoGame to surpass consoles implementation?

Because console developers are at the core of MonoGame, and having to maintain two separate tracks would make maintenance unmanageable. It would also grow frustration if users on the "new" MonoGame start wanting to port their project to consoles to be met with a "it's not the same, you have to change this and this".

Some new users might say "okay, but you're ignoring new users and that makes MonoGame less appealing", which is debatable. It's a side of the same coin. Console developers and console support of MonoGame is mainly what makes the framework interesting to new comers, ignoring it would drive the appeal down. As much as ignoring new comers would end up with a long term decrease of console users.

There's nothing simple in that, and there is no obvious answer to it.

# What about NativeAOT or Mono on consoles? Aren't they promising?

Yes, and no.

## NativeAOT

NativeAOT is a great piece of tech, and exactly what MonoGame would need. The problem is the same as BRUTE, though. It doesn't exist on consoles, and porting it to consoles is pretty much the same amount of work and knowledge involved than upgrading BRUTE. Some community members (from FNA, like @TheSpydog and other, I don't know everybody so sorry if I miscredit) did manage to have it to run on some (not all) consoles, but it's such an amount of work that it's also very likely that these versions will end up being outdated and driving C# versions backward because nobody can keep up with Microsoft's speed of innovation.

## Mono

Mono doesn't officially exist on consoles. There are initiatives (and we should be respectful for that), but none that we are allowed to discuss publicly. The main takeaway is that yes, it might be possible to rely on it for some machines, but not all, and there is no guarantee that any new machines would be supported as well. Despite the hard work put into it, it is difficult to make long terms bet on it.

Also, Mono often is the least performant runtime. For many games it ended up being a bottleneck. It is becoming less true with the newest generation of consoles, but might still be a concern.

# So what now?

We need contributors with knowledge in the .NET runtime, and NDA'd with all consoles. Which is, well, rare. We're trying to unite our effort with the FNA team, which depends on the same tech to consoles, but that is not enough.

There is no golden path. Upgrading BRUTE is as much a valid choice as porting NativeAOT.

So that's it, that's our call to contribute. Because otherwise the C# 5 / .NET 4.5.2 limitation will not be lifted anytime soon.

I hope that you now understand the context.

**Comment by MrGrak** [comment]
Great post, looking forward to the discussion. Here's my thoughts.

### Brute vs Native AoT

i'd like to say how much i appreciate the work that Tom has put into Brute, along with other contributors. there's a lot of value in Brute, specifically the performance of transpiled code on consoles. do we have performance comparisons between native aot code and brute'd code? which is faster? performance requirements for consoles are becoming less important as consoles get more powerful, but i would hate to sacrifice a x10 speedup in favor of new language features that might not even be used. if native aot is significantly slower, is it worth pivoting away from brute? if the time investment is the same (porting native aot vs updating brute), why not rewrite brute to work with .net6 and keep the monogame specific optimizations and faster c++ code? 

### Contributing

i have the ndas, and the time, but not the knowledge or experience to meaningfully contribute to help porting brute or native aot. there are other developers like me, who want to contribute but are unsure how to do so. is there a way to break the process down into smaller tasks that can be explained and delegated? the talent exists, the bottleneck seems to be knowing what to do and how to do it, and testing that it works - once maintainers have decided the direction they want to take monogame. we have console specific brute repos that we can collaborate on rn, but to be honest, they're not very well organized, or explained/documented, and could use a lot of improvement. so imo, it's difficult to work with and contribute to the already existing brute repos, and making that process easier and clearer will likely lead to more contributors. 

### What Makes Monogame Appealing?

i think it's a combination of being open source, being established (with popular games having shipped), being free, and having the ability to target consoles. xna/monogame has never been known for cutting edge 3d. the majority of the popular games made with MG seem to be pixel art 2d games (Celeste, Stardew Valley, etc). for cutting edge 3d, Unreal seems like the best option. for easy and fast 3d, Unity seems like the best option. the barrier to entry for 3d is much, much lower with Unity, and Unity can target consoles. there's other frameworks and engines that could be mentioned here, but the underlying point i'm making is this: 2d pixel art games are monogame's bread and butter. that's what MG is well known for, and i would argue that is what attracts a lot of developers to use MG. that is what led me to choose MG, about a decade ago. and in that time, i have yet to see a framework appear that serves the niche of crossplatform + console 2d pixel art games as well as MG does. the majority of developers in the discord asking about mg are asking questions related to 2d pixel art games. the majority of posts in showcase in the discord are about 2d games. so, i think the majority of MG developers are developing 2d pixel art titles. it might be worthwhile to consider making a version of MG that is targeted towards 2d games, LTS, + consoles (brute & .net 4.5), and one that is targeted to 3d and modern pipelines (.net 6, native aot, compute shaders, vulkan, etc). the argument could be made that modern 3d games aren't being made with MG because of the limitations that are being imposed on MG by consoles (compute shader, for example). so, i dont know if it's possible to satisfy the two party audience of MG with only one version of the framework. there seems to be a push towards more modern features, while MG is still being anchored to 4.5 and c# 5. we dont want to lose the enthusiasm and work that talented developers have put into modernizing MG.

### Simplifying Monogame?

would it be possible to create a version of mg targeted for consoles that has limited functionality? the less there is to port, the easier it should be. there's a lot of stuff inside monogame, and maybe removing some of that stuff would make monogame more lightweight and make the task of migrating to native aot or updating brute easier. i know this would introduce breaking changes, but the alternative is maybe mg never gets ported to native aot and brute never gets updated because the task is too large, complex, and expensive. if the problem with porting is the scale and complexity of monogame, then how do we reduce the scale and complexity of monogame? 

### Cross Version Codebases

i maintain versions of my game on mg 3.7 using C# 4.5 + dx project, and 3.8 w/ opengl for mac/linux. i've got a version working on switch too, via 3.7. i'll be migrating to 3.8.1 soon and using .net 6 too, with vs2022. so i know its possible to write game codebases that are more or less language version + mg version independent. But - requiring an older, unsupported language version and runtime isn't going to be appealing to developers who want the latest features. i can understand, and agree with, both perspectives. i think splitting monogame into two versions is probably the best way to satisfy the two party audience of mg: developers who want stablity and LTS for their console and crossplatform games, and developers who want the latest features and modern pipelines. it would be ideal if monogame could stay a single version that serves all developer interests, but i'm just not sure if that's possible rn.

**Comment by mrhelmut** [comment]
As someone who has done a hundred of console releases with MonoGame, quite honestly, if I had to care about sync'ing 2 implementations for 11 platforms every time I need to port something (or sitting on newer versions), I would have quit gamedev and gone raising goats for years by now. MonoGame, as it is designed today, allows me to have a single unique codebase for all my projects, and that is using 3.8.1.

Splitting MonoGame is a solid no in my opinion. The project is already very complex to maintain with its 11 platforms, I wouldn't expect this to make any good to anyone involved into maintaining it. Ultimately, we should look into making the project more maintainable, not more complicated and convoluted than it already is.

Actually this is not about MonoGame. MonoGame itself isn't _that_ complex to maintain because for the most part it is just stable. There is nothing much to simplify which would have a significant impact of consoles because most of MonoGame is in C#, not native code. For instance, there would be no reason to remove 3D support because even things as (visibly) simple as the SpriteBatcher use the same render pass as 3D. Which means that, if you have the SpriteBatcher running, you also have the 3D layer done, and for the most part, it's just C# code and nothing console specific.

MonoGame on consoles is already as simplified as it can be. Some parts of it are not implemented, but we're already down to its minimum considering what actual clients need. The problem is not MonoGame itself, but the console runtime.
MonoGame as a cross-platform framework is doing very fine. It's not about MonoGame, it doesn't need to be split. The problem is only the runtime. There's reason to bend MonoGame around that if MonoGame itself is fine. It's like changing the engine of a car because the tires are getting old.

(There is space on the market for specialized 2D engines on consoles, but that's an entirely different discussion.)

**Comment by MrGrak** [comment]
3.8.1 sounds like its going to simplify my codebases. i'm excited about updating. i've been waiting for early bugs to be ironed out.

mg as a single version - how do we add things like compute shaders while also maintaining console targets? 

it seems the console runtime is the largest challenge. is there a way to reduce what is supported in the runtime so that less needs to be ported? since the runtime has a finite number of types, classes, and methods we should be able to prioritize the most commonly used ones and triage the porting process. ideas or thoughts on tackling the runtime porting?

**Comment by mrhelmut** [comment]
> how do we add things like compute shaders while also maintaining console targets?

I believe that the current state of MonoGame and its interconnected projects don't allow for breaking changes such as changing the shader pipeline. So it's basically going nowhere for now. What this PR represents is unsettling. I mean, cpt-max work is great, I'm really not diminishing that, but the community has transformed this PR into the symbol of MonoGame being conservative, and that's plainly absurd because none of the people who complained about this PR not being merge intended to actually use compute shaders (you noted yourself that the vast majority of MonoGame's users care only about 2D). It's just a symbol, and it is used to drive debates from the real problems which needs to be solved first.

> is there a way to reduce what is supported in the runtime so that less needs to be ported?

It's already down to the most minimal runtime possible. That was the whole idea behind BRUTE, being brutally minimal.

**Comment by MrGrak** [comment]
hmm, this is quite the complex topic. i'd like to help and contribute, any advice or direction is appreciated. for now, i'll focus my time on mg documentation and articles. i hope we figure out a compromise that suits all developer interests.

**Comment by HouseOfPandas** [comment]
> drive debates from the real problems which needs to be solved first.

Now that things seem to start moving again, I think a roadmap defining those problems would be very useful. It's very hard to plan ahead when there's no clue about what's going on. A little bit more information about console platforms wouldn't harm either. I've been struggling to port a 3d game I did to consoles because of the high amount of unimplemented features I'd have loved to know beforehard.

I know that NDAs make difficult to talk about this kind of things, but something like "MRT is not implemented in any console platform" (at least of the ones I have access to) or "BasicEffect doesn't work out of the box on some platorms" would have helped me a lot when deciding wether to choose MonoGame or not (I'd probably have still chosen MonoGame because I love it, but I'd have done things differently)

The "stick to C# 5" is only barely true if you're doing 2D games (and not using await). I can assure you that discovering that 3.5 years into a project is painful, specially when the main audience of your game genre is console.

**Comment by Apostolique** [comment]
I also like that MonoGame isn't split in two and considered stable.

There's another project that could be interesting for those that want a smaller set of features: <https://github.com/bottlenoselabs/katabasis>. Maintained by @lithiumtoast

**Comment by mrhelmut** [comment]
Most of the prioritized projects are listed [here](https://github.com/MonoGame/MonoGame/projects?type=classic).
I also have a community post in the work to shed some light on all of this and call to participate.

What we hoped to convey is to prioritize making MonoGame more welcoming (i.e. easier to use, easier to setup, and more accessible documentation and resources), then future-proofing it, then breaking stuff.

Beside documentation/tutorial, the two big projects that kind of blocks everything from innovating rapidly are:
- #4571 
- This present one

The other big project that we had planned is partly referenced in #4571 as well: removing all platform code from the C# assembly to have only one unique assembly to rule them all, and offloading all platform code to swappable native dll.

Past these, it's basically party hard in regard to adding new features or breaking stuff.

**Comment by rocketpowergirl** [comment]
I'm a beginner and don't know much but why can't there be made a monogame in C++ just for the consoles?
This will need to be a clone of normal monogame.

And the way you can use C# code cross-platform: there need to be made a C# wrapper with same syntax as the "normal" monogame that calls the monogame C++ DLL just for the consoles only.

In this way there is no need for BRUTE or anything else. In case there is added a new feature to monogame, the C++ dll needs to be updated with C++ code for that same feature. 

My apologies if I'm telling impossible things but to me it seems possible. I also used C# wrappers for C++ libraries in the past too.

**Comment by rocketpowergirl** [comment]
> What we hoped to convey is to prioritize making MonoGame more welcoming (i.e. easier to use, easier to setup, and more accessible documentation and resources), then future-proofing it, then breaking stuff.

Great! The 3.8.1 is already super easy to use and install! I hope future versions will be exactly the same (visual studio extension and everything using nuget packages because this is THE way to do it)
It's just the missing documentation that needs attention now.

**Comment by eosxff** [comment]
The issue is that consoles don't allow ANY C# (or any other JITted languages for that matter) on consoles for security reasons. Rewriting MonoGame in C++ is not going to fix the issue if games are then written in C# anyways

**Comment by mrhelmut** [comment]
> I'm a beginner and don't know much but why can't there be made a monogame in C++ just for the consoles (which can also be run on desktop)?
> This will need to be a clone of normal monogame.

You're suggesting the creation of an entirely new project rewritten from scratch and not compatible with existing code. That's basically asking console developers to scrap their game entirely and to the MonoGame team to have even more projects to maintain.

> And the way you can use C# code cross-platform: there need to be made a C# wrapper with same syntax as the "normal" monogame that calls the monogame C++ DLL just for the consoles only. This C++ dll can then be adjusted (added specific code for a console) for private console code which is not public released.

Console implementations already work that way. The plan is to make all of MonoGame work that way. It's what I linked to earlier.

> In this way there is no need for BRUTE or anything else. In case there is added a new feature to monogame, the C++ dll needs to be updated with C++ code for that same feature.

This is a very large misunderstanding of how C# and .NET work. I don't have the patience nor the time to start a crash into that, so I'll leave you doing your own research.

> The issue is that consoles don't allow ANY C# (or any other JITted languages for that matter) on consoles for security reasons.

Correct. So it's just about just-in-time compilation, and not quite linked to C# itself (which doesn't force us into JIT'ing).

But the real reason C#/.NET doesn't exist on consoles, is because it isn't within .NET official scope, and it isn't on Microsoft's roadmap. There are initiatives within Microsoft, but it's nothing officially supported.

**Comment by rocketpowergirl** [comment]
> > I'm a beginner and don't know much but why can't there be made a monogame in C++ just for the consoles (which can also be run on desktop)?
> > This will need to be a clone of normal monogame.
> 
> You're suggesting the creation of an entirely new project rewritten from scratch and not compatible with existing code. That's basically asking console developers to scrap their game entirely and to the MonoGame team to have even more projects to maintain.

Is it better to depend ALL console implementations on BRUTE, a proprietary product by 1 company and made by 1 man?
What happens if Sickhead games is closed down or Tom Spilman dies? 
You told nobody has the knowledge so this means after this occurs, MonoGame can't be used on any console anymore because nobody can update BRUTE. And since it's closed source, it's lost forever then.
So basically the future of MonoGame for game consoles depends on 1 company or is my understanding wrong?

> 
> > And the way you can use C# code cross-platform: there need to be made a C# wrapper with same syntax as the "normal" monogame that calls the monogame C++ DLL just for the consoles only. This C++ dll can then be adjusted (added specific code for a console) for private console code which is not public released.
> 
> Console implementations already work that way. The plan is to make all of MonoGame work that way. It's what I linked to earlier.

Is it correct console manufacturers buy BRUTE from Sickhead Games and then "glue" their own C++ console SDK together with the open source part of MonoGame by using BRUTE? So BRUTE is really the bridge from C# code to their own C++ SDK for the particular console?

Thanks for this interesting explanation!

**Comment by mrhelmut** [comment]
> Is it correct console manufacturers buy BRUTE from Sickhead Games and then "glue" their own C++ console SDK together with the open source part of MonoGame by using BRUTE? So BRUTE is really the bridge from C# code to their own C++ SDK for the particular console?

No, this is a fantasy.

**Comment by rocketpowergirl** [comment]
> > Is it correct console manufacturers buy BRUTE from Sickhead Games and then "glue" their own C++ console SDK together with the open source part of MonoGame by using BRUTE? So BRUTE is really the bridge from C# code to their own C++ SDK for the particular console?
> 
> No, this is a fantasy.

THEN WRITE DOCS SO PEOPLE CAN UNDERSTAND IT

LAZY FUCKFACE

**Comment by eosxff** [comment]
>BRUTE also applies a bunch of MonoGame-specific optimization to make it super fast.

Is BRUTE usable outside of MonoGame/FNA? If so, given the lukewarm responses here (+1 fiery response), this might seem the only way to get talent on the project.

**Comment by mrhelmut** [comment]
BRUTE is "just" a .NET runtime. It is not bound to MonoGame/FNA and it can be used to run anything that is .NET on those machines. But it is worth noting that, like NativeAOT, the very nature of AOT compilation make it so many features of the .NET runtime are stripped out. For instance, reflection or code generation can't work in a AOT context.

**Comment by eosxff** [comment]
>For instance, reflection or code generation can't work in a AOT context.

Code generation is a given but surely reflection is supported in some way with BRUTE (MonoGame itself uses reflection), even if it is as simple as NativeAOT's rd.xml reflection hints

**Comment by mrhelmut** [comment]
Yes and no. The rd.xml thing is only to avoid trimming on reflected types, BRUTE has the same mechanism to force it to not trim specific types (typically, the content pipeline ContentReader types). But reflection is not limited to that, there is a lot of runtime stuff that don't depend on trimming and which won't work, being on NativeAOT, BRUTE, or any other AOT of .NET such as Unity's IL2CPP. Anything like Assembly.Load, GetAssembly, GetMethod, GetProperty, and basically marshalling generics, just can't work with AOT compilation. In that respect, BRUTE tries some hacks to allow limited support (like Assembly metadata), but it's hacky and greatly increase compilation time. NativeAOT just strips it, and it even has a mode to entirely remove any kind of reflection to drastically reduce the size of the compiled runtime.

**Comment by vpenades** [comment]
@mrhelmut 
> you noted yourself that the vast majority of MonoGame's users care only about 2D

It's like the question of what was first, the chicken or the egg?

The reason because we've stopped doing 3D games is because battling the outdated pipeline, importers, shaders and structures reached a point it was umbearable.

I don't know if at this point it's possible to salvage the 3D side of Monogame. Certainly it's in a vicious cycle: the less developers are interested in doing 3D games with monogame, the less justification will be to expend development time fixing it for 3D.

If there's something I completely agree is this:

> Ultimately, we should look into making the project more maintainable, not more complicated and convoluted than it already is.

I think with the current man power available, it's more important to make things easy to fix and understand, than to improve performance by making things more complicated.

Actually, if I would be me, I would look again into exploring the possibility of making some components virtual (now that it seems consoles are faster?) It's something that's been rejected straight away every time it's been proposed, because consoles don't handle well virtual calls, but I think it would help removing some insanity from the code.

**Comment by mrhelmut** [comment]
> It's like the question of what was first, the chicken or the egg?
> 
> The reason because we've stopped doing 3D games is because battling the outdated pipeline, importers, shaders and structures reached a point it was umbearable.
> 
> I don't know if at this point it's possible to salvage the 3D side of Monogame. Certainly it's in a vicious cycle: the less developers are interested in doing 3D games with monogame, the less justification will be to expend development time fixing it for 3D.

True, but I also feel like XNA wasn't that 3D friendly in the first place. It gave birth to much more 2D games mostly because the sprite batcher is the most accessible API of it. And XNA came in a space where Unity started to get traction on 3D games (while itself not being suited at that time for 2D). It's multi-factorial, I guess, but the problem is indeed where we are now.

My biggest concern here, is that you can't remove the 3D stuff of MonoGame without removing the 2D ones. They're the same pipeline, and if you have a 2D pipeline, you pretty much have a 3D one ready too. Changing the pipeline and introducing more stages is the same problem. You can't add stages to the 3D pipeline without having to figure that out for the 2D path as well. They're the same unique pipeline, the ```SpriteBatch``` class is basically just 3D indexed rendering with a flat projection matrix.
Some graphical APIs (vulkan, dx12) allows to separate the pipelines, but I don't even think if there would be in advantage in doing that besides having the maintain two pipelines instead of one (and having the deal with synchronisation / shared resources between the pipelines).

> I would look again into exploring the possibility of making some components virtual

Would you mind elaborating? I don't think that I get where you're going with this and which problems it might solve.

**Comment by vpenades** [comment]
> > I would look again into exploring the possibility of making some components virtual
> 
> Would you mind elaborating? I don't think that I get where you're going with this and which problems it might solve.

Essentially, the internals of MonoGame have avoided virtual calls, abstract classes, inheritance, interfaces and so on, because it's been stated that consoles are slow at handling virtual calls (vtable lookups, etc), and I guess It's true for NintendoDS and other previous generation consoles, I have no idea if it remains an issue on modern consoles.

But the fact is that, avoiding virtual calls _at all costs_ has shaped MonoGame in what it is right now; all the platforms hardcoded into the main project, which I guess, it's not trivial to maintain because all the platform permutations and #ifdef blocks.... but also, it makes much more difficult to extend monogame in any direction without requiring the abused "fork and compile from source" , which prevents having an ecosystem of compatible components.

Of course I'm talking about the graphics, audio and input subsystems. Maybe it could be possible to refactor things so the core of monogame is truly abstract, and each platform could be located in its own derived project.

There's two advantages:  it's probably easier to maintain isolated projects than a single big project with lots of permutations, and it opens the door for third parties to create derived (but compatible) platform projects (for example, vulkan)

Right now, the biggest problem I see with monogame in terms of maintenance and extensibility is precisely all those forks, each one solving one problem at a time, but no way of taking all these solutions in your own project, because the lack of modularity.

**Comment by flibitijibibo** [comment]
Don't want to interrupt the MG side of things, but I can provide at least some insight for the NativeAOT/BRUTE side:

NativeAOT maintenance can be difficult, but it's a different _kind_ of difficult, in the sense that you are maintaining a PAL rather than a whole runtime - you relinquish some control over the runtime in exchange for not having to maintain the whole dang thing, which is basically what BRUTE is. For FNA so far, we've found that this isn't so bad; we're a little worried that upstream won't care about us but we're hoping our upcoming GDK support will change that.

GDK is sort of our poster child for NativeAOT: Compared to maintaining a whole BRUTE runtime the NativeAOT GDK work has been _much_ less work, even if only because Xbox and Windows are now finally close relatives like they always should have been. Even if upstream rejects it, it won't be as big a deal as maintaining a BRUTE target (and so far it's _much_ less irritating than UWP). We're hoping to have something to share in August.

The contrast to that is Switch, which as always we can't disclose much but we can at least say the NX codebase isn't _worse_ to deal with, and from what our development partners have told us it's competitive in performance (in at least one case it's faster because of the GC alone). I believe a NativeAOT-NX title is in lotcheck now, if you don't hear more about this assume no news is good news.

As always, PlayStation is FNA's blind spot right now, and that's still some time away for us so don't expect to hear from us re: this platform.

**Comment by Lancelotbronner** [comment]
Personally I am working on a 3D game, and like you said since they’re the same pipeline I feel like some more love could be given to the 3D side of things, which will in turn make 2D easier and more powerful.

**Comment by damian-666** [comment]
i dont know if this is relevant and have zero console experince , but  was
curious about why IL code is considered insecure on consoles.. but
 ill throw this out here in case

https://tooslowexception.com/net-jit-compiler-is-not-type-safe/

MSFT answer might be ILVerify..

https://github.com/dotnet/roslyn/issues/22872

i was a bit surprised to read on this thread JIT code isnt allowed on
consoles for security reasons since c++ is all unsafe code,  while c# does
allow  unsafe one of the original goals WAS safe deployability but that
never happened., i guess its the ease of adding executable code,, i have
plugins compiled at runtime from levels  files which i guess coud be modded
if i allowed them unsigned and loaded from modders.   but they can't do
anything unsafe or out of bounds.    I dont even have unsafe code anywhere
yet my performance on heavy physics, fluids and light graphics doesn’t even
need it yet so i could submit a program as "safe" meanng , bounds checked,
and managed..  Also , when gettng a license i read the Android app store
uses the honor system.. Until malicious behavior is reported they don't
test anything, you give your privacy policy and unless someone reports it
its there dong its evil...  so i probably wont go toward consoles for a
while.
anyways im not an engine or library developer i target only pc and droid so
i might be off topic

**Comment by mrhelmut** [comment]
@damian-666 it's insecure because it could allow to run arbitrary code on consoles, which is typically the kind of attack vectors console hackers use to circumvent console securities (e.g. using a glitch in a game to inject code that will be compiled by the JIT to be executed on the machine).

@vpenades Back before MG 3.7 (or something like that), MG had the structure you describe and was less maintainable than it is now. As much convenient as virtuals sound, they often are less readable. Virtuals are doing okay on BRUTE and NativeAOT, they both came up with pretty much the same hack to dampen their impact, but being on AOT or on regular .NET runtime, virtuals don't quite rime with performance and it would make sense to avoid any of it in a graphics/gaming library. And with #4571 in mind, the idea is to totally avoid that problem by having MG into a platform-agnostic assembly (with only one code patch to maintain).

I don't know what you're referring to with "all those forks". If you're referring to console repositories, they are not forks, they are modules of the main repository, which the current structure allows. There is no code duplication.

@flibitijibibo That's some super cool insights. I believe that @harry-cpp would be interested in helping with NativeAOT. And yes, PAL is basically what BRUTE tried, but since BRUTE needs a revamp in addition to upgrading its PAL, it makes NativeAOT in a better position. I would be surprised that Microsoft accepts a GDK implementation upstream (I don't see them adding a ```win-gdk``` target to the core runtime) but at least that should sure open a channel with them. The .NET runtime team seemed very enthusiast about NativeAOT being used in games and they seem very looking forward initiatives like yours.

In any case, it would make total sense that we all concentrate and share efforts on the same runtime.

**Comment by vpenades** [comment]
@mrhelmut 

> @vpenades Back before MG 3.7 (or something like that), MG had the structure you describe...

Thanks for clarifying that aspect. Regarding the forks, I am talking about any time someone wants to add a new feature to monogame outside vanilla, the prefferred approach seems to be a fork instead of an extension/derived library. Whenever someone asks about some feature not in monogame, too often I see the reply "you can use someone's xxx fork which sorted it out" instead of "you can use this library". 

> True, but I also feel like XNA wasn't that 3D friendly in the first place.

It's true that XNA's original 3D side lacks a lot of critical features required to do something not to be ashamed of, but it's also very difficult to add these features if there's not some flexibility on monogame's side. The Shader pipeline system is not the biggest problem here, it's the content pipeline which has a hardcoded architecture that does not align well with modern 3D file formats, In fact it's not possible to write a content importer for gltf or modern fbx. I know because I tried.... and you cannot render what you cannot import.

**Comment by mrhelmut** [comment]
> "you can use someone's xxx fork which sorted it out" instead of "you can use this library"

Let me know if I'm mistaken, but that's a community quote and not a governance quote, right? I don't recall us closing on such discussions with redirecting people to forks.

I feel like this whole discussion is side-tracking. The whole post is about "working toward lifting current limitations so that we can start innovating and have a cleaner code base" and we're being met with "let's ignore the audience depending on those limitations and split monogame in two so that we can have our innovations right now even if that means more work for maintainers".

Please keep this discussion on how to fix BRUTE or enhance NativeAOT. I know that some users are expecting quicker innovations, that will come, but we need to prioritize this. This is not about circumventing limitations, this is about fixing them.

**Comment by vpenades** [comment]
Apologies if I side tracked the discussion, it just happen that to me, both issues are somewhat related. My point was that because consoles, the requirements of BRUTE, etc, have shaped the project in a way that favours certain practices (not good or bad) and makes other practices more difficult (neither good or bad)... and what I tried to discuss is whether it was possible to, at the time of improving BRUTE and moving forward, take into account these other practices and architecture designs into account.

**Comment by mrhelmut** [comment]
Which is what we will be trying to do with #4571 

This post aims at removing the requirements (not ignoring/circumventing them) so that we don't have to favor any practice specifically, and #4571 aims at simplifying maintenance so that we can iterate quicker on features. Once we're there, it'll be a win for everybody.

These are indeed two big projects that will not be achieved over night, so there is indeed some frustration to expect while those are being worked out. I know that frustration is something we wish we could just avoid, but so far we haven't found a solution that fits every side of the coin and doesn't impose maintainability issues on the contributors. It's basically a mexican standoff.

**Comment by TheSpydog** [comment]
> As always, PlayStation is FNA's blind spot right now, and that's still some time away for us so don't expect to hear from us re: this platform.

Bit of an update on this -- we now have the latest upstream version of NativeAOT running on PS5. (In addition to the Switch and GDKX platforms.) It's still early days and it's not ready for production use yet, but if anyone with NDA clearance is interested in contributing or testing it out, feel free to get in touch.

**Comment by egordorichev** [comment]
Thanks a ton to everyone, who is involved in this. The work you've done is truly insane. It is really hard to get into the cycle of how to actually use them, sadly. Something like a list of requirements of net version, library versions & other would go a long way, or maybe a private repo with a sample monogame project, that runs on the consoles by just downloading it, bruting and running a few .bat files. I've ended up debugging a ton of crashes in BRUTE itself, but in the end it looks like my source material was not correct. Brute works well when it does, but if something it expects isn't there, it crashes without any way to understand what's going on, unless you run it with a debugger and analyze the stack trace & local variables

**Comment by mrhelmut** [comment]
This issue will soon be replaced by a Github project and an associated paid bounty by the MonoGame Foundation to accelerate this topic.

**Comment by tomspilman** [comment]
This is now in progress with https://github.com/MonoGame/MonoGame/issues/8194.

**Comment by mrhelmut** [comment]
Just for reference and get expectations right:

It is now safe to development games using .NET 8 and C# 12 features if you're planning to release on consoles. All you have to do, is to make sure that it works with ```PublishAot``` (which basically means that runtime reflection won't work): https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=windows%2Cnet8

Regarding modernizing MonoGame's codebase itself: PR which will make use of recent features but add no functional value will be rejected. This is based on a principle of "what already works, shouldn't be changed to avoid regressions" (even if it feels harmless to you, human errors might occur in either the code or the review, so we prefer to keep already working code away from human errors as much as possible).
