### ISSUE TITLE
Trimming and console friendly serializers.

### ISSUE THREAD

**Issue by vpenades** [MonoGame/MonoGame#7935]
I am aware that the current serializers in built in monogame have issues regarding assembly trimming, because they're reflection based, and trimming does not handle well discovering reflectable types.

I am looking for alternatives for some custom file formats I want to read/write, that can be not only trimmable friendly, but also console friendly.

Right now I'm looking into [Google.Protobuf](https://www.nuget.org/packages/Google.Protobuf) which apparently, supports net4.5 so _theoretically_ it should be compatible with consoles.

Since I don't have access to console branches, I would like to have confirmation, if possible, that this is the case.

I also would like to know if people know about other file formats that meet this criteria: 
- binary
-  console friendly
-  reflection free (trimmable friendly)

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1

#### What operating system are you using:
- Windows

#### What MonoGame platform are you using:

- DesktopGL

**Comment by mrhelmut** [comment]
Trimming is fine and MonoGame should be fine with it too. What's lacking, are trimmer directives to avoid the content type readers to get trimmed. [This trick used to work just fine](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Content/ContentTypeReaderManager.cs), but modern compilers aren't fooled anymore.

Console compilers/runtimes are doing well. They have trimmer directives enabled and documented and the runtimes (being BRUTE or NativeAOT) handle that just fine.

The main issue, is MonoGame.Framework.dll itself on PC and mobile targets which need those directives to avoid users being mislead. There are two points here:
- We need to add [trimming granularity configuration](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-6-0) to either the assembly itself (with the ```IsTrimmable``` attribute) or built into project template by rooting the monogame assembly (which is what we tried doing but apparently the syntax changed over .net core and .net 5 and we ended up removing it from templates)
- Mobile platforms [need an additional treatment](https://learn.microsoft.com/en-us/xamarin/ios/deploy-test/linker?tabs=windows) by adding the ```Preserve``` attribute to each content reader.

In addition to that, we need to document how linking works for users writing their own content readers and redirect them to the official documentation so that they can assimilate that.



(Protobuf is cool but it's not binary-compatible with the XNB format. I believe that changing the serializer would be overengineering a problem that could be fixed with a few attributes, but stuff like protobuf are excellent nonetheless and widely used in the game industry. It might be interesting to have tutorials about that because many developers entering game development over-abuse XML/JSON and this leads to many catastrophic stories.)

**Comment by tomspilman** [comment]
I'm all for adding all the attributes as needed.  Ideally we can do this per-type so that we can target just the content type readers.

**Comment by vpenades** [comment]
To me, the content pipeline and the XNB format makes sense for device resources like textures, fonts, vertex buffers, audio files, etc.

But for general files, I think using XNB is a bit limiting, mostly because the write APIs are not fully exposed (you can only write an XNB file from within a content processor) and also it makes the XNBs version dependant. That limits the flexibility some tooling might require.  (I don't mean to replace XNB by protobuf, just using it side by side)

Anyway, and although I am developing only for windows and mobile, I wanted to check whether protobuf is good to go on consoles, just in case something I am working on moves forward.

**Comment by mrhelmut** [comment]
Protobuf generates generic binary loaders/writers. It'll work anywhere.

There is nothing that strictly require using XNB and the content pipeline on any platform, if that's the concern. The content pipeline is an optional service to avoid having to handle per-platform format/compression (e.g. textures, shaders, audio format), but there's nothing forcing you to use it. I would even (personally) discourage the use of non-graphical assets through the content pipeline and encourage stuff like protobuf or even just using plain '''System.IO''' (which both work fine on all platforms).

The overall take-away is that you can use whatever fits your need, being through the content pipeline or not, it will work on all platforms. If it uses reflection (excluding the current lack of documentation), all you need are compiler directives to avoid some types being trimmed. There are more advanced reflection scenarios which will just not work, but I've almost never seen such uses while porting games to console, so I don't think it's worth detailing that. For the most part, the trimming documentation [does the job](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/incompatibilities).

The one and only thing that we commonly see not working on consoles and mobiles (and PC builds using NativeAOT), is IL code emition. Libraries like NewtonSoft.JSON are known to generate IL code at runtime, but there are forks of it around which have been adapted to work in AOT contexts without IL emition. A good indication is that if a library is labelled as working with Unity, it'll work with MonoGame everywhere.

Also, with NET 6, you can also take advantage of [source generation to generate your own parsers](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation?pivots=dotnet-6-0) without reflection. This is what Microsoft recommends, and techs like Protobuf are actually using pretty much the same approach.

**Comment by damian-666** [comment]
thanx @mrhelmut  pointing all those trimming settings,  my packages work but are bloated..and @vpenades  for pointing  out the open google vault on generalized c++ serialization with .net conformance wrappers generated for net 6 now in there.

  couple questions..if someone wants to see if their code has portability toward consoles, or if you want to onboard some hands to help with MG internals so they can see the c+ backend,  which platform SDK license would be easiest / cheapest to obtain ?    Seems to  you just give an IP address, email, sign the NDA? any upfront fees over 20$ ?  example:  https://developer.nintendo.com/the-process     the ps5 seems harder..      then run an emulator?

   And @mrhelmut re:"... because many developers entering game development "over-abuse XML/JSON and this leads to many catastrophic stories."  its that just the IL  emission u spoke of.??   I've been using [DataContract]  tags and DataContractSerializer in XML ( binary and/or modable)  on droid and windows with very few problems but the source generator thing does already look a bit better.  for collections i  just use a private setter,  and references, and blobs, parsing out thumbnail images work.. everything seems fine so far..

**Comment by vpenades** [comment]
@mrhelmut regarding source generatiors, there's some [horror stories](https://github.com/dotnet/roslyn/discussions/47517#discussioncomment-3542590) that make them much harder to use than what MS initially advertised, so I would stay away from them until MS addresses these issues.

Good to know protobuf is a good option, so I'll carry on with it.

On my side, that's all I wanted to ask... I can close this issue or leave it open for others to discuss more about trimming & serialization.

**Comment by Jure-BB** [comment]
@vpenades [MemoryPack](https://github.com/Cysharp/MemoryPack) and [FlatSharp](https://github.com/jamescourtney/FlatSharp) (FlatBuffers) don't use reflection.

**Comment by mrhelmut** [comment]
Closing this issue in favor of #8104. With .NET, we're moving to the latest formalism to help the trimmer to work without user changes.
