### ISSUE TITLE
Manjaro Linux NullReferenceException

### ISSUE THREAD

**Issue by wizzardcl** [MonoGame/MonoGame#7954]
I have a project under 3.8.0 and tried to run also under 3.8.1 and I get the next exception:

---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MonoGame.OpenGL.GL.LoadExtensions()
   at MonoGame.OpenGL.GraphicsContext..ctor(IWindowInfo info)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.PlatformSetup()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Setup()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, Boolean preferHalfPixelOffset, PresentationParameters presentationParameters)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice(GraphicsDeviceInformation gdi)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
   --- End of inner exception stack trace ---
   at Microsoft.Xna.Framework.GraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)

Steps to reproduce:

- Create a new project for DesktopGL under Manjaro
- Run

Maybe it will be helpful:
I tried to debug the MonoGame and looks like the issue on line 1444 OpenGL.cs (if (Extensions.Count == 0)). I tried to put a breakpoint on line 1446 and 1451 but the debugger (Rider) could not able to set it there and after I tried to move to the next line, the exception appears.

#### What version of MonoGame does the bug occur on:
- MonoGame 3.8.1/MonoGame 3.8.0 (net6)

#### What operating system are you using:
- Manjaro Linux, 22.0.0, Sikaris

#### What MonoGame platform are you using:

- DesktopGL

**Comment by stromkos** [comment]
What video card and driver are you using? 

Run glinfo or glxinfo to verify your OpenGL information.

Short of a hardware failure(corrupt hd, memory, or video card) the only thing near the lines you posted that could cause a null reference is the GL function not mapping to the underlying library.

**Comment by wizzardcl** [comment]
I'm posting result of glinfo.
(JFI Looks like discreet video adapter have died and I'm trying on integrated, but if I'm not wrong when I had Lubuntu I didn't have such issue)
[glinfo.txt](https://github.com/MonoGame/MonoGame/files/9973972/glinfo.txt)

**Comment by damian-666** [comment]
a wild guess but some  general advice on how to approach this class of bug, i had a similar experience wiht the CreateDevice for that worked before upgrating to MG 3.8.1 and Net6 core, ,was tuck for a long time but its solved now.  

Maybe try  the directive #nullable enable   in some classes of your code or the MG sources like the file you mentioned..  With all those flavors of Linux I can't imagine the reality of deploying on that.    that  #nullable will generate warnings here and there, like "might be null," etc..  then you mabye put ? on the  deference to fix the warnings for a start.     The compiler -might -even be able to read into SDL  binary component...  

my isssue went away whenn I used a nullable-context -built unmerged PR for the WPF ->MG interop in craftwork games vault ,that has a custom GraphicsManager service.   the PR verrson It had ? all over the place and  because it was more robust in this way , i dint have to trace MG source, and /or sharpDX source,  and find the thrower.. Was a null window exception and the debugger couldn't go near it.
In my case it probably just tried to set up the device  manager again in a later cycle when the other windowing state was ready because of  deivce context and threading nuances between platforms and netcore  windowing implementon ,   so instead of crashing out  wiht unhandled null Exception,  then it worked like it did  before the update to net6  core , and 3.8.1.
  hope its relevant i dont usually go deep into low level code but now i guess many of us have too..

  mabye   thats why people like RUST so much at low level code..  Seems like nullable  build warnings a is sort of a way to make c# more like RUST, optionally.

https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references

**Comment by wizzardcl** [comment]
Look like an issue with driver/opengl for my GPU. I could build MonoGame (sometimes need to read readme) and in debug I found that Sdl.GL.GetProcAddress return 0x0 for 'glGetString' and it later cause the error.
