### ISSUE TITLE
NativeAOT leads to System.NullReferenceException in Linux

### ISSUE THREAD

**Issue by Odex64** [MonoGame/MonoGame#7958]
I tried to compile a fresh Monogame project with NativeAOT in Linux, however I get the following exception
```
*** MESA_GLSL_CACHE_DISABLE is deprecated; use MESA_SHADER_CACHE_DISABLE instead ***
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Xna.Framework.SdlGameWindow..ctor(Game) + 0x119
   at Microsoft.Xna.Framework.SdlGamePlatform..ctor(Game) + 0x162
   at Microsoft.Xna.Framework.Game..ctor() + 0x4d6
   at CM.Game1..ctor() + 0x14
   at Program.<Main>$(String[]) + 0x1f
   at CM!<BaseAddress>+0x2cfe0b
Aborted (core dumped)
```
I didn't change anything in the project besides the .NET version and its configuration in order to use NativeAOT.

### System
- MonoGame 3.8.1 (DesktopGL)
- .NET 7.1
- Clear Linux*

**Comment by damian-666** [comment]
on related issues it was suggested first  update your graphics drivers..    The other issue is that MG isnt buld with a nullable context, becuase of console limitations.. huge thorny issue:  #7796  .. there are places where null checks might prevent these exceptions, although that might not get around the issue it might help the system to skip some unnecessary binding.

But that doenst mena you cant use nullable warnings to find vulnerable parts of the code.. And Windowing in coreclr is one ,,very delicate, around the dispatcher UI thread , contexts, sync, and message pump stuff that drives UI..    

sometimes in a windowing environemnt context just  trying again later , it will work..... if you open the MG.Framework.Desktop.GL and put #nulllable just on some files you will see warnings like this.

 You can make a MG app  using all its features except the since thread gameloop and the GameComponents,   ( which arent great patterns anyways)  without using the Game class at all BTW.   or mabye you cna try instanciating Game after setting up some of the bindings it depends on..

see the warnings I get.. 

![image](https://user-images.githubusercontent.com/16763801/202921825-d0bb192f-3580-47e4-bb29-65bb904138f2.png)

 You can make a MG app  using all its features except the since thread gameloop and the GameComponents,  without using the Game class at all BTW.   ( which arent great patterns anyways, an ECS and multithreded game loop is more modern, but we use MG to target and potentially render on 11 platfroms)  without using the Game class at all BTW.   or mabye you cna try instanciating Game after setting up some of the bindings it depends on..

some of the warning they can be fixed just with ?   or null checks   But that doesnt mean its fixed.. I would updating drives, that MESA_GLSL_CACHE_DISABLE is deprecated; use MESA_SHADER_CACHE_DISABLE  is a hint,   try making a DeviceManager first,  or some of the things that are assumed to not be null n the game Constructor.    Mabye it just doesnt work on that flavor of linux..

Other thing is some templates build Monogame as a Net6 app, Windows" app on linux. to avoid the console window.. I build on Windows as a Console DX netcore app , im trying to hide the console thing, and i hope to deploy on Linux via VMs.     anywasy hope this might give you things to try.    Otherwise you might have to 1. look for new drivers, 2. build the MG from source, + dependencies.    SDL and such as its all documented.         IN my case I was doing interop and just needed the IGraphicsDeviceService.  my null ref went away as soon as i added ? on al the deferencing so that  the UI thread and windowing state was ready when i finally get it instantiated, thus avoiding a crash on null ref and exit situation.  

htere are some new samples in a brach called MG 3.8.1 that have been updated and work.

keep us informed because gthere are tons of linux flavors  and im wondering if to target it at all via Steam or use Maui .

**Comment by debugnik** [comment]
NativeAOT heavily trims assemblies, removing any reflection metadata not detected as needed, so if you're sure your code doesn't fail normally, my first guess would be that [some reflection member in SdlGameWindow's constructor](https://github.com/MonoGame/MonoGame/blob/cd81db5c8785b1b7642cbf0026e5e4dcd542822f/MonoGame.Framework/Platform/SDL/SDLGameWindow.cs#L113-L115) is returning null under trimming and then dereferenced.

**Comment by gluser2** [comment]
> NativeAOT heavily trims assemblies, removing any reflection metadata not detected as needed

To add to this, you can omit parts of the assembly from reflection with an [rd.xml file](https://github.com/gamedevcb/neonshooter_nativeAOT/blob/main/MyGame/rd.xml) in your project folder. The sample one I linked keeps your Content and the required file mscorlib.dll, at least. Also add this to your .csproj:
`<ItemGroup>
    <RdXmlFile Include="rd.xml" />
</ItemGroup>`

**Comment by mrhelmut** [comment]
RD.xml has been deprecated and should not be used. I'm closing this issue is favor of #8104.
