### ISSUE TITLE
 Translating into Portuguese and Portuguese-BR (Pt-BR)

### ISSUE THREAD

**Issue by BrunoMPVieira** [MonoGame/MonoGame#8073]
**There are many game developers in Brazil. I think it's important to translate the README to PT-BR for a better understanding, considering that the premise of the project is to be "EASY" to create games.**

**Comment by MrValentine7777** [comment]
Hi, 

On behalf of the MonoGame Community, Welcome.

  For the time being, individual learners may utilise free translation services, however, for a business this would not be the case.

If some members from the Brazil side of the ponds can assist in translation, this would speed up the process greatly.

MonoGame is entirely a community driven project, and unfortunately I do not speak/read/write in more than ~two languages and neither of them are PT-BR otherwise I would have started on this by now. If you can reach out to a translation group and work with them to transcribe the documentation, this would go a long way to speed up the process for all.

Thank you for showing your interest in MonoGame, we hope to see your works in the future.

- A MonoGame Community Member.

**Comment by harry-cpp** [comment]
Unfortunately we can't keep docs in languages other than english up to date.

**Comment by BrunoMPVieira** [comment]
Thanks for your personal attention! **Great job!**
