### ISSUE TITLE
Getdata<T> allocates an extra array of T[] 

### ISSUE THREAD

**Issue by circle601** [MonoGame/MonoGame#8304]
### Prerequisites

- [X] I have verified this issue is present in the `develop` branch
- [X] I have searched [open](https://github.com/MonoGame/MonoGame/issues) and [closed](https://github.com/MonoGame/MonoGame/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported.

### MonoGame Version

3.8.1

### Which MonoGame platform are you using?

MonoGame Cross-Platform Desktop Application (mgdesktopgl)

### Operating System

Windows

### Description

Getdata<T> allocates an extra array of T[] GC runs reducing the frame rate

### Steps to Reproduce

```          Rectangle r = new Rectangle(X, Y, 1, 1);
            texture.GetData<Color>(0, r, TextureCheckbuffer, 0, 1);
```

### Expected Behavior

No extra allocations needed

### Resulting Behavior

Color[] is allocated each frame

**Comment by mrhelmut** [comment]
This line:

https://github.com/MonoGame/MonoGame/blob/4a3d5e747ff570fbcd27ba7197d0eeac2606f906/MonoGame.Framework/Platform/Graphics/Texture2D.OpenGL.cs#L254C17-L254C86

and this line:

https://github.com/MonoGame/MonoGame/blob/4a3d5e747ff570fbcd27ba7197d0eeac2606f906/MonoGame.Framework/Platform/Graphics/Texture2D.OpenGL.cs#L271


can't be optimized with traditional ```stackalloc``` or ```Span``` because of the generic type. It could be possible by working with a ```byte[]``` and converting elements in and out from ```T```. Or having static class-wide caching array that grows when required (still garbage-prone, but much less).

This being said, polling ```GetData``` every frame isn't a good practice and it is recommended to rework your logic to avoid relaying on ```GetData``` this much.

**Comment by SimonDarksideJ** [comment]
Does the answer suit your needs @circle601 and can this be closed now?  Due to generics, this is not something solvable at this time.

**Comment by circle601** [comment]
Could we make it use a user provided array?

**Comment by Inverness** [comment]
I recall sometimes reading through the .NET BCL code and seeing cases where unsafe casts to and from a byte span are used in cases where a generic type does not contain references. The implementation of Span<T>.Clear() is relevant in this case: https://github.com/dotnet/runtime/blob/1d8fcf1017d5c47233743470af1dc29382249fd0/src/libraries/System.Private.CoreLib/src/System/Span.cs#L284

Perhaps a similar strategy can be used in this case?

**Comment by Nebulaxin** [comment]
Default stack size is [1.5 MB](https://github.com/dotnet/runtime/blob/90d4c7d41a3fb3390cdcca598fc34cc6b986c75e/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Windows.targets#L36), and that can be not enough for texture; for example, 1024x1024 color texture is 4 MB
