### ISSUE TITLE
question: forum

### ISSUE THREAD

**Issue by nes-girl** [MonoGame/MonoGame#8531]
### Intent

Why is the forum of monogame not accepting new accounts? I,would like to ask questions. You get this message when trying to make an account

### Motivation

/

**Comment by squarebananas** [comment]
![image](https://github.com/user-attachments/assets/c406ab21-bd13-428c-9067-704e7d72e4a0)
[https://community.monogame.net/](https://community.monogame.net/)

**Comment by SimonDarksideJ** [comment]
Appologies @nes-girl , we had to suspend new accounts and activity due to a 1000% fold increase in spam registrations and posts.  We continue to review this and hopefully we can reopen it in the future as we have a significant investment in time and resources in the community site.

The discussions have now moved to the aforementioned [GitHub Discussions](https://github.com/MonoGame/MonoGame/discussions) for posting questions and the [Discord Community](https://discord.gg/monogame) has stepped up as well.

We wish you well on your MonoGame journey.
