### ISSUE TITLE
Font Texture and atlas

### ISSUE THREAD

**Issue by dsaf** [MonoGame/MonoGame#8547]
### Intent

It would be great to be able to specify the rectangular region within the texture atlas to avoid having a separate texture just for the font:
![image](https://github.com/user-attachments/assets/f3e0e3ab-fcd1-4ef0-9952-9c4bc43188be)

### Motivation

* Allows having a single atlas for both sprites and fonts

**Comment by mrhelmut** [comment]
I had to read your message multiple times to understand what you meant, but if I get it correctly, you'd like to be able to use a single sprite sheet that contains both the bitmap font _and_ other sprites, and tell the tool to generate the ```SpriteFont``` out of a sub-space within that sprite sheet? (and assuming that would be more optimized)

Even if that feature is made, the problem is that you would still end up with two separate XNB files that both contain a copy of the texture and both textures (despite being the same) will still end up being loaded independently as copies. You would end up with less source files, but it won't be more optimized at run time.

**Comment by mrhelmut** [comment]
I noted that you do not wish to go into third party libs, but if that may be of any use, I used to use [BMFont](https://www.angelcode.com/products/bmfont/) to generate bitmap fonts and I wrote a binary BMFont file parser in C# and a renderer for MonoGame. I can share that over a gist if looking at it might inspire you or give hints toward writing your own.
