### ISSUE TITLE
MGFX: Compiler optimizations break float4x4 parameters

### ISSUE THREAD

**Issue by WaaghMan** [MonoGame/MonoGame#911]
Hard to explain, but I'm attaching some code:

``` c
float4x4 WorldViewProj : WorldViewProjection;
float4x4 World: World;
float4x4 WorldInverseTranspose : WorldInverseTranspose;


struct VS_INPUT{
    float3 Position: POSITION;
    float4 UV: TEXCOORD0;
    float3 Normal: NORMAL;
};
struct VS_OUTPUT{
    float4 pos:POSITION;
    float4 UV: TEXCOORD0;
    float3 WorldNormal: TEXCOORD1;
    float3 WorldPosition: TEXCOORD2;
};


VS_OUTPUT mainVS(VS_INPUT input){
    VS_OUTPUT output;
    output.pos=mul(float4(input.Position, 1.0), WorldViewProj);
    output.UV=input.UV;
    output.WorldNormal =  normalize(mul(input.Normal, (float3x3)WorldInverseTranspose));
    output.WorldPosition =  mul(float4(input.Position, 1.0), World);
    return output;
}

```

When converting the effect with the 2MGFX tool, it results in the following code:

```
uniform vec4 vs_uniforms_vec4[10];
uniform vec4 posFixup;
const vec4 vs_c10 = vec4(1.0, 0.0, 0.0, 0.0);
vec4 vs_r0;
vec4 vs_r1;
#define vs_c0 vs_uniforms_vec4[0]
#define vs_c1 vs_uniforms_vec4[1]
#define vs_c2 vs_uniforms_vec4[2]
#define vs_c3 vs_uniforms_vec4[3]
#define vs_c4 vs_uniforms_vec4[4]
#define vs_c5 vs_uniforms_vec4[5]
#define vs_c6 vs_uniforms_vec4[6]
#define vs_c7 vs_uniforms_vec4[7]
#define vs_c8 vs_uniforms_vec4[8]
#define vs_c9 vs_uniforms_vec4[9]
attribute vec4 vs_v0;
#define vs_o0 gl_Position
attribute vec4 vs_v1;
varying vec4 vTexCoord0;
#define vs_o1 vTexCoord0
attribute vec4 vs_v2;
varying vec4 vTexCoord1;
#define vs_o2 vTexCoord1
varying vec4 vTexCoord2;
#define vs_o3 vTexCoord2

void main()
{
    vs_r0 = (vs_v0.xyzx * vs_c10.xxxy) + vs_c10.yyyx;
    vs_o0.x = dot(vs_r0, vs_c0);
    vs_o0.y = dot(vs_r0, vs_c1);
    vs_o0.z = dot(vs_r0, vs_c2);
    vs_o0.w = dot(vs_r0, vs_c3);
    vs_r1.x = dot(vs_v2.xyz, vs_c7.xyz);
    vs_r1.y = dot(vs_v2.xyz, vs_c8.xyz);
    vs_r1.z = dot(vs_v2.xyz, vs_c9.xyz);
    vs_r1.w = dot(vs_r1.xyz, vs_r1.xyz);
    vs_r1.w = inversesqrt(vs_r1.w);
    vs_o2.xyz = vs_r1.www * vs_r1.xyz;
    vs_o3.x = dot(vs_r0, vs_c4);
    vs_o3.y = dot(vs_r0, vs_c5);
    vs_o3.z = dot(vs_r0, vs_c6);
    vs_o1 = vs_v1;
    gl_Position.y = gl_Position.y * posFixup.y;
    gl_Position.xy += posFixup.zw * gl_Position.ww;
}
```

As you can see, the vec4 parameter array is sized 10 , when it should be 12 (3 matrices x 4 rows each). Looks like the compiler is optimizing the parameters, since the WorldNormal casts the matrix to a 3x3 float ( XNA didn't allow float3x3 parameters, if I remember well)). I suppose the same thing happens for WorldPosition.

This sounds great, but it breaks when the shader is applied, as it tries to apply effect parameters with wrong sizes in ConstantBuffer.

In this case, the offsets are ok ( 0, 64 and 112), but the amount of data copied isn't ( it tries to copy 64 bytes the three times ).

I'm not sure as to how to fix this, I suppose you should store the parameter size in the MGFX, or calculate it using the offset for the next parameter, instead of supposing it's always 64 bytes for 4x4 matrices).

**Comment by Mloren** [comment]
The same issue also breaks on arrays where elements of the array are not used.
In my shader I have:
`float3 LightPositions[8];`

If in the fragment shader I use all 8 elements then it works fine, but if I only use LightPositions[0] then it appears to optimise away the other 7 elements of the array and then crash with an exception because the size is now different than it expected.

The optimizer shouldn't cause a crash, if it's going to resize the data it needs to keep track of that and account for it.

**Comment by juliand665** [comment]
Just spent multiple hours tracking this down myself. I ran into it because I wanted to transform my normals to world space. I declared the parameter as `Matrix` in both HLSL and C#, but because I was trimming off the w component after applying the transform, the optimizer _helpfully_ optimized out the last row of the matrix for me.

I got a pretty unhelpful error:
![error stack trace](https://user-images.githubusercontent.com/827762/157151769-cbf24d5b-4a1b-4d59-a5d9-8b84bb25e2fe.png)

The fix turned out to be declaring the matrix as `float3x3` in HLSL and just applying that, which I admit is nicer, but the path to that solution should be a _lot_ clearer.
